### ISSUE TITLE
Unknown upload error message

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#1002]
I can't necessarily replicate this error right now, but wanted to log it for reference. 

I attempted to upload a large test file, and before it reached the "Upload complete" status, the platform VERY briefly flashed on a "You've been logged out" message before re-directing back to the upload page. The drag and drop box had the message "[File] is ready for upload."

Upon choosing to upload the file again, the platform returned an error stating "Submission 8 not available for upload." 

![image](https://user-images.githubusercontent.com/13036571/26901893-49c6dcf2-4ba5-11e7-845f-260a57f96641.png)

**Comment by lesgou** [comment]
To add on, after @keileyo encountered this error, I logged in to the same bank and all previous uploads were erased.

**Comment by keileyo** [comment]
Closing this per standup discussion on logging platform errors.
