### ISSUE TITLE
Refactor panel loader

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#1011]
The current panel loader needs to be refactored / upgraded with the following requirements: 

* Rename to _loader_ as opposed to _parser_ to better reflect its function
* Make the project an independent package (jar file) so that it can be run independently
* Remove dependencies on any other project that has runtime implications (i.e. loader joining the `hmda` application cluster, when it shouldn't). This means that it should not depend on `api` or `query` for instance. This might require extraction of common code into separate projects, or code duplication of model objects

**Comment by nickgrippin** [comment]
The dependency on the `query` project comes from the previous issue #807, where we determined the need to drop the institutions table before running the panel loader.  Removing this dependency is possible, but would require creating an admin API endpoint that would delete the table.  Does this solution work, and if so, should it be considered as part of this ticket, or a separate issue?

The dependency on the `api` project is only needed for the JSON protocol.  This could be removed by either duplicating the necessary files into the `panel` project, or moving the JSON protocol into a separate project and adding that as a dependency of both `panel` and `api`.  Either option would also need the `api` model objects, which would also have to be duplicated or moved.  I'm leaning more towards moving the `api` model and JSON protocol into a separate project, but I'm open to other suggestions.

The last question is how this relates to issue #982 and it's associated pull request #985.  Should the PR be closed and the panel file added to the project in this ticket?

**Comment by jmarin** [comment]
On your first question, that issue will not be there since we will end up dropping the PostgreSQL implementation. If one were needed, I would expose it through the API. The whole point of this is to be able to run the panel loader as a standalone process. Right not that is not possible and presents problems when the application is deployed remotely. 

Your second question, yes, it's basically what I suggested in the ticket. A new project (i.e. called `api-model`) might be the common dependency that both `api` and `panel` use. Also, `panel` should be packaged as an independent jar file. 

The last question is about closing the PR that is in flight. Right now there is a question we need to discuss about the data, let's bring it up today. And also there are Travis failures, not sure if they are relevant or not
