### ISSUE TITLE
Update wording in footer

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-platform#1015]
In the footer, under HMDA Platform Tools, please modify "Check Digit Generator" to "Check Digit Tool"

![image](https://user-images.githubusercontent.com/9752096/27137838-d061b484-50d3-11e7-9e1c-12ea4355e15c.png)

**Comment by awolfe76** [comment]
We should just remove these links (or comment them out) until we have the tools ready.

**Comment by nickgrippin** [comment]
Does this ticket belong on the hmda-platform-ui?

**Comment by awolfe76** [comment]
Sure does. Didn't even notice the repo when I saw it. 😜

**Comment by lesgou** [comment]
Sorry, I'll move it. Thought I was in the right repo.
