### ISSUE TITLE
IRS CSV

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#1021]
The MSA/MD name can have a `,` in it, eg "Terre Haute, IN". This causes the downloaded CSVs columns to be misaligned.

## Example file
[2-irs-report.txt](https://github.com/cfpb/hmda-platform/files/1098432/2-irs-report.txt) (update the extension to .csv)

**Comment by schbetsy** [comment]
Could this be solved by putting the MSA/MD name in quotation marks?

**Comment by nickgrippin** [comment]
That seems to be [the standard](https://en.wikipedia.org/wiki/Comma-separated_values#Basic_rules) for escaping the delimiters.
