### ISSUE TITLE
Validation (2017): V155 (Respondent E-mail Address)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#103]
**Edit #:** V155
**Type:** Validity
**Category:** Transmittal Sheet (only)
**Column:** Respondent E-mail Address

A valid e-mail address for the institution must be provided and must be in the format of username@exampledomain.topleveldomain. The e-mail address shall not contain any spaces and must contain only one @ symbol. The e-mail address shall not contain "@.", ".@" and ".." character strings.

Additional resources:
* [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
* [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
* [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by nickgrippin** [comment]
Already implemented.  Cannot find original PR.
