### ISSUE TITLE
IRS endpoint sometimes returns all 0s

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#1031]
Here's one way I've seen this happen:

1. Start the application with docker-compose
2. Create an account and log in
3. Upload a file (I used `edits-M_1124-lars.txt`, but I've seen it happen with others)
4. Verify Macro errors, proceed to Summary/Submission page
5. See that the IRS table isn't there
6. Check the "Network" tab of the developer console. See that the call to the irs endpoint had this response:

```json
{"count":0,"total":0,"msas":[],"summary":{"homeImprovement":0,"multiFamily":0,"lars":0,"FSA":0,"FHA":0,"amount":0,"oneToFourFamily":0,"refinance":0,"MFD":0,"conv":0,"homePurchase":0,"VA":0},"_links":{"self":"?page=1","prev":"?page=1","last":"?page=0","next":"?page=0","first":"?page=1","href":"/institutions/6999999/filings/2017/submissions/1/irs{rel}"}}
```

In my observation, it seems to happen on the first file submitted after starting the app. Needs confirmation.

**Comment by awolfe76** [comment]
Sounds like this one could use a UI issue too? If we see an empty `"msas":[]` we should handle that better.

**Comment by nickgrippin** [comment]
I'm still having trouble replicating this issue.  Does refreshing the page work, or will the response continue to return empty?  

The only thing I can see that would cause this issue is the IRS stats not persisting fast enough.  They're only stored once the `HmdaFileValidator` reaches the `CompleteValidation` step, which would be right before the IRS stats are viewed.

**Comment by awolfe76** [comment]
I've seen this happen too. Haven't seen it in a while but when I did a refresh did not fix the problem, the API just returned the empty response.

_Going to create a separate issue to track this, but I saw something similar happen with the `/summary` endpoint this morning. The UI handled this better than it did the IRS, but could be even better there too._

**Comment by schbetsy** [comment]
+1 to what Andrew said. The IRS endpoint returns the same response every time I hit it. So if it came back empty once for a submission, it will continue to for that submission.

**Comment by nickgrippin** [comment]
I'm still having issues replicating this issue.  The only line I can think would cause this to fail is [here](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/scala/hmda/persistence/processing/HmdaFileValidator.scala#L261).  After talking with Juan, there's a possibility that a message occasionally won't send successfully.  Unfortunately, there's no way to fix this without sacrificing asynchronous behavior.

I'm currently trying adding `yield`, but it's difficult to tell if that actually changes anything.

**Comment by awolfe76** [comment]
I saw this again this morning but didn't have the #1051 fix in my build. Just wanted to make a quick note of it though. I'll run through things with that fix soon.

**Comment by nickgrippin** [comment]
Re-opening since this is bug is still occurring.

**Comment by nickgrippin** [comment]
So, the IRS bug can be replicated (in full docker-compose) with these steps:
1.  Create a new upload (doesn't have to be the first submission)
2.  Upload a file with only quality/macro edits
3.  **Don't validate the edits**  Instead, wait for about a minute or two.
4.  The `submission-lar-stats` actor, along with a bunch of other actors, will terminate.  You'll see about 5 successive messages in the logs all starting with "Actor stopped at..."
5.  Now, go through and validate the edits.  Go to the confirmation page, and the IRS will not appear.

**Comment by schbetsy** [comment]
I'm smoke testing this now. When you say "Don't validate the edits", do you mean "don't verify"? (Validation happens automatically, so I don't think there's a way to not validate).

**Comment by awolfe76** [comment]
> When you say "Don't validate the edits", do you mean "don't verify"? 

Yeah, that's right. _Sorry so late._
