### ISSUE TITLE
Validation (2017): V108 (Parent Name)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#104]
**Edit #:** V108
**Type:** Validity
**Category:** Transmittal Sheet (only)
**Column:** Parent Name

If parent name is reported, then parent name cannot equal institution name.

Additional resources:
* [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
* [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
* [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by schbetsy** [comment]
Closed by #346
