### ISSUE TITLE
Summary endpoint returned 404

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#1040]
Steps I took after a fresh re-build:

1. Created a new account under `bank0`
1. After logging in and getting to the institutions page went directly to the "Upload a new file"
1. Used `clean_10-lars.txt`
1. After the process completed I went straight to the confirmation page.
1. Saw the error in the UI, "Sorry, we couldn't find the data you're looking for. Please refresh the page. If this message persists, you will need to upload your file again."

<details><summary>Console logs</summary><p>

```
Failed to load resource: the server responded with a status of 404 (Not Found)
:4443/hmda/institutions/6999998/filings/2017/submissions/2/summary
08:57:45.008 app.min.js:50511 got res Response 404
08:57:45.013 app.min.js:45000  action @ 08:57:45.008 RECEIVE_ERROR
08:57:45.014 app.min.js:48565 Error: 404: Not Found
    at app.min.js:48560
    at <anonymous>
```

</p></details>

---

I tried both refreshing the page and logging out and back in; both gave the same response.

I attempted the same steps later and the API was successful.

**Comment by nickgrippin** [comment]
Was there a previously existing submission, or was this a new filing?  Just want to make sure that the `submissions/2` part is correct.

**Comment by schbetsy** [comment]
@wpears pointed out this error to me as well. According to him, it consistently happens for the first submission after logging in with `bank0`. I think this is an issue with the demo data, since Bank 0 get pre-loaded with incomplete data for a few submissions. 

I suspect that if we delete the (now-unnecessary) demo submissions from the demo data, this will no longer be an issue.

**Comment by awolfe76** [comment]
`submissions/2` is correct in this case.

I went straight to submit a new file because of the issue @wpears and @schbetsy point out, the existing submission for `bank0` always fails (I agree with @schbetsy about the demo data).

**Comment by awolfe76** [comment]
See https://github.com/cfpb/hmda-platform/pull/1041#issuecomment-315396866

I then went back to the upload page and uploaded a new file ... without refreshing or logging out. This upload was successful and the `/summary` endpoint was as well.

**Comment by schbetsy** [comment]
More data: according to @awolfe76 , this bug only happens on docker-compose, not on the cluster.

**Comment by schbetsy** [comment]
@awolfe76 I haven't been able to reproduce this error lately. Have you?

**Comment by awolfe76** [comment]
No, I haven't. I'll try to reproduce this today.

**Comment by hkeeler** [comment]
This just occurred for me when using the Compose setup, and a fresh rebuild of everything on master.  It was against Bank 0, and was my first submission.  

```json
{
  "httpStatus":404,
  "message":"submission 6999998-2017-1 not found",
  "path":"/institutions/6999998/filings/2017/submissions/1/summary"
}
```

Subsequent submissions went through without issue.  Additionally, once I rebuilt everything _again_, the problem did **not** reoccur.

**Comment by awolfe76** [comment]
Just saw the same thing again ... fresh build. See https://github.com/cfpb/hmda-platform/issues/1040#issuecomment-329836272, same details.

Refresh does not fix it.
