### ISSUE TITLE
Validation (2017): V110 (Parent Mailing Address)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#105]
**Edit #:** V110
**Type:** Validity
**Category:** Transmittal Sheet (only)
**Column:** Parent Mailing Address

If respondent is a mortgage banking subsidiary (MBS) or a nondepository institution that has an affiliation with a depository institution, then parent name of the MBS or the depository institution that the nondepository institution is affiliated with along with the address, city, state and zip code must not = blank.

Additional resources:
* [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
* [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
* [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by kgudel** [comment]
This seems like it requires panel.

**Comment by jmarin** [comment]
@kgudel It does

**Comment by nickgrippin** [comment]
Blocked by panel requirement

**Comment by hkeeler** [comment]
Can we give this description a bit of love?  I'm having a hard time parsing the run-on sentence.

>If respondent is a mortgage banking subsidiary (MBS) or a nondepository institution that has an affiliation with a depository institution, then parent name of the MBS or the depository institution that the nondepository institution is affiliated with along with the address, city, state and zip code must not = blank.

First off, can we define what _affiliated with_ means?  Does that mean it's _parent_?  The term seems broader than that, but that's what makes the most sense in context with the rest of the description.

I _think_ the logic for this is supposed to be (hope this pseudo-code makes sense):

```python
if (respondent.type == 'mbs' or (respondent.type == 'non-di' and respondent.parent.type == 'di')) and
   (ts.parent_name == '' or ts.parent_address == '' or ts.parent_city == '' or ts.parent_state == '' or ts.parent_zip == ''):
        
    fail
else:
    pass
```
...because I _could_ read the first statement as...

```python
if ((respondent.type == 'mbs' or respondent.type == 'non-di') and respondent.parent.type == 'di') and...
```

...though I'm pretty sure this isn't the case after reading this a few dozen times.

I think I finally get it.  Can this be simplified to the following?

>If the respondent is a mortgage banking subsidiary (MBS)**,** or a non-depository institution affiliated with a depository institution, then fields _Parent Name_, _Parent Address_, _Parent City_, _Parent State_, and _Parent Zip Code_ must not be blank.

**Comment by lesgou** [comment]
@hkeeler Your simplification of the edit is accurate. 
@Kibrael and I did some research into what affiliate means, and we have an initial ticket in GHE panel. @Kibrael has more details.

**Comment by Kibrael** [comment]
Here is the affiliate definition posted in the HMDA-Panel-Dev repo: 
(k) Affiliate.-For purposes of this chapter, the term "affiliate" means any company that controls, is controlled by, or is under common control with another company.

The logic for this edit may be:
institution type in (9, 10, 11, 12, 13, 15, 16, 17, 18)

This will take a little work figuring out the coding logic for some of those institution types. We have an outstanding question with the FRB, @debseidner may have updates.

**Comment by debseidner** [comment]
Unfortunately no updates from the FRB. Agree with logic above.

**Comment by hkeeler** [comment]
@lesgou and @Kibrael, thanks for the clarification.  Sounds like there's more to come. :)

**Comment by lesgou** [comment]
Almost similar to #178
