### ISSUE TITLE
Q054: edit does not trigger or hangs

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#1079]
This edit did not return a failure result for the test file. The file was sent to a local instance of the back-end interactive API mode. Original issue #227.

The file was tested in python with the following results: 417 rows failed the edit criteria (numerator) and 461 rows were purchased loans (denominator) resulting in a 90% fail rate. This should trigger the edit as the threshold is >1%.

I am unable to validate Cassandra and Zookeeper and the other pieces as I don't know how to do that. If you believe this result is in error, let me know and I will close the issue.

**Comment by keileyo** [comment]
:+1:

**Comment by lesgou** [comment]
@Kibrael please add more details as per https://github.com/cfpb/hmda-platform/issues/1078
