### ISSUE TITLE
Q055: edit does not trigger or hangs

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#1080]
This edit did not return a failure result for the test file. The file was sent to a local instance of the back-end interactive API mode. Original issue #231.

The file was tested in python with the following results: 432 rows failed the edit criteria (numerator) and 498 rows were originations (denominator) resulting in an 86% fail rate. This should trigger the edit as the threshold is >5%.

I am unable to validate Cassandra and Zookeeper and the other pieces as I don't know how to do that. If you believe this result is in error, let me know and I will close the issue.

**Comment by lesgou** [comment]
@Kibrael please add more details as per https://github.com/cfpb/hmda-platform/issues/1078

**Comment by schbetsy** [comment]
Thanks for the follow up details, @Kibrael.

(Possibly related), I noticed an issue with the edit logic in this line: https://github.com/cfpb/hmda-platform/pull/678/files#diff-23a6c44934e7c79ec393678539a66be3R26. When testing whether `rateSpread` is ≥ 5%, we should not coerce that value to an `Int`.
