### ISSUE TITLE
Q062: edit doesn't trigger or hangs

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#1081]
This edit did not return a failure result for the test file. The file was sent to a local instance of the back-end interactive API mode. Original issue #228.

The test file was checked in python with the following results: 452 rows failed the edit criteria (numerator) and 494 rows were originations (denominator) resulting in a 91% fail rate. This should trigger the edit as the threshold for fails is >1%.

I am unable to validate Cassandra and Zookeeper and the other pieces as I don't know how to do that. If you believe this result is in error, let me know and I will close the issue.

**Comment by lesgou** [comment]
@Kibrael please add more details as per https://github.com/cfpb/hmda-platform/issues/1078
