### ISSUE TITLE
Q065: edit doesn't trigger or hangs

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#1083]
This edit did not return a failure result for the test file. The file was sent to a local instance of the back-end interactive API mode. Original issue #230.

The file was tested in python and contains 448 rows with HOEPA = 1. A count of >= 200 HOEPA rows should cause the edit to trigger.

I am unable to validate Cassandra and Zookeeper and the other pieces as I don't know how to do that. If you believe this result is in error, let me know and I will close the issue.

**Comment by lesgou** [comment]
@Kibrael please add more details as per https://github.com/cfpb/hmda-platform/issues/1078
