### ISSUE TITLE
V317: edit does not trigger back end API

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#1084]
This edit did not return a failure result for any of the rows in the test file. The file was sent to a local instance of the back-end interactive API mode. Original issue #141.

The file was tested in python showing that 200 rows had co-applicant ethnicity = 5 and co-applicant sex = 5. 0 rows had co-applicant race = 1. This should result in 200 rows returned as fails for this test file.

I am unable to validate Cassandra and Zookeeper and the other pieces as I don't know how to do that. If you believe this result is in error, let me know and I will close the issue.

**Comment by lesgou** [comment]
@Kibrael please provide more details. Is this checking the test or the code? Or is that the same thing?
