### ISSUE TITLE
V326: Edit does not trigger back-end API

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#1085]
This edit did not return a failure result for any of the rows in the test file. The file was sent to a local instance of the back-end interactive API mode. Original issue #154.

The file was checked in python. 200 rows had values of 8 for co-applicant race 1 and 5 for co-applicant ethnicity. 0 rows had 5 for co-applicant sex. This should have resulted in 200 fails when the file was sent to the API. 0 rows returned as failures.

I am unable to validate Cassandra and Zookeeper and the other pieces as I don't know how to do that. If you believe this result is in error, let me know and I will close the issue.

**Comment by lesgou** [comment]
@Kibrael please provide more details. Is this checking the code or the test? or both?

**Comment by nickgrippin** [comment]
@lesgou, @Kibrael: According to [this comment](https://github.com/cfpb/hmda-platform/issues/154#issuecomment-220037809), we coded the edit as follows:

* If co-applicant sex is 5, then co-applicant race must be 8 and co-applicant ethnicity must be 5.

This would explain why David saw no failures from his test file.  None of them had co-applicant sex equal to 5, so the edit never checked the race and ethnicity.  However, from what I'm reading, the logic should be reversed and the "and" switched to an "or":

* If co-applicant race is 8 or co-applicant ethnicity is 5, then co-applicant sex must be 5.

**Comment by nickgrippin** [comment]
This exact same confusion seems to be the problem in #1084 and #1086.

**Comment by Kibrael** [comment]
The way I understand it is that if a "no co-applicant" enumeration is selected for one, then it must be selected for all three. That's why there are three edits that check it from different angles. 

I think that putting logic like "if co-applicant race 1 = 8 and co-applicant ethnicity = 5 and co applicant sex != 5 then FAIL" should check the edit as I understand it. Does that make sense?

**Comment by lesgou** [comment]
So, edits V326, V463 and V317 check this from all directions - ethnicity, race, and sex, so I don't think we need to reverse the logic. 

However, these should be implemented as "and/or"

V326: Co-Applicant sex does not = 5; however, co-applicant ethnicity = 5 **and/or** co-applicant race field 1 = 8.

V463: Co-Applicant ethnicity does not = 5; however, co-applicant race field 1 = 8 **and/or** co-applicant sex = 5.

V317: Co-Applicant race field 1 does not = 8; however, co-applicant ethnicity **and/or** co-applicant sex = 5.

**Comment by lesgou** [comment]
This is the edit from a passing point of view:

V326: Co-Applicant sex equals 5, then (co-applicant ethnicity must equal 5) and (co-applicant race: 1 must equal 8)

V463: Co-Applicant ethnicity equals 5, then (co-applicant race: 1 must equal 8) and (co-applicant sex must equal 5)

V317: Co-Applicant race: 1 equals 8, then (co-applicant ethnicity must equal 5) and (co-applicant sex must equal 5)

**Comment by nickgrippin** [comment]
@lesgou: That follows the logic of our edit.  We check to see if co-applicant sex equals 5, if it does then check the other two fields.  

However, in the test file, "0 rows had 5 for co-applicant sex".  That means the other two fields aren't checked, so the edit passes.  Is this an error with the test file?  The conditions described in the test file (sex = 0, ethnicity = 5, race = 8) mean it would fail both of the other edits (V463 and V317).

**Comment by lesgou** [comment]
Updating to:

V326: If co-applicant sex = 1, 2, 3, or 4, then (co-applicant ethnicity must equal 1, 2, 3, or 4) AND (co-applicant race: 1 must equal 1, 2, 3, 4, 5, 6, or 7).

V463: If co-applicant ethnicity equals 1, 2, 3, or 4, then (co-applicant race: 1 must equal 1, 2, 3, 4, 5, 6, or 7) AND (co-applicant sex must equal 1, 2, 3, or 4).

V317: If co-applicant race: 1 equals 1, 2, 3, 4, 5, 6, or 7, then (co-applicant ethnicity must equal 1, 2, 3, or 4) AND (co-applicant sex must equal 1, 2, 3, or 4).

**Comment by nickgrippin** [comment]
All right... Final version:

**V326**: If co-applicant race is 8 **OR** co-applicant ethnicity is 5, then co-applicant sex must be 5

**V463**: If co-applicant race is 8 **OR** co-applicant sex is 5, then co-applicant ethnicity must be 5

**V317**: If co-applicant ethnicity is 5 **OR** co-applicant sex is 5, then co-applicant race must be 8

To clarify, if any single field indicates there is no co-applicant, all fields must indicate there is no co-applicant.
