### ISSUE TITLE
V463: Edit does not trigger back-end API

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#1086]
This edit did not return a failure result for any of the rows in the test file. The file was sent to a local instance of the back-end interactive API mode. Original issue #140.

The file was checked in python showing that 200 rows had co-applicant race 1 = 8 and co-applicant sex = 5. The file had 0 rows with co-applicant ethnicity = 5. This indicates that the platform should return 200 fails when passed this test file.

I am unable to validate Cassandra and Zookeeper and the other pieces as I don't know how to do that. If you believe this result is in error, let me know and I will close the issue.

**Comment by lesgou** [comment]
@Kibrael can more details be provided please? Is this checking the test or the edit?
