### ISSUE TITLE
Include a Version Number in Health Check

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-platform#1099]
Having a good way to quickly confirm the version number of the platform in the cluster will help greatly with bug hunting.

**Comment by nickgrippin** [comment]
Right now, I think the only place the version number exists is in Git.  Implementing this would probably require adding some variable or configuration setting to reference the version number, which in turn would require a change every time we push out a new release.

Not saying this shouldn't be implemented, just trying to get a full idea of the work involved.

**Comment by jmarin** [comment]
This can be done with the sbt release plugin. But it's another thing to configure and deploy, which takes time. I guess my question is, how many versions are we running that causes confusion?

**Comment by ericspry** [comment]
Arose from discussion today. This is in the "nice to have" category and not a priority for beta. Backlog for now, but wanted to capture the ticket
