### ISSUE TITLE
V110: Institution type for 'affiliate' is set incorrectly.

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#1106]
V110  (original ticket #105) uses the incorrect institution type for affiliate, code 8. The correct institution type for affiliate is 18.

Affiliate enumerations are set [here](https://github.com/cfpb/hmda-platform/blob/0acae4d94ab6394c1766c780493bf745eaf9acd1/parser/shared/src/main/scala/hmda/parser/fi/InstitutionParser.scala).

**Comment by jmarin** [comment]
Duplicate of #1070?

**Comment by Kibrael** [comment]
Yes, it is, apologies.
