### ISSUE TITLE
V280: Does not return correct number of row failures

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#1107]
V280 (original ticket #133 ) gives incorrect results.

Steps to reproduce:

While running dev dependencies (docker-compose -f docker-dev.yml up) in one session, start the api locally (with sbt, project api, clean, reStart)

Using Postman, create a submission for bank 0

Upload the V280 test file (in the shared drive at HMDA > Platform > HMDA Edits > Validation Testing > Test Files > Validity > V280.txt)

Check the edit results endpoint for this submission (localhost:8080/institutions/6999998/filings/2017/submissions/1/edits)

Expected result: V280 should return 200 failures.
Actual result: V280 returns 133 failures.

Python was used to check that the test file is correct, so it's not an issue with the test file. The file has 200 rows. Of these 67 have null values for MSAs and 133 invalid MSAs. It appears that the edit is not failing rows with null values in the MSA field.

**Comment by nickgrippin** [comment]
This problem is pretty easy to fix.  A lot of values in the `CBSATractLookup` have blank MSAs or MDs, which means the edit check `validMSA or validMD or NA` will always return true for a blank MSA/MD.
