### ISSUE TITLE
V500: Edit does not return correct number of failures for test file

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#1108]
V500 (original ticket #165) gives incorrect results.

Steps to reproduce:

1. While running dev dependencies (`docker-compose -f docker-dev.yml up`) in one session, start the api locally (with `sbt`, `project api`, `clean`, `reStart`)
2. Using Postman, create a submission for bank 0
3. Upload the V500 test file (in the shared drive at HMDA > Platform > HMDA Edits > Validation Testing > Test Files > Validity > V500.txt)
4. Check the edit results endpoint for this submission (`localhost:8080/institutions/6999998/filings/2017/submissions/1/edits`)

Expected result: V500 should return 200 failures. 
Actual result: V500 returns 147 failures.

Python was used to check that the test file is correct, so it's not an issue with the test file. The file has 200 rows. Of these 119 have null values for rate spread and 81 have "9A%01" for rate spread. 

(minor edits for formatting. - Betsy)

**Comment by nickgrippin** [comment]
I think this edit may be coded correctly.  The test file on the shared drive actually has:

- 53 rows with "NA"
- 66 rows with a blank ("") string
- 81 rows with "9A%01"

Given these values, we should see 66 + 81 = 147 failures for the V500.txt test file.

**Comment by keileyo** [comment]
Agree with @nickgrippin. NA is a valid response for Rate Spread, so rows reporting NA should not fail V500. Can confirm that the V500 test file on the shared drive has rows with NA reported for rate spread.

**Comment by nickgrippin** [comment]
Closing the ticket, the current implementation is correct.
