### ISSUE TITLE
Research Alternate Approaches to Project Configuration

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-platform#1117]
When `assembly` is used to create the .jar for this project all of the individual project configurations are concatenated into one large `application.conf` file. To view this file one can create the jar using `sbt assembly`, expand the .jar and open the file in any text editor. One can also vim into the .jar and look at the file that way.

When the configuration files are concatenated together into one large `application.conf` file there are many duplicate entries. For example: `akka {loglevel = "INFO"}` occurs many times throughout the file. Within this file duplicates are tolerated, however, [only the last entry is used](https://github.com/typesafehub/config#features-of-hocon).

This has led to several unexpected behaviors:
1. `cluster.name` always defaults to `hmda` regardless of the env `HMDA_CLUSTER_NAME`
1. All logging defaults to `OFF`
1. `hmda.persistent-actor-timeout` defaults to `60` which causes the platform to hang on validation and never validate a file if `HMDA_IS_DEMO=false`

In all three of these instances these config values occur multiple throughout the .jar `application.conf` file and have different values through their instances, and generally the values from the `validation` project are the one's used as that is the last project to occur in the .jar's `application.conf`.

Further complexity is added when `HMDA_IS_DEMO=true`. In this case a second configuration file, `application-dev.conf, is added in and used by certain parts of the codebase. This configuration file then has its own defaults. As such, the `HMDA_IS_DEMO` flag can have large and unexpected effects on how the platform runs.

As a short term fix unwanted config values can be overwritten by passing in runtime arguments. For example, to change the value of `hmda.persistent-actor-timeout` from `60` to `3600` and to turn logging from `OFF` to `INFO` the following can be run:
```
jre*/bin/java -Dhmda.persistent-actor-timeout=3600 -Dakka.loglevel=INFO -jar hmda.jar
```
In the long run it would appear that we need a new method by which we merge our configuration files or a new way of constructing these files in order to prevent these unexpected interactions for the future.

**Comment by jmarin** [comment]
Many of the issues described in this issue are already solved in the `cluster-roles` WIP PR, where the configuration for clustering is centralized, and most (if not all) of the redundant configuration settings have been removed. The remaining issue might be the `HMDA_IS_DEMO` flag, which I have thought for some time that should be removed altogether (along with the hacky methodology for loading demo data; panel loader should be used instead)
