### ISSUE TITLE
Include filename in the /submissions endpoint

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform#1119]
The filename for a submission is ingested via the upload's Content Disposition and is being saved and used for the summary. See [here](https://github.com/cfpb/hmda-platform/blob/e682f7d6c95b870beb6d084cb17ccf2d9e6a6be1/persistence/src/main/scala/hmda/persistence/processing/HmdaRawFile.scala) and [here](https://github.com/cfpb/hmda-platform/blob/88afb4962acdc642eac9e14995706456511a4821/api/src/test/scala/hmda/api/http/institutions/submissions/SubmissionSummaryPathsSpec.scala).

We display the filename at different times, across refreshes, to different users of the same institution, and different filings. Using localStorage doesn't cover all these use cases and disrupts our state modeling.

If the filename is available as a key in the [submission](https://github.com/cfpb/hmda-platform/blob/master/Documents/API.md#latest-submission), this would clean up some nasty code on the front-end and allow us to display the correct filename in all cases for a given submission.

**Comment by schbetsy** [comment]
So you'd like to see something like this as the JSON structure for submissions?

```json
{
    "id": {
        "institutionId": "6999998",
        "period": "2017",
        "sequenceNumber": 1
    },
    "filename": "my_bank's_lars_2017.txt",
    "receipt": "",
    "status": {
        "code": 1,
        "message": "created",
        "description": "The filing period is now open and available to accept HMDA data."
    },
    "end": 0,
    "start": 1504805019722
}
```

... with `filename` as a key in the JSON, in all the places where submissions are included in API responses

**Comment by wpears** [comment]
Yep, that looks good to me.

**Comment by schbetsy** [comment]
Editing my post above. There's already a pattern of using `fileName` instead of `filename` in the platform, so I'm using that as the JSON key.
