### ISSUE TITLE
Upgrade Akka version to 2.5.1

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#1134]
Note: Akka in memory persistence needs to be upgraded in sync with Akka

**Comment by schbetsy** [comment]
According to `Dependencies.Scala` There are 6 packages that currently all version in sync with Akka (excluding packages that are only in `test`). They are:
- `akka-slf4j`
- `akka-cluster`
- `akka-cluster-tools`
- `akka-stream`
- `akka-persistence`
- `akka-persistence-query`

Can I upgrade them all to `2.5.1`, or should I only upgrade the two packages you specifically mentioned?

**Comment by jmarin** [comment]
All of these should be on the same version
