### ISSUE TITLE
Performance and Intent behind Load Balancer

### ISSUE THREAD

**Issue by charandas** [cfpb/hmda-platform#1329]
Hi Folks,

I am running hmda-platform at work using your docker workflow on Rancher/Swarm. The load balancer does not seem to work on the IPSec overlay network provided by rancher. It ends up having affinity to 1 out of say 3 API instances.

Either way, before I get too deep into infrastructure troubles, thought I would take a step back and learn about how the API works as far as submission of LARs and performance one can expect.

`/institutions/<institutionId>/filings/<period>/submissions/<submissionId>` seems like the first API that's hit per the [docs](https://github.com/cfpb/hmda-platform/blob/master/Documents/API.md#submission-by-id).

I notice that it then calls this a bunch of times:
`https://baseUrl/hmda/institutions/6999999/filings/2017/submissions/latest`. So for a file 5509 lines in length, (edits-M_5508-lars.txt from your examples), takes 45 seconds on my unscaled instance.

It seems like a polling approach in action. Is there any way to speed up the process its waiting on? We are trying to do 15000 records in our LARs and could appreciate some more speed.

**Comment by schbetsy** [comment]
Hi @charandas! Thanks for your patience.

I don't think we can help with your infrastructure woes, unfortunately. We only use the load balancer in local dev builds. We have a different devops setup in Production, so we haven't seen the same issues that you have.

But, to answer your question: You're right, the front-end uses the `/latest` endpoint to poll until the upload, parsing, and validation process finishes. The bulk of that time is spent in validation, which is the step where each line of the file goes through the 150 edits that ensure the accuracy of the data (See the [2017 Filing Instruction Guide](https://www.consumerfinance.gov/data-research/hmda/static/for-filers/2017/2017-HMDA-FIG.pdf) for more information about edits).

This validation process is the core of the HMDA filing platform, and it takes time, especially for large files. We’ve architected it according to reactive principles to handle a large number of simultaneous filers, so system availability was a higher priority than single file performance.

**Comment by charandas** [comment]
Thanks for the info @schbetsy. Thats super helpful. Will close.

**Comment by charandas** [comment]
I saw elsewhere you are using DC/OS. That’s exciting.
