### ISSUE TITLE
Investigate missing Institution records

### ISSUE THREAD

**Issue by nickgrippin** [cfpb/hmda-platform#1352]
Some institutions seem to be missing their records in the `InstitutionView`.  These institutions will still have Filing objects and Institution records with the `InstitutionPersistence` actor.  This might be causing a bug where a bank only sees a spinning icon when they login, preventing them from starting or continuing a submission.

**Comment by jmarin** [comment]
Suggestion: merge `InstitutionView` into `InstitutionPersistence` logic, it simplifies things and probably also solves this bug.

**Comment by colleenms** [comment]
We also have a few institutions whose domains are not being recognized in platform, even after creating the JSON files. I'll send the domains via email.
