### ISSUE TITLE
Random error with akka 

### ISSUE THREAD

**Issue by charandas** [cfpb/hmda-platform#1359]
I need some help ascertaining why API fails to start the filing api on port 8080, port 8081 (admin) and 8082 (public) respond well, but here is the difference between successful and failure logs:

```
# FAIL
11/30/2017 4:41:57 PM[2017-11-30 21:41:57,087][INFO ][main] New Cassandra host cassandra/10.42.16.11:9042 added
11/30/2017 4:42:05 PM[2017-11-30 21:42:05,728][WARN ][hmda-akka.actor.default-dispatcher-25] Couldn't join seed nodes after [2] attempts, will try again. seed-nodes=[akka.tcp://hmda@127.0.0.1:44741]
11/30/2017 4:42:05 PM[2017-11-30 21:42:05,731][WARN ][hmda-akka.actor.default-dispatcher-25] Remote connection to [null] failed with java.net.ConnectException: Connection refused: /127.0.0.1:44741
11/30/2017 4:42:05 PM[2017-11-30 21:42:05,731][WARN ][hmda-akka.actor.default-dispatcher-25] Association with remote system [akka.tcp://hmda@127.0.0.1:44741] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://hmda@127.0.0.1:44741]] Caused by: [Connection refused: /127.0.0.1:44741]
11/30/2017 4:42:10 PM[2017-11-30 21:42:10,698][ERROR][hmda-akka.actor.default-dispatcher-3] Timeout in Joining!
11/30/2017 4:42:10 PM[2017-11-30 21:42:10,700][ERROR][hmda-akka.actor.default-dispatcher-5] Terminating system, because constructr-machine terminated!
11/30/2017 4:42:10 PM[2017-11-30 21:42:10,718][INFO ][hmda-akka.actor.default-dispatcher-41] Shutting down remote daemon.
11/30/2017 4:42:10 PM[2017-11-30 21:42:10,719][INFO ][hmda-akka.actor.default-dispatcher-41] Remote daemon shut down; proceeding with flushing remote transports.
11/30/2017 4:42:10 PM[2017-11-30 21:42:10,738][INFO ][hmda-akka.actor.default-dispatcher-41] Remoting shut down.
```

```
# SUCCESS
11/30/2017 4:42:57 PM[2017-11-30 21:42:57,820][INFO ][main] New Cassandra host cassandra/10.42.16.11:9042 added
11/30/2017 4:42:57 PM[2017-11-30 21:42:57,841][INFO ][hmda-akka.actor.default-dispatcher-21] *********ATTEMPTING CONNECTION TO CASSANDRA QUERY CLUSTER********
11/30/2017 4:42:57 PM[2017-11-30 21:42:57,841][INFO ][hmda-akka.actor.default-dispatcher-21] Using native clock to generate timestamps.
11/30/2017 4:42:57 PM[2017-11-30 21:42:57,841][INFO ][hmda-query-dispatcher-43] Started submission signed event subscriber validator at akka://hmda/user/query-supervisor/singleton/$a
11/30/2017 4:42:57 PM[2017-11-30 21:42:57,926][INFO ][hmda-akka.actor.default-dispatcher-21] Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
11/30/2017 4:42:57 PM[2017-11-30 21:42:57,926][INFO ][hmda-akka.actor.default-dispatcher-21] New Cassandra host cassandra/10.42.16.11:9042 added
11/30/2017 4:42:57 PM[2017-11-30 21:42:57,944][INFO ][hmda-akka.actor.default-dispatcher-21] Subscribed to SubmissionSigned
```

Is there a timeout that I could increase to settle the issue?

**Comment by charandas** [comment]
Seems to be something related to zookeeper. Do you suggest one use exactly one Zk instance in an environment that runs more than one instance of the API?

I run into the above error even when running just one instance and restarting the API it would often go away.

I most certainly experience this error when scaling the API and using only 1 Zk instance. I was able to get beyond that by dedicating 1 Zk instance each to each API instance.

Any thoughts or advice would be welcome.

**Comment by charandas** [comment]
I was able to resolve this issue in my environment by adding the below config in `cluster/main/resources/application.conf`:

```
constructr {
  coordination.nodes = [${hmda.zookeeperHost}":"${hmda.zookeeperPort}]
  nr-of-retries = 10
  ttl-factor = 3.1
}
```

And I figured there should only be 1 zk instance or cluster, as otherwise the API will fall out of state between instances of itself as regards to submission state and other similar things.

**Comment by charandas** [comment]
Excuse my ignorance but I don’t think I know what’s happening to assert I have found a solution.

The issue is sporadic and so a rare success clouds my experiment and me into thinking that I had a workaround.

So at times I see a 2s timeout message in logs, and at times I see a connection refused. In either case, the API shuts down.

I have started studying Akka HTTP cluster management docs but it’s not immediately clear to me if I need to do manual leave/delete for cluster memebers when I am restarting the API container or scaling it up.

Could someone from the CFPB’s tech team please shed light on what causes above errors?

Is it my the perf of my zookeeper instance? Is my expectation that I can scale up the API container at will, correct?

**Comment by jmarin** [comment]
Hi @charandas,

There are too many things that could be going wrong here. Unfortunately we are not in a position to support third party deployments of the platform at this stage, but I will try to help. 

The first thing I would say is that our `docker` configuration is clearly a development setup, and doesn't reflect what we run in production. It is not meant to be optimized for performance or scalability. When you say that you are "scaling" the API, I'm assuming you are deploying several copies of the `api` cluster role. This violates the single writer principle that our architectural style for the platform imposes, and you may end up with conflicts in the database and / or race conditions. Under those circumstances, I would not be surprised if you started getting exceptions that made the whole thing unstable. A single instance of the `api` and `persistence` cluster roles should support a high enough volume of `LARs` for validation on commodity hardware.If you don't need storing the validated `LARs` and validation errors, we are going to open up the Single LAR validation public API soon, which is stateless and simpler to use, although it operates on a row by row basis. This will hopefully be deployed soon at https://ffiec.cfpb.gov/, keep an eye on this [ticket](https://github.com/cfpb/hmda-platform/issues/1363) and our [releases](https://github.com/cfpb/hmda-platform/releases) for details on release notes for future versions to see when it makes it in. 

As for the service discovery mechanism, we do use `Zookeeper`, for a production system you should deploy a cluster of at least 3 nodes. The `Akka Cluster` application uses [constructr](https://github.com/hseeberger/constructr) to maintain the cluster seed node configuration. On occasion, you will have to "clean up" this configuration by deleting the relevant nodes in `ZooKeeper` (constructr/hmda node by default). The symptom for this is an `Akka Cluster` node trying to connect to an old port. This might be happening to you based on your logs. It's also possible that there are network issues with your configuration, especially if you are running the platform as a cluster in a `docker` environment (i.e. `Kubernetes`, `docker swarm`, etc.). While theoretically possible, these alternative `docker` cluster runtime environments are not something we have spent time testing and the default configuration will most likely not work on them without some additional tweaking. 
Hope this helps

**Comment by charandas** [comment]
Thanks so much @jmartin.

It’s good to know of the single writer paradigm that your application builds upon. I would halt on my scaling efforts accordingly.

Thanks also for the zookeeper notes above. I am running in rancher cattle environment and would robustify the zookeeper part of the deployment.

I will keep an eye out for when the single LAR api becomes available.
