### ISSUE TITLE
Edit language for V290, V295 and V300 - WIP

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform#1366]
Some users are confused by the language associated with the location-related edits (V290, V295 and V300). These edits can be triggered by:

A) the individual values being invalid (i.e. state or county codes don't include the leading zeroes, census tracts don't include the decimal points) OR
B) the combination of values being invalid (based on the FFIEC geocoder)

The existing language describes B, so I think we should expand it to also address A.
@colleenms

**Comment by schbetsy** [comment]
@colleenms If you provide the error messages we should display, we can add them to the system.

**Comment by colleenms** [comment]
V290 - "If MSA/MD does not = NA, then MSA/MD, state, and county codes must equal a valid combination. Valid state code format must be NN. Valid county code format must be NNN."

V295 - "State and county must = a valid combination or (county = NA where MSA/MD = NA). Valid state code format must be NN. Valid county code format must be NNN or NA."

V300 - "Census tract must = a valid census tract number for the MSA/MD, state, county combination or {NA if county is classified as small) or (where MSA/MD = NA the census tract must = a valid census tract for the state/county combination or NA). Valid census tract format must be NNNN.NN or NA. Valid state code format must be NN. Valid county code format must be NNN or NA."
