### ISSUE TITLE
Document Single Lar Validation API

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#1367]
Document public Single Lar Validation API. Specific endpoints with inputs and outputs, as well as what validation edits are not being run as part of this public API. Depends on #1363

**Comment by charandas** [comment]
@jmarin I was looking at the tests for this API, followed them as an example and ran some single LAR requests against the API, which works great.

I am assuming this API is going to leave the responsibility of running file-level checks like below to the caller, is that assumption correct?

> Q130: Numer of records received does not = number of loan/app records reported in transmission sheet

**Comment by jmarin** [comment]
@charandas yes, this API leaves out a few edits that don't make sense for a single lar, i.e. some macro edits that look at the whole file for instance. It also doesn't perform validation on edits that require institution data.
