### ISSUE TITLE
Validation (2017): V463 (Co-Applicant Ethnicity)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#140]
**Edit #:** V463
**Type:** Validity
**Category:** Loan/Application Register (only)
**Column:** Co-Applicant Ethnicity

Co-Applicant ethnicity does not = 5; however, co-applicant race field 1 = 8 and/or co-applicant sex = 5.

Additional resources:
* [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
* [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
* [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by schbetsy** [comment]
A better explanation, from the edit requirements spreadsheet:

When Record Identifier = "2" AND Co-applicant Sex = "5" OR Co-applicant Race: 1 = "8", Co-Applicant Ethnicity must = "5"

**Comment by schbetsy** [comment]
Updated explanation: 

When Co-Applicant Sex = 5, then Co-Applicant Ethnicity must = 5 and Co-Applicant Race1 must = 8.
