### ISSUE TITLE
Large LAR files generating error message

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-platform#1410]
Users uploading large LAR files (>100k) are reporting receiving the below error message and needing to refresh the page multiple times during the submission process. They are able to complete a submission.

![image](https://user-images.githubusercontent.com/32906749/34018052-4e6436ba-e0f6-11e7-8515-efeb9c8e7e48.png)

**Comment by keileyo** [comment]
Can confirm that this happens w/ a 22k LAR test file. Test file that replicates this error is in drive.

**Comment by keileyo** [comment]
Some behavior that I've exhibited testing on HMDA3 today with large files (100k). 

Uploaded a 100k file with parsing errors in the transmittal sheet, after an hour of "uploading" i logged out and logged back in. At that point, i was prompted with the error message in the original comment above. I refreshed the page and it showed me the parsing errors. 

Logs show that the parsing with errors actually finished 10 minutes after the original upload, so it seems that leaving the platform and logging back in prompted the _refresh the page_ error & new status of _your file has formatting errors_ to be present in the UI. 

Uploaded another 100k file without parsing errors, and saw it move from uploading to validating the edits within 5 minutes. From there:
- The file stayed in _your data is being analyzed_ for over two hours
- After two hours, I logged back in and got only a spinning wheel
- Refreshed the page and received the "Sorry, and error has occured. Please refresh the page" message. Refreshed the page, and syntactical and validity edits were served in the UI.

**Comment by keileyo** [comment]
Testing prod during off hours:
- both the 100k file and 250k files produced parsing errors stating that the an unexpected number of data fields was found in a single LAR. In both cases, the files actually had the correct number of data fields in the LAR.  In the 100k file, this happened in row 98,945 and in the 250k file, this happened in row 198,897. 

- a second upload of the same 100k file made it past parsing. After 20 minutes of showing _uploading_ in the UI, I signed out and signed back in immediately and saw that the status moved forward to _your data is being analyzed_. After another ~1.5 hours, i logged out and logged back in and saw that my status moved to _validated with errors_.  
- Upon attempting to review the edits, I received just a spinning wheel in the UI, refreshed the page, received the error message in the first comment, refreshed again, and got stuck with a spinning wheel. The edits never appeared.

![image](https://user-images.githubusercontent.com/13036571/34880104-61186f0e-f77d-11e7-9462-257733f5dff7.png)

**Comment by keileyo** [comment]
Per conversation on Friday, entered a separate issue #1446 for the incorrect parsing errors noted in the comment above.

**Comment by schbetsy** [comment]
For large files, when the `/edits` endpoint returns a 500, this error is in the logs:
```
[2018-01-16 09:32:19,621][ERROR][hmda_master-akka.actor.default-dispatcher-25] 
  Ask timed out on [Actor[akka://hmda_master/user/supervisor/singleton/HmdaFileValidator-bfl-2017-3#370774026]] after [10000 ms]. 
  Sender[null] sent message of type "hmda.persistence.messages.CommonMessages$GetState$".
```
