### ISSUE TITLE
APOR table transfer from S3

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#1413]
Investigate why ingestion of APOR tables from S3 to platform failed - formatting or escape character in the .txt files? 

@jmarin putting this here to keep track of it.

**Comment by schbetsy** [comment]
The issue was that we didn't have the correct credentials set up for the S3 connection in PROD1. Since we're seeing that APOR data has imported correctly in both PROD1 and PROD2, I'll close this ticket.
