### ISSUE TITLE
Check Digit returning a 1 digit #

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-platform#1423]
In certain cases, the Check Digit Tool is dropping the leading zero when generating the check digit. See first screenshot below; the back-end message was as follows:

{"loanId":"5493001YS08XHF42M0372005203","checkDigit":7,"uli":"5493001YS08XHF42M03720052037"}

The second screenshot shows "07" was the actual check digit generated for that ULI.

![image](https://user-images.githubusercontent.com/32906749/34524308-185b0058-f069-11e7-82d3-b45fd5b8c755.png)

![image](https://user-images.githubusercontent.com/32906749/34524432-827d39e2-f069-11e7-89cf-af525013209d.png)

**Comment by wpears** [comment]
@schbetsy, you probably already noticed, but it's because the check digit is modeled as an Int: https://github.com/cfpb/hmda-platform/blob/d51b752cd017efbc3fbaf29076a34e109ddefe80/api-model/src/main/scala/hmda/api/model/public/ULIModel.scala#L6

It should be a String.
