### ISSUE TITLE
Check-digit endpoint: Return sensible error for invalid input

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#1427]
Currently, if the input loan ID contains any non-alphanumeric characters (such as `!#$%^`), it returns `500 Internal Server Error` and no helpful information.

Instead, use response code `400` and return a useful error message, e.g. "LEI + Loan/Application ID may only contain alphanumeric characters".

**Comment by awolfe76** [comment]
There are also limits on the min/max characters for the LEI and loan/application id:

- max of 43
- min of 20

Same applies to the validation of a ULI as well. ULI has:

- max of 45
- min of 23

It would be nice to have those error responses as well. The [check digit UI](https://cfpb.github.io/hmda-platform-tools/check-digit/) does account for this.

@keileyo - double check me, please.

**Comment by keileyo** [comment]
Above is mostly correct, the one exception being that the combination of LEI/Loan ID is a minimum of 21 characters and a maximum of 43 characters. 

Universal Loan ID (ULI) is comprised of:

- Legal Entity Identifier which is alphanumeric and always 20 characters in length
Source: [GLEIF](https://www.gleif.org/en/about-lei/iso-17442-the-lei-code-structure/)
- Loan/Application ID which is alphanumeric and between 1 - 23 characters
Source: [100.3.4(a)(1)(i)(B)](https://www.consumerfinance.gov/eregulations/1003-4/2015-26607_20180101#1003-4-a-1-i-A)
- Check digit which is numeric and always 2 characters
Source: [100.3.4(a)(1)(i)(C)](https://www.consumerfinance.gov/eregulations/1003-4/2015-26607_20180101#1003-4-a-1-i-B)

ULI minimum: 23 characters, ULI maximum: 45 characters 
LEI/Loan ID minimum: 21 characters, maximum: 43 characters
