### ISSUE TITLE
Automatically strip out leading and trailing spaces for panel updates

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-platform#1434]
Automatically strip out leading and trailing spaces so that we don't have any issues with future panel updates for production

@schbetsy

**Comment by schbetsy** [comment]
There was a situation today where a panel update contained a trailing space, like so:
```
"emailDomains":["example.com "]
```

When that was in place, this institution couldn't be found in domain search under `example.com`, since the trailing space isn't searchable.

**Comment by awolfe76** [comment]
We've also seen that this has an impact on the institution id. It would make sense to apply this to all fields as well.

**Comment by jmarin** [comment]
Does this belong here? Or should that be done at origin, where the data is produced? I'm not a big fan of having the platform modifying data that is produced elsewhere

**Comment by awolfe76** [comment]
I've asked @Kibrael to do it there as well, which I think is done already.
I thought it would be a good idea to have it here too, as a second catch, but wouldn't have to be.

**Comment by schbetsy** [comment]
Good point. Maybe modifying data we receive isn't good practice. However, I'm not a fan of inserting data that will cause a fiery crash (like we had today, with the trailing space in the institution ID). 

We could check for bad data, and reject it with an error code and a message.
