### ISSUE TITLE
Incorrect parsing errors on large files

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#1446]
Splitting off from #1410 

Per our conversation on Friday, creating a new issue for the incorrect parsing errors. Twice, the platform returned parsing errors on files that did not actually have parsing errors. 

- File w/ 100 k LARs, produced an "unexpected number of data fields found" error in row 98,945 
- File w/ 250k LARs, produced an "unexpected number of data fields found" error in row 198,897

I believe this is low priority because subsequent tests with the same files have not replicated the parsing errors, and the submissions successfully moved from uploading the data to validating the edits.

**Comment by schbetsy** [comment]
(As you pointed out) I accidentally duplicated this issue in #1479. Closing this in favor of that once, since it has more information now.
