### ISSUE TITLE
Update edit language for S025

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-platform#1449]
A large number of users are generating the S025 edit and contacting HMDA Help for guidance. If we add the following to the edit language, I think users will be more clear on what needs to be changed:

"Please note the respondent-id should not include any leading zeros or a dash"

I believe the current language in platform is as follows: 
"Control number must = a valid respondent identifier/agency code combination for date processed.,The respondent-id and agency code provided in the file does not match our records. Please verify the reported respondent-id and agency code and update your file accordingly."

@keileyo any other thoughts on this?

**Comment by nickgrippin** [comment]
Reopening.  Requested change needs to be made in the "Edit Description" column, not the "User Friendly Language".
