### ISSUE TITLE
Files getting stuck in validating

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-platform#1452]
Files get stuck in validating when income is formatted incorrectly. Enhance parser to catch this. 

After further review, we determined the issue is being caused by the income field, which had values containing decimal places, e.g. 163.956. The income field needs to be rounded to the nearest thousand, without commas, or reported as NA.

~~We replicated an issue that results in a file getting stuck in validation. What we know:~~
~~- Certain required transmittal sheet fields are left blank~~
~~- Even when the blank transmittal sheet fields are populated, the issue still gets stuck in validation~~

**Comment by keileyo** [comment]
After discussing with @jmarin, the idea is to include a check in the parser for this and other alphanumeric fields that can only be a whole number or NA.

**Comment by jmarin** [comment]
@keileyo Can you provide here the list of fields that this condition is true for? 
Thanks

**Comment by keileyo** [comment]
Fields that must be either an integer or NA (like income);

- Date Application Received
- MSA/MD
- State
- County
- Income
