### ISSUE TITLE
Mod APOR tables in platform

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#1454]
In order to restore proper functionality for the rate set dates 12/25/17 - 12/31/17, modify the APOR table stored in platform so that the effective dates and values match the published tables. 

https://s3.amazonaws.com/cfpb-hmda-public/prod/apor/YieldTableFixed.txt
https://s3.amazonaws.com/cfpb-hmda-public/prod/apor/YieldTableAdjustable.txt

**Comment by keileyo** [comment]
Clarification:

A new PR will be needed because the action that needs to be applied is **deleting** a row of data. I believe that the the way the error was applied and then fixed in the tables actually led to the presence of an additional row of data. 

The tables in platform currently store a row of data beginning with the effective date 12/28/17. That entire row should be removed. The result should match the tables linked in the comment above. There should be a row of data with effective date 12/25/17 and the following row of data should have an effective date of 1/1/18.

**Comment by schbetsy** [comment]
When I was testing/code reviewing the current modify-apor functionality, I thought I confirmed that we don't actually need to be able to delete data. I thought we could simply modify the 12/28 data to have the correct values, or re-add a line of data on 12/25 with the correct values, and we'd get the correct rate spread responses from the API. 

I may have gotten mixed up in my testing, so I'm not 100% sure, but I wanted to check. Did you test a solution in dev to make sure the current functionality won't work?

**Comment by keileyo** [comment]
Sorry for a late response, I'll break down the issue:

1. 12/25 row values are correct and should not be touched or replaced. 
2. A row was added with the effective date of 12/28/17 with APOR values that should have been effective 1/1/18. 
3. A fixed file was uploaded on 1/2 with an effective date of 1/1/18 and all of the same APOR values as the 12/28 row. 

This leaves the platform with something like this: 
12/25/17 - 1, 1, 1, 1, 1..
12/28/17 - 2, 2, 2, 2, 2 ....
1/1/18 -  2, 2, 2, 2, 2....

Changing the date on the 12/28/17 line would leave us with 2 lines with a 1/1/18 effective date which does not work in the platform.

**Comment by schbetsy** [comment]
That's exactly the scenario that I tested for when I was reviewing #1437. I believe the extra row of data does not matter, and we can make the rate spread calculator return correct values for those dates without deleting the row.

**Comment by schbetsy** [comment]
I updated the values in Production. @keileyo could you test it out to double check that the values look right now?

**Comment by keileyo** [comment]
Tested it using batch in production & this works!  Will have @wpears take down the error message on the UI. Hooray
