### ISSUE TITLE
2016 HMDA Files

### ISSUE THREAD

**Issue by charandas** [cfpb/hmda-platform#1458]
I am trying to evaluate the capability of running macro edits such as Q075 and Q076, and see the need for previous year data obviously. 

The data load script [here](https://github.com/cfpb/hmda-platform/blob/master/Documents/2016_Data_load.md) is great, but wondering if 2016 data is available in pipe-delimited format somewhere on the web?

EDIT: I am aware of the HMDA LAR Flat files made available [here](https://www.ffiec.gov/hmda/hmdaflat.htm), are they a starting point for your team as well, when hydrating the database?

**Comment by jmarin** [comment]
Hi @charandas
Yes, that is the source of our information, we have taken the public data available and loaded it into the platform to represent last year's information for the purposes of edit checks. One thing to note is that there are some differences in the data model between the input data that the platform will expect described in the [Filing Instruction Guide](https://www.consumerfinance.gov/data-research/hmda/static/for-filers/2017/2017-HMDA-FIG.pdf) and the public LAR files (described [here](https://www.ffiec.gov/hmdarawdata/FORMATS/2016HMDALARRecordFormat.pdf) as you have probably already seen). I don't know if we can share the code that performed this transformation, as it wasn't part of this code repository but I will dig into it and see what I can find.

**Comment by charandas** [comment]
@jmarin on a related note, I am looking into accessing 2017 modified LAR data programmatically. Wondering if there is a public API for that?

I see conflicting information:
1. On one hand, I see this [page](https://ffiec.cfpb.gov/data-publication/modified-lar)
2. On the other, I see this [recent commit](https://github.com/cfpb/hmda-platform/commit/7f3e14b166d6efb260d42bdb82f9d47350159917) which disabled the API of the same name.

Could you help me understand if this option would be made available on the public api again?
