### ISSUE TITLE
Q666: Identify loans with id composed of all characters

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#1464]
Check that Loan id is not exclusively composed of characters

**Comment by schbetsy** [comment]
I believe the edit needs to catch more scenarios than what's described here. For instance, it should also warn if there is a loan ID in formats like any of these:
- `first last` (with a space)
- `name-denied` (with a hyphen)
- `name(location)` (with parens)

Proposal: fail the edit if the loanID doesn't contain any digits.

**Comment by jmarin** [comment]
The reason the PR associated with this ticket is stalled is because the requirements for this are still being flushed out. These requirements will be quite strict and not coming from our team. Thanks

**Comment by schbetsy** [comment]
Ah, thanks for the clarification. Sounds good.

**Comment by ericspry** [comment]
Correct. We will only implement a narrow set of conditions for this feature to be triggered based on Bureau guidance:

1. Application or Loan Number is all alpha characters  
2. Application or Loan Number contains a numeric pattern matching ###-##-####

This warning will assist users in the following recommendation pursuant to [1003.4(a)(1) comment 4](https://www.consumerfinance.gov/eregulations/1003-4/2015-26607_20170101#1003-4-a-2) which states in regards to Application or Loan Number:  
>Institutions are strongly encouraged not to use the applicant's or borrower's name or social security number, for privacy reasons. 

Design work for the warning is in this [hmda-platform-ui Issue #1009](https://github.com/cfpb/hmda-platform-ui/issues/1009)

**Comment by keileyo** [comment]
Clarifying requirement 1:

In order to be over inclusive (false positives are ok), requirement 1 is revised: Instead of "all alpha characters" search for Loan IDs that **do not have any numerical characters.**

**Comment by keileyo** [comment]
Cleared language that should be returned when the edit is flagged:

"The Loan/Application Number data field contains all alphabetical characters following the pattern of a name or numbers and dashes following the pattern of a Social Security number.  Institutions are strongly encouraged not to use the applicant’s or borrower’s name or Social Security number in the Loan/Application Number field, for privacy reasons.  Please review the data in this field and consider updating your file, if appropriate."
