### ISSUE TITLE
Question on Replacing Existing LAR

### ISSUE THREAD

**Issue by timkvfpmq** [cfpb/hmda-platform#1471]
I'm a developer for a compliance product that assists banks with HMDA submissions.  We have a client that incorrectly created a submission with leading zeros in the respondent ID and received S025 edits.

They corrected their submission file, logged back into the platform and chose to upload a new file.  Their new file had a different name than the previous one and they confirmed there were no longer leading zeros on the respondent ID.

When they uploaded their new file, it showed the **_new_** file name during upload but when they got the message that their upload was complete, it showed the **_old_** file name and retained the same S025 errors as the initial file.

We've tried logging out of the HMDA Platform and back in with the same results.  Is it possible their instance of IE could be caching something causing a problem?

**Comment by timkvfpmq** [comment]
Follow-up on this.  This morning the client had their IT clear the cache on their browser and restart the PC.  They attempted the upload again and this time the new file uploaded successfully and replaced the previous file.

**Comment by jmarin** [comment]
Thanks @timkvfpmq. If it's OK with you, I'm going to close this ticket. For any further questions or issues with the production system please feel free to contact HMDA Help.
