### ISSUE TITLE
Large uploads sometimes silently time out

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#1479]
For large files, I sometimes see two different issues when uploading. These are especially prevalent when there's a lot of traffic on the system. (I've mostly seen these on HMDA3 stacks. They might be less prevalent on Prod, since it has more resources, but I believe they can still happen)

1. The submission just stays in `uploading` status (seemingly) forever.

or

2. The submission proceeds from `uploading` to `parsing` status, but when parsing is finished, it shows that the upload got cut off. It shows a parser error (not enough fields on line X) where the upload stopped.

**Comment by keileyo** [comment]
#2 above I believe is the same behavior I saw in #1446

**Comment by schbetsy** [comment]
More info:

Sometimes the upload endpoint returns a `502 - Bad Gateway`, and the page looks like the screenshot below. In that case, the result is scenario 2 above.

After the `502`, it shows this error: 
<img width="1064" alt="screen shot 2018-02-02 at 12 32 54 pm" src="https://user-images.githubusercontent.com/4295388/35746597-5011df58-0815-11e8-9eb9-740abfb7b66b.png">

... but it continues polling. Once it receives the `parsed with errors` result, the page updates to show this below the upload box:
<img width="1034" alt="screen shot 2018-02-02 at 12 34 24 pm" src="https://user-images.githubusercontent.com/4295388/35746639-71795f54-0815-11e8-936d-7fb2e9b1bdef.png">

**Comment by schbetsy** [comment]
Another test I did: 
1. Start a large file upload (100k lars)
2. Leave the page before the upload is finished
In that trial, it did not encounter any parsing errors, but the file summary only shows that 5488 lars were submitted.

**Comment by schbetsy** [comment]
This happened for a very large filing in Production. From Andrew:

```
HTTP/1.1 500 Internal Server Error
Content-Encoding: gzip
Content-Type: application/json
Date: Fri, 09 Feb 2018 17:11:03 GMT
Server: akka-http/10.0.11
Transfer-Encoding: chunked

{
    "httpStatus": 500,
    "message": "Internal server error",
    "path": "/institutions/<id>/filings/2017/submissions/<seqNr>/edits"
}
```
