### ISSUE TITLE
Summary endpoint 404ing

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-platform#1482]
As of around 2:00 today, the summary endpoint 404ed 151 of 211 times it was called.  If you limit that to distinct submissions, it's at about 50/50 with 42 of the 82 distinct submissions having this issue.  It seems like for a given submission, if you fail the first time, it'll always fail. Here is a screenshot; there is a separate ticket in the UI repo:

![image](https://user-images.githubusercontent.com/32906749/35757509-67e88e7e-083d-11e8-96d1-3b17fc15dd9d.png)

**Comment by awolfe76** [comment]
Closing, including in #1477
