### ISSUE TITLE
Feature Request: Add parse/validate endpoints for a single Transmittal record

### ISSUE THREAD

**Issue by tmeneau** [cfpb/hmda-platform#1493]
# Proposal

The current public API [supports parse/validate](https://github.com/cfpb/hmda-platform/blob/master/api/src/main/scala/hmda/api/http/public/SingleLarValidationHttpApi.scala) endpoints for single LAR records, and it looks like the platform has internal logic for [validating Transmittal records](https://github.com/cfpb/hmda-platform/tree/master/validation/src/main/scala/hmda/validation/rules/ts). Exposing that validation logic over the public API identically to the LAR validation endpoints could be similarly helpful to technology vendors in helping institutions ensure the validity of transmittal data prior to submission.

**Comment by jmarin** [comment]
Closed by #1500
