### ISSUE TITLE
Signature box greyed out; users unable to submit

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-platform#1504]
Several users have reported seeing the following in the platform:

![image](https://user-images.githubusercontent.com/32906749/36387359-c0ee4a14-1566-11e8-98f1-4dd848e7c57e.png)

Per research from @kgudel , one of the institutions reached validation completed, no errors. I'll provide a list of the institutions via MM.

**Comment by keileyo** [comment]
Users started reporting this issue on Friday, 2/16.

**Comment by nickgrippin** [comment]
Suggested course of action is to go back to the edits page and uncheck and recheck the "verify edits" checkbox.  This should (hopefully) refresh the submission status.

**Comment by nickgrippin** [comment]
It looks like all institutions were able to sign.  Closing the issue.
