### ISSUE TITLE
List of filers - public endpoint

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#1507]
We'll need a public endpoint that returns a list of the filers for a given period.

I think the endpoint should do 2 things:

1. return the full list of filers and
1. allow for a search parameter, eg `?search=<someString>`.

__Would like to hear suggestions for the endpoint URL.__

My only thoughts are a new `/filers` or something off of the existing `/institutions`.

Suggested JSON response:

```json
{
  "institutions": [
    {
      "id": "12345",
      "name": "First Bank",
    },
    {
      "id": "123456",
      "name": "Second Bank",
    }
  ]
}
```

_I don't think any more data is required for now._

**Comment by awolfe76** [comment]
We'll also need to include the filing period as a parameter here.

**Comment by awolfe76** [comment]
It would be good to include as many `id` values as possible in the response.

Looking at the [`/institutions?domain=` endpoint](http://cfpb.github.io/hmda-platform/institutions/#search-by-domain) I think a similar approach would work well.

I don't think we need to go digging through multiple sources to just to get ids, using what we have available in panel and the modified LAR filename should be fine.

At a minimum, we should include the `respondent id`. So if we need to, we can add later, as long as this is included.

@keileyo @colleenms - does this sound right?

**Comment by keileyo** [comment]
yep, sounds right. The ID values that are most helpful to return are Respondent ID, RSSD ID and Tax ID. We will show respondent ID w/ the name in the UI of the mLAR search.
