### ISSUE TITLE
Panel file for bulletin & regulator data transfer 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#1524]
Create a one time panel file that includes:

1. All institution records with the HMDA Filer Flag = True (this is what we are currently producing daily)
2. In addition to number 1, add all institution records for actual HMDA filers. This will be a combination of filer institution records that existed prior to the filing period & had the HMDA filer flag set to false and institution records that were added via the inserts process during the filing period. 

Uses:
- Regulator data transfer (one time full panel file)
- HMDA bulletin team 

Will need this file produced during 1.25 (edit: now continued 1.24) sprint, and will be produced in the same format as the current daily panel file output.  Suggest that we use the base 2/5 panel file + records of all other institutions who have filed by 2/5.

**Comment by Kibrael** [comment]
If it is possible to have this file produced early next week that would be ideal. 

The Bulletin team is working on a tight deadline.
