### ISSUE TITLE
Validation (2017): V326 (Co-Applicant Sex)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#154]
**Edit #:** V326
**Type:** Validity
**Category:** Loan/Application Register (only)
**Column:** Co-Applicant Sex

Co-Applicant sex does not = 5; however, co-applicant ethnicity = 5 and/or co-applicant race field 1 = 8.

Additional resources:
* [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
* [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
* [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by schbetsy** [comment]
A better explanation, from the edit requirements spreadsheet:

When Record Identifier = "2" AND Co-applicant Ethnicity = "5" OR Co-applicant Race: 1 = "8", Co-applicant Sex must = "5"

**Comment by schbetsy** [comment]
Closely related to #141 and #140

**Comment by schbetsy** [comment]
Would it be safe to rephrase this edit like this? (just for coding purposes, not to change the edit requirements document):

"When Co-Applicant Sex = 5, then Co-Applicant Ethnicity must = 5 and Co-Applicant Race 1 must = 8"

I think it would make the logic easier to understand and code. If that works, I would make a similar change in #141 and #140.

**Comment by lesgou** [comment]
Yes, that make sense.
