### ISSUE TITLE
Inconsistent CSV header formatting in API responses

### ISSUE THREAD

**Issue by ryanulit** [cfpb/hmda-platform#1566]
The private endpoints use header rows with spaces after the commas, while the public endpoints use header rows without spaces.  I only noticed due to a 3rd party CSV parser not being able to handle the difference, so it might not be a huge deal to others, but could be nice to have some consistency.

For example:

[https://github.com/cfpb/hmda-platform/blob/master/Documents/API.md#edits-csv](https://github.com/cfpb/hmda-platform/blob/master/Documents/API.md#edits-csv) 

This returns a response with a header row of `editType, editId, loanId`

[https://github.com/cfpb/hmda-platform/blob/master/Documents/public-api.md#check-digit](https://github.com/cfpb/hmda-platform/blob/master/Documents/public-api.md#check-digit)

The batch version of this returns a response with a header row of `loanId,checkDigit,uli`

**Comment by awolfe76** [comment]
Thanks, @ryanulit. And sorry for the delay here.

When we do our next release `v2` for the edits CSV will no longer have spaces in the header row.
