### ISSUE TITLE
Invalid MSA codes in 2017 data

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#1577]
During the filing period, the platform accepted ~3,400 invalid MSA codes from 90 filers. The invalid MSA values, which are actually Micropolitan Statistical Area codes, should have been reported as NA and caught by validity edit V280.

1. Confirm which source used to check V280.
2. Work w/ internal stakeholders to determine message or remedy.

**Comment by keileyo** [comment]
@kgudel will check the source for the file used for the geography edits.

**Comment by kgudel** [comment]
The file that we use for determining [here](https://www.census.gov/geographies/reference-files/time-series/demo/metro-micro/delineation-files.html). The specific file that is used is called [Jul. 2015](https://www2.census.gov/programs-surveys/metro-micro/geographies/reference-files/2015/delineation-files/list1.xls) under the heading `Core based statistical areas (CBSAs), metropolitan divisions, and combined statistical areas (CSAs)`.
