### ISSUE TITLE
Report 1 missing data

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#1584]
It looks like some data was left off of the report 1 JSON files.

You can use the [FFIEC aggregate tool](https://www.ffiec.gov/HmdaAdWebReport/AggWelcome.aspx) to see the PDF; pick a `state -> MSA/MD -> Report 1` to see the PDF.

[Here is a JSON example](https://s3.amazonaws.com/cfpb-hmda-public/prod/reports/disclosure/2017/215662/12420/1.txt).

You'll see 2 columns at the end of the PDF version, "% Min Pop" and "Median Income As PCT of MSA/MD Median" (used on the track name rows). This data doesn't look like it's in the JSON version.

**Comment by nickgrippin** [comment]
The Aggregate Report Table 1 should have the correct values.  [See here](https://github.com/cfpb/hmda-platform/blob/master/publication/src/main/scala/hmda/publication/reports/aggregate/A1.scala#L117-L124)

This is just an issue with the Disclosure Report.

**Comment by awolfe76** [comment]
Yep, thanks @nickgrippin!

Closing this since it's just a slight difference between aggregate and disclosure report formats.
