### ISSUE TITLE
Report 11-* data issues

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform#1585]
In the 11-* series of tables, I've uncovered the following issues:
 - No HOEPA information is included
 - The "value" of Means/Medians is always "None", even when data exist
 - The "count" of Means/Medians is the empty string "" if all entries in that row were 0.

 Note, for the first two issues this [follows the spec](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/decatur/11-3/11-3.json). However, it looks like the spec deviates from [last year's report](https://www.ffiec.gov/hmdaadwebreport/pdf/2016/Hmda/temp/2016HD11-3_0000858528228700.pdf).

**Comment by wpears** [comment]
Yeah and there's been an [open PR for 5mo](https://github.com/cfpb/hmda-viz-prototype/pull/193) updating it 😅

**Comment by colleenms** [comment]
To add to the above, for the first table in the 11-* reports (Pg. 1 of the 2016 example), the mean and median values should be calculated based on the count of loans above the 1.50% threshold, (i.e. total percentage points above average prime offer rate/# of loans with a rate above the average prime offer rate). For the second table (Pg. 2 of the 2016 example), the mean and median values should be calculated based on the dollar value of the loans, as outlined in Notes 30, 31 [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

**Comment by nickgrippin** [comment]
Are we OK to close the and #1589?
