### ISSUE TITLE
New aggregate endpoint

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#1587]
The aggregate front-end flow requires a user to `select a state -> select a MSA/MD -> select a report`.

We need a new endpoint that lists the available MSA/MDs per state.

#### Possible URL

Suggestions?

#### Proposed response

```json
{
  "year": "2017",
  "state": {
    "name": "Alabama",
    "id": "AL"
  },
  "msaMds": [
    {
      "id": "1234",
      "name": "Friendly MSA Name 1"
    },
    {
      "id": "2345",
      "name": "Friendly MSA Name 2"
    }
  ]
}
```

**Comment by nickgrippin** [comment]
Which API should this be available on?  Admin or public?

I would suggest something like `/aggregate/msas/AL`

**Comment by awolfe76** [comment]
Definitely public, we need it for the A&D reports.

That path looks ok, but I'm not sure we need the `aggregate` part. It _could_ be used in other cases too. We'll also need the period too.

You can check out #1570 to see the other endpoint, for disclosure. Maybe that will help with the path. (I think that one would be good to have first since we've been focusing mostly on disclosure for the UI for now.)

@jmarin @wpears

**Comment by nickgrippin** [comment]
Do we need the year?  It could be something as simple as `/msas/AL`.  We don't keep separate year-labelled versions of MSA data on the platform.  If we do need to plan for that in the future, I'm fine with including the year, like `/msas/2017/AL`

**Comment by awolfe76** [comment]
Well, it depends.

If this endpoint only returns MSAs that we _know_ have a report, then yes, we should include the year.

If it's going to return all MSAs, all the time, we probably don't. But even then I think we'd need some time frame associated with it, assuming MSAs change over time.

**Comment by nickgrippin** [comment]
With aggregate reports, every report is generated for every MSA.  This endpoint would just be returning a subset of information from [this file](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/resources/msa17inc.csv).  Probably cross-referenced with [this one](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/resources/state.csv) if we need friendly state names.

**Comment by wpears** [comment]
Yeah we can hardcode this mapping in the front-end. Opened https://github.com/cfpb/hmda-pub-ui/issues/64
