### ISSUE TITLE
Report 12-2 data issues

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform#1589]
Along with #1585, it looks like Table 12-2 has similar data issues:
 - Empty string for Mean/Median counts
 - "None" for Mean/Median values
 - Missing a column of data from the [2016 tables](https://www.ffiec.gov/hmdaadwebreport/pdf/2016/Hmda/temp/2016HA12-2____________12540.pdf). Namely, rather than including columns "5.00 - 5.99" and "6 or More", the data just contains a "5 or More" column. Again, this matches the [prototype](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/decatur/12-2/12-2.json) but I'm wondering whether there was an error in generating the prototype itself .

**Comment by colleenms** [comment]
To add to the above, for the first table in the 12-2 report (Pg. 1 of the 2016 example), the mean and median values should be calculated based on the count of loans above the 1.50% threshold, (i.e. total percentage points above average prime offer rate/# of loans with a rate above the average prime offer rate). For the second table (Pg. 2 of the 2016 example), the mean and median values should be calculated based on the dollar value of the loans, as outlined in Notes 30, 31 [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

**Comment by colleenms** [comment]
Per discussion, we will not add the "6 or More" data column to 12-2.
