### ISSUE TITLE
Difference in institution object keys between /filers and /msaMds

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform#1609]
The institution objects returned by the `/filers` endpoint has the keys `respondentId`, `name`, `period` and `institutionId` while the keys on the institutions object returned from the `/msaMds` endpoint are `respondentId`, `name`, `id`.

I'd suggest modifying the `/msaMds` endpoint match the `/filers` representation or (if you don't want to add `period` at this time) at least updating the `id` key to `institutionId` for consistency.

**Comment by nickgrippin** [comment]
Closed in #1620
