### ISSUE TITLE
New Report A4W: Nationwide Disclosure Report by Respondent ID

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-platform#1612]
Table A4W: "DISPOSITION OF PREAPPROVALS FOR CONVENTIONAL HOME-PURCHASE LOANS, FIRST LIEN, 1- TO 4-FAMILY DWELLINGS (EXCLUDES MANUFACTURED HOMES), BY BORROWER OR CENSUS TRACT CHARACTERISTICS"

Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

respondent_id
institution_name
table: "A4W"
type*: "Disclosure"
desc: "Disposition of preapprovals for conventional home-purchase loans, first lien, 1- to 4-family dwellings (excludes manufactured homes), by borrower or census tract characteristics"
year
report-date
applicantincomes

*note: this is a nationwide disclosure report

JSON: none, see A4 example [here](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/decatur/A-4/A-4.json) (difference is A4W is nationwide)
Prototype: None created, see attached FFIEC Report

[2016HDA4W__0000112837900000.pdf](https://github.com/cfpb/hmda-platform/files/1985369/2016HDA4W__0000112837900000.pdf)

Overall table filters
Loan Type: 1
Property Type: 1
Purpose of Loan: 1
Lien Status: 1

Borrower or Census Tract Characteristics
Borrower Characteristics
•	Race
•	Ethnicity
•	Minority Status
•	Income
•	Gender

Census Tract Characteristics
•	Racial/Ethnic Composition
•	Income

Dispositions
This table includes the following dispositions:
•	Preapprovals Resulting In Originations: Preapproval = 1 and Action Taken = 1
•	Preapprovals Approved but Not Accepted: Action Taken = 8
•	Preapprovals Denied: Action Taken = 7

Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

**Comment by nickgrippin** [comment]
Done on [this branch](https://github.com/nickgrippin/hmda-platform/blob/report-s3-source-national/publication/src/main/scala/hmda/publication/reports/disclosure/DisclosureA4W.scala)
