### ISSUE TITLE
Implement Institutions Data Model 

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#1615]
Version 2, including [LEI](https://www.gleif.org/en/about-lei/introducing-the-legal-entity-identifier-lei)

**Comment by keileyo** [comment]
Upon further research, i do not think we should roll up the 18 defined codes & null code into the 6 text based institution type codes that we used last year. 2018 data model should just contain 1-18 or the decided null value (@jmarin, last year this was -1, but i'll leave that up to you on whether we need a value or whether it can be blank).

**Comment by jmarin** [comment]
@keileyo thanks this helps. Do the 1-18 integer values have a description associated with it? i.e. "Savings and Loan", "Mortgage Banking Subsidiary", etc.? I would like to model this similar to what we had in the previous version. Thanks

**Comment by keileyo** [comment]
@jmarin, i just thought of this in regard to the institutions data model. We aren't determining the HMDA filer flag ahead of time, but rather producing a "filers" file which is populated w/ the institutions data for all FIs that have filed HMDA data.  When we brainstormed this, the idea was that the "filer flag" would be switched to "on" once a filing is signed for the FI, and the "filers" file is created of all FIs with the flag flipped to "on."

Do we need to add a blank field for filer flag in the institutions data model to accommodate that?

**Comment by keileyo** [comment]
and my second comment in response to the question about the names for the Institution Type Codes - we want our "filers" file to contain the integers for the type codes, not the text. let me know if you want to chat about these tomorrow.

**Comment by jmarin** [comment]
Forgot about the `HMDA` filer flag. Will add this. 
For the second question, yes, the codes are what we put in files, it's the official value for that field. It's good to know what they mean so that we can use the description in code when filtering, aggregating, etc.
