### ISSUE TITLE
Aggregate Table i is not returning the full list of institutions

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-platform#1622]
As an example, MSA/MD 35614 has a list of 29 institutions in [table i](https://ffiec.cfpb.gov/data-publication/aggregate-reports/2017/NJ/35614/i), but the LAR data indicates there are 774 unique institutions with loans in this MSA. the file generated by the back-end has only the 29 institutions

**Comment by nickgrippin** [comment]
Closing
