### ISSUE TITLE
Check Digit: Large files generate invalid results

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-platform#1667]
For the check digit batch upload, large files (greater than ~6k records or 150 kb) fail to generate expected results. A user reported that the tool generated a file with truncated and blank ULI records.

**Comment by nickgrippin** [comment]
Generated a large test file of ~7400 LEIs.  The endpoint failed once, but worked every other time.  My recommendation would be for the user to retry the same file, and check for correct data and formatting.

**Comment by Jc692488** [comment]
Fix error

**Comment by jmarin** [comment]
@nickgrippin OK to close?

**Comment by jmarin** [comment]
@nickgrippin What is left to do here?
