### ISSUE TITLE
Update dynamic LAR and TS file settings in S3

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#1681]
So we always allow the dynamic files

- https://s3.amazonaws.com/cfpb-hmda-public/prod/dynamic-data/2017_lar.txt
- https://s3.amazonaws.com/cfpb-hmda-public/prod/dynamic-data/2017_ts.txt

to be downloaded we need to update the settings during (or after) the files have been written.

We are able to do this manually, after the files are written, by setting the `Content-Disposition`.

#### For reference
- https://stackoverflow.com/questions/2613792/change-content-disposition-of-existing-s3-object
- https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ObjectMetadata.html#setContentDisposition-java.lang.String-

**Comment by nickgrippin** [comment]
Closed in https://github.com/cfpb/hmda-platform/pull/1683
