### ISSUE TITLE
Debug LAR filtering issue

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#1682]
As of 7/22, the filters applied to the daily LAR file are no longer working, and the records previously filtered are being written to the nightly regulator file. 

Known:
- the filters worked as expected for 7/19 and 7/20
- the filters work as expected for the dynamic dataset but not the nightly regulator file.

**Comment by keileyo** [comment]
Update:

1) we will provide manually generated LAR file to data team as short term solution.

2) as a backup @nickgrippin will backup the current dynamic data files so that we can use them if filtering issues persist.

**Comment by nickgrippin** [comment]
Is this ticket OK to be closed? @keileyo

**Comment by nickgrippin** [comment]
Closing, the issue has been resolved.  Other running instances of the platform were overwriting the produced files with outdated filters.
