### ISSUE TITLE
A4 report has A4W as the table in the JSON files

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#1684]
When viewing an `A4` report everything is correct except that the `table` property in the JSON has `A4W` as its value. This is rendered in the UI, so the UI appears incorrect.

### Screenshot

![a4-as-a4w](https://user-images.githubusercontent.com/2932572/43279766-f3dd465e-90dc-11e8-9315-18d19d10d354.png)

**Comment by nickgrippin** [comment]
We discussed in standup on 8/7 to have these renamed using a script, rather than regenerating the reports.  The script would need to download each report from S3, modify the `table` field, and upload it, overwriting the existing report.
