### ISSUE TITLE
Validation (2017): Q033 (Parent Mailing Address)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#178]
**Edit #:** Q033
**Type:** Quality
**Category:** Transmittal Sheet (only)
**Column:** Parent Mailing Address

If respondent is a bank, savings association, or independent mortgage company, and if any parent company exists, then parent name, address, city, state and zip code should not = blank.

Additional resources:
* [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
* [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
* [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by schbetsy** [comment]
Not sure how we'll know what kind of institution the respondent is (bank, savings association, mortgage co, etc). Will that information come from Panel? I didn't see it in the transmittal sheet.

**Comment by jmarin** [comment]
This will come from panel, yes.

**Comment by nickgrippin** [comment]
Adding a blocked label, as this requires panel
