### ISSUE TITLE
Add 2017 results to institution search

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#1793]
_Based on https://github.com/cfpb/hmda-platform/issues/1792._

From this paragraph:

> In this case both the 2017 and 2018 datasets should be searched, with 2017 only being used if there is no result found in 2018. The 2018 dataset is "preferred". And the response should be a list of institutions, using the existing response format, that matches the search parameter(s).

This issue is to add the 2017 dataset to possibly be included in the search response.

**Comment by Jc692488** [comment]
And how do I add the 2017

**Comment by awolfe76** [comment]
@Jc692488 - at the moment you have to use the 2 different public endpoints; [2017](https://github.com/cfpb/hmda-platform/blob/b3d6d4766d4c8dd906460ccf0cfed3d3399942f8/docs/v1/public-api.md#institutions) and [2018](https://github.com/cfpb/hmda-platform/blob/b3d6d4766d4c8dd906460ccf0cfed3d3399942f8/docs/v2/api/public-api.md#institutions).
