### ISSUE TITLE
Validation (2017): Q012 (Tax Identification (ID) Number)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#180]
**Edit #:** Q012
**Type:** Quality
**Category:** Transmittal Sheet (only)
**Column:** Tax Identification (ID) Number

The reported Tax ID number on the transmittal sheet of your HMDA data file does not match the Tax ID number reported in the previous calendar year submission.

Additional resources:
- [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
- [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
- [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by schbetsy** [comment]
How will we get this information for the 2017 filing year? Is Tax ID included in Panel info, or do we need to get it from the 2016 filings somehow?

**Comment by jmarin** [comment]
This is information that should be part of panel.

**Comment by nickgrippin** [comment]
Adding a blocked label

**Comment by hkeeler** [comment]
Is this really lookup against _panel_ data?  To me it does make more logical sense to work that way, but the edit itself reads more like its a comparison against the previous year's HMDA filing.

**Comment by debseidner** [comment]
This should be a lookup against Tax ID is on the transmittal sheet from the previous year but it isn't a bad idea to check the tax  id on the prior year's transmittal sheet AND the panel data to make sure NIC has the same value as the filer is providing (NIC is where the panel tax id would be from).

**Comment by hkeeler** [comment]
We're going to need to figure this one out for this sprint.  I currently have this as one we can unblock once #437 is finished, but I'm not-so-sure that's the case.  We either need to:

1. Do it as the description read, and check against the previous year's HMDA filing.  If this is the case, this will not be fixed by #437.
2. Change the edit to say we're going to check against institution data instead.  However, this is further complicated by the _previous calendar year_ statement.  Does this mean we need to track historical institution data as part of this?  If yes, that will complicate this quite a bit, and I'd suggest we continue to wait on this until we have the _real_ persistence solution in place, which likely will deal with historic data effectively.

I guess it depends on what exactly this edit it trying to check.  It _seems_ pretty legit to just check the submission's tax id against the current institution data, but I may be missing some nuance here.

**Comment by lesgou** [comment]
Per discussion, this will just be checked against previous year's TS.
