### ISSUE TITLE
Institutions API - PUT request

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#1805]
When running the local setup I'm able to perform `GET` and `POST` requests but the `PUT` method fails ...

[The `OPTIONS` request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) is failing with a `400 Bad Request` response of `CORS: invalid method 'PUT'`.

The console output says `Failed to load http://192.168.99.100:8081/institutions: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by jmarin** [comment]
Let's keep it open. We will need to retest this when we do the `k8s` setup
