### ISSUE TITLE
Validation (2017): Q130 (# of Loan Applications)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#181]
**Edit #:** Q130
**Type:** Quality
**Category:** Transmittal Sheet (only)
**Column:** # of Loan Applications

The number of loan/application records received in this transmission file per respondent does not = the total number of loan/application records reported in this respondent’s transmission or the total number of loan/application records in this submission is missing from the transmittal sheet.

Additional resources:
- [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
- [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
- [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by schbetsy** [comment]
Adding "blocked" label. Requires file/LAR persistence, so we know how many LARs are in current file.

**Comment by schbetsy** [comment]
Removing "blocked" label, since we now have aggregate edit check capability.
