### ISSUE TITLE
Institutions API - mismatch data types?

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#1812]
There seems to be a difference between the `rssd`, `parent.idRssd`, and `topHolder.idRssd` fields even though all contain `RSSD`s.

For example, trying to update `parent.idRssd` or `topHolder.idRssd` with something like`1234TEST1234` (alphanumeric) the API call fails with a response of `For input string: "123412asdf"`. But, if you send that same data, `1234TEST1234`, to the `rssd` field it will be successful.

Calls to update `parent.idRssd` and `topHolder.idRssd` with numeric data, e.g. `12341234`, are successful.

Should these fields all follow the same pattern? Should they allow only numeric or should they allow alphanumeric?

**Comment by jmarin** [comment]
Fixed by #1831
