### ISSUE TITLE
Create Parsing Objects for Exempt Codes

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-platform#1912]

**Comment by keileyo** [comment]
Exempt fields & codes:

Excluded Data Fields | Current Field Type | Exempt Code
-- | -- | --
ULI | Alphanumeric, String | The FI's loan ID up to 22 characters
Street Address | Alphanumeric, String | FI enters "Exempt"
City | Alphanumeric, String | FI enters "Exempt"
Zip Code | Alphanumeric, String | FI enters "Exempt"
Rate Spread | Alphanumeric, Double or NA | FI enters "Exempt"
Credit Score of Applicant or Borrower | Numeric, Integer | FI enters  "1111" for Exempt
Credit Score of Co-Applicant or Co-Borrower | Numeric, Integer | FI enters  "1111" for Exempt
Applicant or Borrower, Name and Version of Credit Scoring Model | Numeric, Integer | FI enters  "1111" for Exempt
Applicant or Borrower, Name and Version of Credit Scoring Model: Conditional Free Form Text Field for Code 8 | Alphanumeric, String or blank | Leave blank
Co-Applicant or Co-Borrower, Name and Version of Credit Scoring Model | Numeric, Integer | FI enters  "1111" for Exempt
Co-Applicant or Co-Borrower, Name and Version of Credit Scoring Model: Conditional Free Form Text Field for Code 8 | Alphanumeric, String or blank | Leave blank
Total Loan Costs | Alphanumeric, Double or NA | FI enters "Exempt"
Total Points and Fees | Alphanumeric, Double or NA | FI enters "Exempt"
Prepayment Penalty Term | Alphanumeric, Integer or NA | FI enters "Exempt"
Loan Term | Alphanumeric, Integer or NA | FI enters "Exempt"
Introductory Rate Period | Alphanumeric, Integer or NA | FI enters "Exempt"
Balloon Payment | Numeric, Integer | FI enters  "1111" for Exempt
Interest-Only Payments | Numeric, Integer | FI enters  "1111" for Exempt
Negative Amortization | Numeric, Integer | FI enters  "1111" for Exempt
Other Non-amortizing features | Numeric, Integer | FI enters  "1111" for Exempt
Property Value | Alphanumeric, Double or NA | FI enters "Exempt"
Submission of Application | Numeric, Integer | FI enters  "1111" for Exempt
Initially Payable to Your Institution | Numeric, Integer | FI enters  "1111" for Exempt
Mortgage Loan Originator NMLSR Identifier | Alphanumeric, Integer or NA | FI enters "Exempt"
Origination Charges | Alphanumeric, Double or NA | FI enters "Exempt"
Discount Points | Alphanumeric, Double or NA or Blank | FI enters "Exempt"
Lender Credits | Alphanumeric, Double or NA or Blank | FI enters "Exempt"
Interest Rate | Alphanumeric, Double or NA | FI enters "Exempt"
Debt-to-Income Ratio | Alphanumeric, Double or NA | FI enters "Exempt"
Combined Loan-to-Value Ratio | Alphanumeric, Double or NA | FI enters "Exempt"
Manufactured Home Secured Property Type | Numeric, Integer | FI enters  "1111" for Exempt
Manufactured Home Land Property Interest | Numeric, Integer | FI enters  "1111" for Exempt
Multifamily Affordable Units | Alphanumeric, Integer or NA | FI enters "Exempt"
Automated Underwriting System: 1 | Numeric, Integer | FI enters  "1111" for Exempt
Automated Underwriting System: 2 | Numeric, Integer or Blank | Leave blank
Automated Underwriting System: 3 | Numeric, Integer or Blank | Leave blank
Automated Underwriting System: 4 | Numeric, Integer or Blank | Leave blank
Automated Underwriting System: 5 | Numeric, Integer or Blank | Leave blank
Automated Underwriting System: Conditional Free Form Text Field for Code 5 | Alphanumeric, String or blank | Leave blank
Automated Underwriting System Result 1 | Numeric, Integer | FI enters  "1111" for Exempt
Automated Underwriting System Result 2 | Numeric, Integer or Blank | Leave blank
Automated Underwriting System Result 3 | Numeric, Integer or Blank | Leave blank
Automated Underwriting System Result 4 | Numeric, Integer or Blank | Leave blank
Automated Underwriting System Result 5 | Numeric, Integer or Blank | Leave blank
Automated Underwriting System Result: Conditional Free Form Text Field for Code 16 | Alphanumeric, String or blank | Leave blank
Open-End Line of Credit | Numeric, Integer | FI enters  "1111" for Exempt
Business or Commercial Purpose | Numeric, Integer | FI enters  "1111" for Exempt
Reverse Mortgage | Numeric, Integer | FI enters  "1111" for Exempt
Reason for Denial: 1 | Numeric, Integer | FI enters  "1111" for Exempt
Reason for Denial: 2 | Numeric, Integer or Blank | Leave blank
Reason for Denial: 3 | Numeric, Integer or Blank | Leave blank
Reason for Denial: 4 | Numeric, Integer or Blank | Leave blank
Reason for Denial: Conditional Free Form Text Field for Code 9 | Alphanumeric, String or blank | Leave blank

**Comment by jmarin** [comment]
@keileyo Can you provide a sample file with exemptions? It would make it a lot easier to track and validate that all the changes to the parser are correct. Thanks

**Comment by keileyo** [comment]
ive added a sample file w/ a TS and single LAR that has all relevant exempt codes to the 2018 Edit Test Files folder on drive. it called Single LAR_Exempt Codes
