### ISSUE TITLE
Validation (2017): Q068 (Co-Applicant Ethnicity,)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#195]
**Edit #:** Q068
**Type:** Quality
**Category:** Loan Application Register (only)
**Column:** Co-Applicant Ethnicity,

If action taken type = 1-5, 7 or 8, and applicant ethnicity, race and sex=4,7,4, respectively, and co-applicant ethnicity, race and sex=4,7,4, respectively, and there is no co-applicant, then co-applicant ethnicity, race, and sex should=5,8,5, respectively.

Additional resources:
* [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
* [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
* [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by schbetsy** [comment]
Explanation from the edit requirements document: 

> "Loans should not have a non-natural person for both the applicant and the co-applicant. Please confirm this is correct and that this should not be one non-natural person as the applicant and no co-applicant in the co-applicant fields."

Restatement of logic for programming:
If action taken type = 1-5 or 7-8 AND applicant ethnicity, race sex = 4,7,4,
then Co-Applicant ethnicity, race, sex should not = 4,7,4.
