### ISSUE TITLE
Update and delete emails

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#1980]
`ModifyInstitution` and `DeleteInstitution` events should trigger updates / deletes in the institutions read side.

**Comment by jmarin** [comment]
@nickgrippin This is already done, correct?

**Comment by nickgrippin** [comment]
Modification is completed, but the `DeleteInstitution` event does not trigger any changes to the email table.

**Comment by jmarin** [comment]
Can you create a ticket for delete events? Thank you

**Comment by nickgrippin** [comment]
https://github.com/cfpb/hmda-platform/issues/2088
