### ISSUE TITLE
Institutions admin API - required fields

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#2004]
When trying to create a new institution there are several cases that return a `400`.

An example response looks like:
```
The request content was malformed:
Int: DownField(agency)
```

A `400` response, like the one above, was found when trying to create an institution without the following fields (there could be others):
- agency code
- RSSD (institution, parent, top holder)
- institution type
- assets
- lender code

Are these fields __required__? Or is only `LEI` required?

If so, can we add that to the [documentation](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/api/admin-api.md) and improve the response message to say that the field is required, rather than `malformed`?

If not, we'll need to all the request (as long as there is an `LEI`).

**Comment by jmarin** [comment]
The API is expecting an object with the schema of an institution. So I think what is going on is that you are passing JSON that is only partially conformant with that. The API is somewhat typed in that sense. I _think_ that you can pass empty values, if that is what you are already doing then this is a bug

**Comment by awolfe76** [comment]
Here's an example of the request payload (sorry for the one-liner, but just wanted to show the full payload was there):
```json
{"activityYear":2018,"LEI":"asdf","agency":"","institutionType":"","institutionId2017":"","taxId":"","rssd":"","emailDomains":[],"respondent":{"name":"","state":"","city":""},"parent":{"idRssd":"","name":""},"assets":"","otherLenderCode":"","topHolder":{"idRssd":"","name":""},"hmdaFiler":true}
```

__But, I see now that I'm passing `string`s for most properties, when I should pass an `Int` for some of them.__

Should I pass a default `Int` in those cases? Is [this file](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Institution_Data_Model_Spec.csv) still the right place to check for the types? And, if so, should we add defaults to that?

**Comment by jmarin** [comment]
Yeah, some fields are numeric and need a default value if passing an empty JSON. The file you linked is the spec, unless there are errors it's the official data model. In case you are curious or need more details the implementation is [here](https://github.com/cfpb/hmda-platform/blob/master/common/src/main/scala/hmda/api/http/codec/institution/InstitutionCodec.scala#L38) (you'll see which fields expect `Int`)

**Comment by jmarin** [comment]
Also, the admin API [docs](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/api/admin-api.md) have sample JSON responses where you can also see which fields are required to be numeric

**Comment by awolfe76** [comment]
Should _all_ of the `Int` values default to `-1`?
