### ISSUE TITLE
HMDA Platform Edits Not Triggering 

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#2059]
Here is a list of all of the edits I've found issues with so far. 
- [x] V619
- [x] V619-2
- [x] V619-3
- [x] V622
- [x] V629
- [x] V629-2
- [x] V629-3
- [x] V631
- [x] V631-2
- [x] V631-3
- [x] V631-4
- [x] V632
- [x] V632-2
- [x] V632-3

**Comment by keileyo** [comment]
I updated these to check boxes for ease of tracking which are resolved.
