### ISSUE TITLE
Institution Admin API accepts requests on any path

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#2121]
`http POST :8081/institutions @institutions-add.json` works

However, 

`http POST :8081/anythingelsehere @institutions-add.json` also works.

**Comment by nickgrippin** [comment]
I noticed we also have a [repeated path here](https://github.com/cfpb/hmda-platform/blob/master/hmda/src/main/scala/hmda/api/http/admin/InstitutionAdminHttpApi.scala#L67-L106).  Could we clean it up as part of this ticket?
