### ISSUE TITLE
Validation (2017): Q595 (MSA/MD Number)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#213]
**Edit #:** Q595
**Type:** Quality
**Category:** Loan Application Register (only)
**Column:** MSA/MD Number

If action taken type = 1-5, 7, or 8, then MSA/MD must = a corresponding respondent, MSA/MD combination on respondent panel, or NA. @NOTE: This edit is not applied to mortgage banking subsidiaries or independent mortgage companies. Their Metropolitan Statistical Areas or Metropolitan Divisions (if appropriate) will be determined at the end of the cycle based on the data reported. For depository institutions, this edit will produce the Q595 report but will not be counted in any error statistics.

Additional resources:
- [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
- [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
- [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by kgudel** [comment]
Marking this as blocked since it requires panel

**Comment by lesgou** [comment]
Additional explanation: 
1) If the filer is a depository institution, and 
2) The reported loan is not a purchased loan, then

The reported MSA/MD for this loan should be listed on the panel as where the bank has a branch. Please indicate (yes/no) if you have a branch in this msa/md.

**Comment by hkeeler** [comment]
Thanks @lesgou!  That's much clearer.

**Comment by lesgou** [comment]
Updating requirements:

If institution type <9
and action taken type = 1, 2, 3, 4, 5, 7, or 8

Then list the MSA/MD where the filer does not have a branch office.

Include the following information:
MSA/MD ID
MSA/MD Name
Number of loans in this MSA/MD

**Comment by nickgrippin** [comment]
Closing this ticket, edit will not be checked.

**Comment by lesgou** [comment]
This edit is no longer relevant due to changes in architecture.
