### ISSUE TITLE
Filing status not correct?

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#2134]
When hitting the `/v2/filing/institutions/B90YWS6AFX2LGWOXJ1LD/filings/2018` endpoint (I did create the filing) I get a response of

```json
{
  "filing": {
    "period": "2018",
    "lei": "B90YWS6AFX2LGWOXJ1LD",
    "status": { "code": 2, "message": "in-progress" },
    "filingRequired": true,
    "start": 1541010323132,
    "end": 0
  },
  "submissions": []
}
```

The `status` doesn't seem right to me given that `submissions` is `[]`.

I don't think there is a doc for the v2 filing status codes, but from [the v1 doc](https://github.com/cfpb/hmda-platform/blob/8222f7e8e5f3089e87eb210fc977bec0be8b0d98/docs/v1/filing-status.md) is looks like we should be at a filing status of `1: not-started - A filing has been opened but no submission has been submitted for the filing`.

**Comment by awolfe76** [comment]
It looks like the filing status is the same even after a signature too. And the end date, `end`, isn't being set.

```json
{
  "filing": {
    "period": "2018",
    "lei": "BANK1LEIFORTEST12345",
    "status": { "code": 2, "message": "in-progress" },
    "filingRequired": true,
    "start": 1543423168708,
    "end": 0
  },
  "submissions": [
    {
      "id": {
        "lei": "BANK1LEIFORTEST12345",
        "period": "2018",
        "sequenceNumber": 106
      },
      "status": {
        "code": 15,
        "message": "Your submission has been accepted.",
        "description": "This completes your HMDA filing process for this year. If you need to upload a new HMDA file, the previously completed filing will not be overridden until all edits have been cleared and verified, and the new file has been submitted."
      },
      "start": 1545308260265,
      "end": 1545308330522,
      "fileName": "clean_file_10_rows_Bank1_syntax_validity.txt",
      "receipt": "BANK1LEIFORTEST12345-2018-106-1545308330522"
    }
  ]
}
```

_Note: We don't have docs for this status in v2. [Here are the docs for v1.](https://github.com/cfpb/hmda-platform/blob/master/docs/v1/filing-status.md)_

**Comment by omnipresent07** [comment]
Fixed in https://github.com/cfpb/hmda-platform/pull/2385
