### ISSUE TITLE
Edit Details Endpoint

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#2169]
### Edit Details

`/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits/<edit>`

`GET` - For an edit, return a collection of all rows that failed it, including the relevant fields and their values.

| Query parameter | Description |
| --------------- | ----------- |
| page | Integer. If blank, will default to page 1. Page size is 20 lines of errors. |

This endpoint is paginated. The response contains 3 fields of pagination metadata:

 - `total`: total number of occurrences of this validation error for this file
 - `count`: number of rows with errors returned on this page. Full page contains errors from 20 lines of the HMDA file.
 - `links`: the `href` field is the path to this resource, with a `{rel}` to be replaced with the query strings in the `first`, `prev`, `self`, `next`, `last` fields.

Example response:

```json
{
   "edit":"Q036",
   "rows":[
      {
         "id":"4514746044",
         "fields":[
            {
               "name":"Property Type",
               "value":2
            },
            {
               "name":"Loan Amount",
               "value":213
            }
         ]
      },
      {
         "id":"6072140231",
         "fields":[
            {
               "name":"Property Type",
               "value":2
            },
            {
               "name":"Loan Amount",
               "value":185
            }
         ]
      }
   ],
   "count":2,
   "total":2,
   "_links":{
      "self":"?page=1",
      "prev":"?page=1",
      "last":"?page=1",
      "next":"?page=1",
      "first":"?page=1",
      "href":"/institutions/2/filings/2017/submissions/2/edits/Q036{rel}"
   }
}
```

**Comment by jmarin** [comment]
@awolfe76 I'm starting to look into the edit details endpoint, which is the hardest one to implement and the one that gave us some pain last year. I have some ideas on how to make this work, but first I need to make some modifications to the `json` response as described in this ticket. Take a look at it when you get a chance and let me know if there is anything in here that jumps out at you. Thanks

**Comment by awolfe76** [comment]
Yeah, it's a bit of refactoring for the changes but doesn't seem bad. Go for it! 👍
