### ISSUE TITLE
Download edits as CSV (HTTP endpoint)

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#2171]
### Edits CSV

`/institutions/<institutionId>/filings/<period>/submissions/<submissionId>/edits/csv`

`GET` - Returns a list of all validation errors for the submission, formatted as CSV for use in spreadsheet software

Example response:

```csv
editType, editId, loanId
Syntactical, S020, Transmittal Sheet
Validity, V125, Transmittal Sheet
Quality, Q027, 9553605194
Quality, Q027, 9401122359
Quality, Q027, 2156575876
Quality, Q027, 12073393.95
Quality, Q027, 4101572269
Quality, Q027, 4748775957
Quality, Q027, 6024192341
Quality, Q027, 621742533.4
Macro, Q023,
```

**Comment by omnipresent07** [comment]
Already implemented https://github.com/cfpb/hmda-platform/blob/master/hmda/src/main/scala/hmda/api/http/filing/submissions/EditsHttpApi.scala#L99
