### ISSUE TITLE
Validation (2017): Q011 (Total Number of Loan Applications)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#224]
**Edit #:** Q011
**Type:** Macro
**Category:** The Macro Quality Edit Report contains the following edits and is generated by the FFIEC
**Column:** Total Number of Loan Applications

If the current or previous year's total number of applications is ≥ 500, then the current year should be within (+ or -) 20% of the previous year's total.

Additional resources:
- [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
- [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
- [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by schbetsy** [comment]
Requires previous year's data. Marking as blocked.
