### ISSUE TITLE
(Keycloak) Registration

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#2243]
Do the registration forms for the filing application and the HMDA help application conflict? 

We need to be able to handle the registration and login processes for both applications. The registration requires different fields (the help application will only need a username/email and password?).

I think we need to test this out more to see what's needed.

**Comment by keileyo** [comment]
right now - yes they conflict. Currently, the registration process for both is the same. Its not a huge deal as all of our HH registrations are @cfpb.gov email addresses, so they just have to also register to be a bank 0 or bank 1 filer & then we manually change the role to hmda-admin. Ideally, the registrations processes would be separate.

**Comment by awolfe76** [comment]
Cool, I thought that would be the case. We'll have to investigate splitting those out at some point. Thanks, @keileyo.
