### ISSUE TITLE
Update name field for edits with underscore

### ISSUE THREAD

**Issue by nickgrippin** [cfpb/hmda-platform#2285]
Some edits have a name defined as "V629_2", which will break the edit text lookup.  Replace all instances of this naming convention with a hyphen (e.g. "V629-2").

**Comment by awolfe76** [comment]
@kgudel - this one _sounds like_ it may have been handled by some of the edits work you were doing. Do you think we can close it?

**Comment by kgudel** [comment]
This issue is no longer relevant.
