### ISSUE TITLE
Q618 details endpoint returns error - only found in 1 case

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#2293]
[This file](https://github.com/cfpb/hmda-platform/blob/master/data/clean_test_files/bank_0/clean_file_10_rows_Bank0_syntax_validity.txt) returns quality edits, including Q618. When the call for the details is made the response status code is `504 Gateway Timeout` and the response itself is `upstream request timeout`.

_This does NOT happen will the other files for Bank 0 (3, 100, 100 ... rows)._

**Comment by jmarin** [comment]
More details. The backend prints the following message

```
[INFO] [11/30/2018 20:29:20.985] [hmda2-akka.actor.default-dispatcher-35] [akka.actor.ActorSystemImpl(hmda2)] Request timeout encountered for request [GET /institutions/B90YWS6AFX2LGWOXJ1LD/filings/2018/submissions/111/edits/Q618 Empty]
```

**Comment by omnipresent07** [comment]
This was also happening on 100 row file but beginning page 4. It looks like there were duplicates of Q618. These duplicates were throwing off the pagination. https://github.com/cfpb/hmda-platform/pull/2298 Fixes it.

<img width="1232" alt="screen shot 2018-12-01 at 3 11 11 pm" src="https://user-images.githubusercontent.com/44377678/49346517-e2ac3f80-f661-11e8-966b-b75abfc5dc12.png">
