### ISSUE TITLE
Set cache control for api responses

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform#2301]
Some api responses need to be explicitly uncached, namely, `/latest` and any `POST` request. Other responses should have long cache expiry set.

**Comment by awolfe76** [comment]
We are doing a few updates on the front-end that might fix this ...
https://github.com/cfpb/hmda-platform-ui/pull/1187
https://github.com/cfpb/hmda-platform-ui/pull/1185
https://github.com/cfpb/hmda-platform-ui/pull/1182

We update here after some more testing.

**Comment by awolfe76** [comment]
Closing, the UI updates look like they've fixed this issue.
