### ISSUE TITLE
Make institution checkbox on register page a required field

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#2303]
In the below screenshot if the checkbox for Bank0 is not selected, and the user clicks `Register`, an upstream error happens. 

Ideally, the `Register` button should be disabled until the institution is selected. 

<img width="618" alt="screen shot 2018-12-03 at 3 46 21 pm" src="https://user-images.githubusercontent.com/44377678/49400645-e4820b80-f712-11e8-821e-3dfdadf90070.png">

**Comment by awolfe76** [comment]
Closing. There are situations where we need to allow for this.
