### ISSUE TITLE
404's for images in keycloak

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#2337]
The path to the files, `/filing//favicon-57.png`, is incorrect.

Logs from Ambassador:

```
ACCESS [2018-12-10T20:00:11.785Z] "GET /filing//favicon-57.png HTTP/1.1" 404 - 0 125 0 0 "209.162.202.34" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" "6eb43328-6b2c-418c-b3eb-551363278feb" "ffiec.beta.cfpb.gov" "10.100.38.57:80"
ACCESS [2018-12-10T20:00:13.613Z] "GET /filing//ffiec-logo.svg HTTP/1.1" 404 - 0 125 0 0 "71.40.211.34" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" "14c52a09-f694-4f89-bb28-fdbc1107c058" "ffiec.beta.cfpb.gov" "10.100.38.57:80"
```

**Comment by zencircle** [comment]
`ACCESS [2018-12-10T20:39:25.487Z] "GET /auth/resources/4.2.1.final/login/hmda/img/alerts/success.svg HTTP/1.1" 404 - 0 0 1 1 "207.87.217.98" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "15b2e2b9-206c-4c0b-b6fc-c63916c9009e" "ffiec.beta.cfpb.gov" "10.100.111.219:80"
`

**Comment by zencircle** [comment]
`ACCESS [2018-12-11T17:42:06.588Z] "GET /auth/resources/4.2.1.final/login/hmda/img/arrow-both.svg HTTP/1.1" 404 - 0 0 1 1 "165.212.246.21" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)" "e77a9ba4-131c-4853-b0e4-c4dc5a2c44bb" "ffiec.beta.cfpb.gov" "10.100.111.219:80"`

**Comment by zencircle** [comment]
`
ACCESS [2018-12-03T19:13:34.525Z] "GET /auth/resources/4.2.1.final/login/hmda/css/hmda.css HTTP/1.1" 200 - 0 4261 1 1 "184.72.118.177" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "472cd8b9-0fbe-43d2-a4aa-de621a1b99e4" "ffiec.beta.cfpb.gov" "10.100.111.219:80"
ACCESS [2018-12-03T19:13:34.525Z] "GET /filing//favicon-57.png HTTP/1.1" 200 - 0 521 1 1 "184.72.118.177" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "33a6fe4c-1669-4ae4-8eda-109afaed99ce" "ffiec.beta.cfpb.gov" "10.100.244.118:80"
`
