### ISSUE TITLE
LEI match should be case insensitive

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#2339]
if LEI is `B90YWS6AFX2LGWOXJ1LD` and uploaded file has LEI `b90YWS6AFX2LGWOXJ1LD `, it should not result in code `9` -- example Bank0 - 10 row file

**Comment by nickgrippin** [comment]
There are two edits that check LEI: S301 (TS) and S303 (LAR).  I'm assuming both of these should be changed to be case-insensitive? @keileyo
