### ISSUE TITLE
Publish Modified LAR to S3

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#2341]
`Loan Application Register` needs to be processed into `Modified Loan Application Register` as follows:

**1. Redacted fields**
Remove the following fields from the public data set:
* ULI
* Application Date
* Action Taken Date
* Street Address
* City
* Zip Code
* Ethnicity of Applicant or Borrower: Free Form Text Field for Other Hispanic or Latino
* Ethnicity of Co-Applicant or Co-Borrower: Free Form Text Field for Other Hispanic or Latino 
* Race of Applicant or Borrower: Free Form Text Field for Enrolled or Principal Tribe
* Race of Applicant or Borrower: Free Form Text Field for Other Asian
* Race of Applicant or Borrower: Free Form Text Field for Other Pacific Islander
* Race of Co-Applicant or Co-Borrower: Free Form Text Field for Enrolled or Principal Tribe
* Race of Co-Applicant or Co-Borrower: Free Form Text Field for Other Asian
* Race of Co-Applicant or Co-Borrower: Free Form Text Field for Other Pacific Islander
* Credit Score of Applicant or Borrower
* Credit Score of Co-Applicant or Co-Borrower
*  Applicant or Borrower - Name and Version of Credit Scoring Model: Conditional Free Form Text Field for Code 8
* Co-Applicant or Co-Borrower - Name and   Version of Credit Scoring Model: Conditional Free Form Text Field for Code 8
* Reason for Denial: Conditional Free Form Text Field for Code 9 free-form text field
* NMLSR identifier
* Automated Underwriting System: Conditional   Free Form Text Field for Code 5
* Automated Underwriting System Result: 1
* Automated Underwriting System Result: 2
* Automated Underwriting System Result: 3
* Automated Underwriting System Result: 4
* Automated Underwriting System Result: 4
*  Automated Underwriting System Result: Conditional Free Form Text Field for Code 16
--

 **2. Binning or rounded**

* Loan Amount: bin to midpoint for the $10,000 interval into which the value falls (i.e. if $252,476 --> $250,000 - $259,999.99 bin and would be reported as $255,000)
* Age of Applicant or Borrower: 
  - <25 
  - 25-34
  - 35 - 44
  - 45 - 54
  - 55 - 64
  - 65 - 74
  - 74+
* Add "Applicant Age >= 62" field, with the following logic: 
  - If the age is >= 62, return "Yes"
  - If the age is < 62, return "No"
  - If age is reported 8888 or 9999, return "NA"
* Age of Co-Applicant or Co-Borrower: same as above
* Property Value: bin to midpoint for the $10,000 interval into which the value falls (see example above for loan amount). If Property value is reported NA or Exempt, don't modify - return NA or Exempt as reported. 
* Debt to Income Ratio: 
  - Disclose exact values between 36% and 50%
  - < 20%
  - 20% - <30% 
  - 30% - <36%
  - 50% - <60%
  - 60%+
If reported NA or Exempt, don't modify - return NA or Exempt as reported. 
* Total Units: 
  - Disclose exact number if total units is <5
  - 5-24
  - 23-49
  - 50-99
  - 100-149
  - 150+
* Multifamily Affordable Units: report as percentage --> multifamily affordable units / total units reported. Round to a whole number. If reported NA or Exempt, don't modify - return NA or Exempt as reported.

**Comment by jmarin** [comment]
@keileyo Can you complete this? In particular, the list of redacted fields. Thank you

**Comment by keileyo** [comment]
Filled in the information in your original comment. I added the rest of the redacted fields, and added some information about keeping NA or Exempt when reported for Property Value, DTI and Multifamily Affordable Units.

**Comment by keileyo** [comment]
@MichaelFurey17 is working on a sample file in the modified LAR format.
