### ISSUE TITLE
Modified LAR Adding Zeros as Blank Entries

### ISSUE THREAD

**Issue by MichaelFurey17** [cfpb/hmda-platform#2352]
Modified LAR appears to zero-fill blank fields. It's possible that it might be a data type issue.

**Comment by jmarin** [comment]
Which fields?

**Comment by MichaelFurey17** [comment]
There is zero-filling happening in any field where the value should be blank. To name a few fields:  Ethnicity of Applicant Fields (2-5), Ethnicity of Co-Applicant Fields(2-5), Race of Applicant Fields (2-5), Race of Co-Applicant Fields (2-5). 

However, I think that blank fields are being expressed as zeroes generally in the modified LAR file. The only field that may permit 0's is Property Type. Let me know what I can do!
