### ISSUE TITLE
Summary endpoint 504s

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform#2369]
With the merge of https://github.com/cfpb/hmda-platform/pull/2355, the summary endpoint should work, but instead results in a 504 Gateway Timeout.

**Comment by wpears** [comment]
This seems to be intermittent, as I'm currently getting a 200 and correct data from the endpoint.

**Comment by omnipresent07** [comment]
PR coming shortly. It is missing a serializer.
