### ISSUE TITLE
Institution events - follow up

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#2371]
Seeing some inconsistent behavior with institution events (email domain specifically):

Initially, I added a new test bank - BANK5LEIFORTEST12345 with email domains @bank5.com and @cfpb.gov. 
- I was able to see the new bank in the institutions API: https://hmda4.demo.cfpb.gov/v2/public/institutions/BANK5LEIFORTEST12345
- I was not able to register for Bank 5 on the platform: 
![image](https://user-images.githubusercontent.com/13036571/50126412-c8b25580-023a-11e9-8922-b1dbbfaa1503.png)

I went back and deleted bank 5 & added is again. This time i added only bank5.com as a single email address & this worked in platform. I went back in and added cfpb.gov as an update to the institution and now both work for registration purposes. However, it does look like the API is duplicating email addresses:

HH app:
![image](https://user-images.githubusercontent.com/13036571/50126656-d1575b80-023b-11e9-8e7a-c01905539cda.png)

API:
![image](https://user-images.githubusercontent.com/13036571/50126681-ea600c80-023b-11e9-9864-84d9e34d17ee.png)

It seems like this is fairly minor, but I'm concluding:
1) you cannot add two email domains to a new institution. you need to add the first one and then add the second one
2) if you update an email domain in the HH app, it will duplicate it in the API. The API & HH app results are out of sync.

**Comment by keileyo** [comment]
Editing this:

The issue is that when attempting to add either 2+ email domains to a new institution or adding an email domain to an existing institution that already has an email domain, the API is picking those up as a single domain. So adding bank5.com, cfpb.gov adds one domain "bank5.com, cfpb.gov" 

In order to get around this, in the HH app, you can only add one domain at a time. If you need to add a domain to an existing institution, you need to remove the existing domain and only add the new one. This will then put the data shown by the app & the data in the institutions API & database out of sync  (HH app will show a single domain, institutions API will show both the old domain & new domain)

**Comment by awolfe76** [comment]
Closing this for now, see https://github.com/cfpb/hmda-help/issues/44.
