### ISSUE TITLE
Undefined institution

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#2374]
Have been seeing this on local instance intermittently when creating institution. We've seen this on front end a few times as well. 

Local instance log shows:

```
[INFO] [12/17/2018 22:05:52.082] [hmda2-akka.actor.default-dispatcher-90] [akka://hmda2/system/sharding/Institution/939/Institution-undefined] Started Institution: Institution-undefined
```

**Comment by awolfe76** [comment]
@omnipresent07 - have you noticed this one recently? I think this was actually a [front-end problem that has been resolved](https://github.com/cfpb/hmda-platform-ui/pull/1204).
