### ISSUE TITLE
 Edits Details errors

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#2379]
Seeing some issues with the edits details returning for certain fields and/or edits:

1) Field name mismatch. Instead of returning the value in the field, a field name mismatch is returning in the edits details. Known fields affected:
- Credit Score of Co-Applicant or Co-Borrower: Co-Applicant or Co-Borrower, Name and Version of Credit Scoring Model
- Applicant or Borrower, Name and Version of Credit Scoring Model: Conditional Free Form Text Field for Code 8
- Sex of Applicant or Borrower: 1
- Sex of Coo-Applicant or Co-Borrower: 1
![image](https://user-images.githubusercontent.com/13036571/50176702-1b891d00-02ce-11e9-9c25-1737eca50c1b.png)

~~2) Edits that don't have edits details fields returned (showing only ULI)
Known edits:~~
~~- V625-2~~
![image](https://user-images.githubusercontent.com/13036571/50176972-ce597b00-02ce-11e9-8299-633d16d3fec1.png)

* Editing out condition 2 - edits details are not set up for edits that call a separate microservice. If we want to add this functionality, ill create a separate issue. 

3) We will document in this ticket any edits details that are not returned in full (i.e. edits that do not call a separate microservice, but that have fields missing from the details returned).

**Comment by keileyo** [comment]
I'll continue to update this as I see additional fields or edits that produce the behavior above.

**Comment by omnipresent07** [comment]
@keileyo I understand this has WIP tag, but it'll be useful to know what the edit details fields should show for edits that don't have edits details fields.

**Comment by keileyo** [comment]
@omnipresent07 I think the edits details thing is actually just that the backend is not set up to return the edits details for the edits that call a separate microservice. I don;t think this is critical to implement, so im going to cross out that portion of the original issue.

However, i have seen one or two edits where the details were returning incompletely (some fields missing) and ill document those in this ticket.

**Comment by curtinapope** [comment]
@kgudel These are the additional fields triggering the error field mismatch: 
- Debt to income ratio 
- Ethnicity of Co-Applicant or Co-Borrower: 5
- Ethnicity of Co-Applicant or Co-Borrower: Free Form Text Field for Other Hispanic or Latino
- Ethnicity of Co-Applicant or Co-Borrower 1
- Race of Co-Applicant or Co-Borrower 1
- Ethnicity of Co-Applicant or Co-Borrower: 4

**Comment by curtinapope** [comment]
@kgudel 
- Race of Applicant or Borrower: Free Form Text Field for Other Pacific Islander

**Comment by curtinapope** [comment]
@kgudel 

- Ethnicity of Co-Applicant or Co-Borrower: 2

**Comment by curtinapope** [comment]
@kgudel 
- Sex of Applicant or Borrower

**Comment by cpope28** [comment]
@chynnakeys 
test

**Comment by cpope28** [comment]
@kgudel 

- Ethnicity of Co-Applicant or Co-Borrower 1
- Race of Co-Applicant or Co-Borrower 1

**Comment by cpope28** [comment]
@kgudel 

-Race of Applicant or Borrower: Free Form Text Field for Other Asian
- Race of Applicant or Borrower: 3
- Race of Applicant or Borrower: 4
- Race of Applicant or Borrower: 5
- Race of Applicant or Borrower: 1
- Race of Applicant or Borrower Collected on the Basis of Visual Observation or Surname

**Comment by cpope28** [comment]
@kgudel 














-



 




@kgudel 

- Race of Applicant or Borrower: 2
- Race of Applicant or Borrower: Free Form Text Field for Other Pacific Islander

**Comment by cpope28** [comment]
@kgudel 

- Sex of Co-Applicant or Co-Borrower

**Comment by kgudel** [comment]
@cpope28 could you include the edits that triggered those errors along with the field that errors.

**Comment by cpope28** [comment]
@kgudel 

I was testing on my personal laptop so I don't have all of the edits. Here are some 

V.679-2
•	v 613.3
•	v.613.4

V.663  
•	v.613.3
•	v 613.4

V.664 
•	v.614.1

V 679-3 
•	v.614.2

**Comment by Arsadeghi4** [comment]
@kgudel v668_2 also produces the same errors.

**Comment by keileyo** [comment]
Here are some other edits that produce the issue:
- V635-4: Race of Applicant or Borrower: Free Form Text Field for Other Asian
- V636-3: Race of Applicant or Borrower: Free Form Text Field for Other Asian
- V651-2: Ethnicity of Applicant or Borrower 1, Race of Applicant or Borrower 1
- V636-2: Race of Applicant or Borrower: Free Form Text Field for Other Asian

**Comment by chynnakeys** [comment]
V605: Contact Person's Office Zip Code

**Comment by awolfe76** [comment]
@kgudel - Do you know if all of these are complete now? Can we close this one?

**Comment by kgudel** [comment]
All issues except for `V605: Contact Person's Office Zip Code` appear to be fixed.
