### ISSUE TITLE
/sign endpoint not persisting data

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#2394]
An example ...

When I sign for bank 1 the `/sign` endpoint returns
```json
{
  "timestamp": 1545408148742,
  "receipt": "BANK1LEIFORTEST12345-2018-329-1545408148742",
  "status": {
    "code": 15,
    "message": "Your submission has been accepted.",
    "description": "This completes your HMDA filing process for this year. If you need to upload a new HMDA file, the previously completed filing will not be overridden until all edits have been cleared and verified, and the new file has been submitted."
  }
}
```
which is good.

But if I go view bank 0 and then come back to bank 1 the `/sign` endpoint returns
```json
{
  "timestamp": 0,
  "receipt": "",
  "status": {
    "code": 15,
    "message": "Your submission has been accepted.",
    "description": "This completes your HMDA filing process for this year. If you need to upload a new HMDA file, the previously completed filing will not be overridden until all edits have been cleared and verified, and the new file has been submitted."
  }
}
```

**Comment by omnipresent07** [comment]
@awolfe76 @wpears Does something need to change on front end for this as well? In the screenshot below I'm seeing receipt number and enddate returned from the backend for latest submission. However, the date on frontend is still shown as December 31, 1969. If the frontend is reading the date from another endpoint and it dosn't have a date, please let me know. 

<img width="1440" alt="screen shot 2018-12-27 at 8 02 04 am" src="https://user-images.githubusercontent.com/44377678/50481133-dfc91400-09ad-11e9-884c-e147861c503b.png">

**Comment by awolfe76** [comment]
We aren't using the `/latest` endpoint to populate that data. That data is coming from the `/sign` endpoint ... in the cases where it is failing, that is specifically the `GET` request to `/sign`. 

#### Example response from `GET` for `/sign`
There is no `timestamp` or `receipt`.
```json
{
  "timestamp": 0,
  "receipt": "",
  "status": {
    "code": 15,
    "message": "Your submission has been accepted.",
    "description": "This completes your HMDA filing process for this year. If you need to upload a new HMDA file, the previously completed filing will not be overridden until all edits have been cleared and verified, and the new file has been submitted."
  }
}
```
