### ISSUE TITLE
WIP - Weekly reporting for stakeholders 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#2449]
Internal & external (FFIEC) stakeholders are interested in weekly reporting metrics during the filing period. Last year, we provided the following metrics, so this is a good place to start:

- Number of filers overall, number of filers by week
- Number of LARs overall, number of LARs by week
- Number of filers & number of LARs by agency code

Note: putting WIP on this bc i want to discuss more with the team the best approach & metrics to include in reporting.

**Comment by omnipresent07** [comment]
`lar` and `ts` tables have been modified to add a `created_at` timestamp column. This did not require a re-deployment of the hmda-analytics service.

**Comment by omnipresent07** [comment]
> The `lar` and `ts` tables referenced are on`RDS Postgres`?

Correct.

**Comment by omnipresent07** [comment]
Some other metrics that might be useful:

- Number of LARs by county/tract?
- Top denial reasons
