### ISSUE TITLE
Filtering institutions or use admin API

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#2472]
The `hmda-regulator` service added in [filters](https://github.com/cfpb/hmda-platform/blob/baac33f910ffe0b019330a914525e91b7a983b2c/kubernetes/hmda-regulator/values.yaml#L72) to remove certain institutions from the regulator data publishing process.

Would other reporting services (modified LAR, IRS, etc) also need to take advantage of this list?

If so, would we be better off handling this list using the institutions admin API?

My thought is that we could use the `hmdaFiler` flag to know if an institution should have publication data generated or not. We would have to allow for this in the HMDA help application, an input to allow for updating that flag. Then, when any reporting needs to be generated each service could take advantage of the Admin API to get an institution, read that value (`true` or `false`), and decide to generate the reports or not.

**Comment by omnipresent07** [comment]
Modified LAR and IRS read from the cassandra journal, which doesn't have the `hmdaFiler` flag. Only the Postgresql DB has the `hmdaFiler` flag. Also, being able to change environment variables gives us flexibility while testing in dev servers. modifiedLar and IRS should, however, should take advantage of the filters used in the `hmda-regulator`

**Comment by omnipresent07** [comment]
Closed by https://github.com/cfpb/hmda-platform/pull/2533
