### ISSUE TITLE
Q617 - Possible bug in deserializing prior to check run

### ISSUE THREAD

**Issue by charandas** [cfpb/hmda-platform#2492]
If I am to make a submission using the values of CLTV (50), loan amount (50.4) and property value (100.0) from the [unit test](https://github.com/cfpb/hmda-platform/blob/master/hmda/src/test/scala/hmda/validation/rules/lar/quality/Q617Spec.scala#L34-L42), the platform v2.7.4 raises Q617.

Since the unit tests are passing, I surmise that the bug is not in the check [implementation](https://github.com/cfpb/hmda-platform/blob/master/hmda/src/main/scala/hmda/validation/rules/lar/quality/Q617.scala) itself. My first hunch is that it converts CLTV values like 50 with zero precision to 50.0 causing the failure.

The protobuf for lar register itself uses a `string` to store the value, so that part is correct. I tried looking through cassandra/journal but don't have the in-depth knowledge to pin point a line of code :)

**Comment by charandas** [comment]
Anyone else experiencing this issue? /cc @keileyo

**Comment by keileyo** [comment]
thanks for reporting - i'll do some testing and look into this.

**Comment by charandas** [comment]
Any news so far?

**Comment by charandas** [comment]
Possibly resolved by [f4b0f5090](https://github.com/cfpb/hmda-platform/commit/f4b0f50900399df9addcdb857e9643974c9468e8)

**Comment by keileyo** [comment]
Yeah - this was resolved in our latest release.
