### ISSUE TITLE
Implement CSV file parser tests

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#250]
Similar to https://github.com/cfpb/hmda-platform/blob/master/parser/jvm/src/test/scala/hmda/parser/fi/FIDataDatFileParserSpec.scala and https://github.com/cfpb/hmda-platform/blob/master/parser/js/src/test/scala/hmda/parser/fi/FIDataDatFileParserSpec.scala but with CSV data

**Comment by schbetsy** [comment]
Putting this ticket on hold until we've decided whether ScalaJS is staying in the project.

**Comment by schbetsy** [comment]
Property tests exist for parsing FI data (including individual TS and LAR specs) from CSV.
To close, just need to implement `FIDataCsvFileParserSpec`, to demonstrate parsing directly from a file.
