### ISSUE TITLE
Regulator data service producing blank files. 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#2503]
Nightly regulator data has been producing empty LAR files.  Out of the past 5 days, the files for 1/19, 1/21 and 1/22 are blank without any data. 

1) Look into the root cause of the issue that is causing the data not to be populated
2) We should not ever produce blank files as this has downstream effects on the the receivers of the data. We would rather have no file produced than a blank file produced - this should be built into the regulator data service (thinking some kind of automated check that looks at file size/content and does not write to S3 based on size/content or immediately deletes the file if there is no content, etc)

@PatrickHSI @omnipresent07

**Comment by omnipresent07** [comment]
Regulator data service should also have an internal endpoint that accepts a date parameter. Hitting this endpoing will re-generate the regulator data for the passed in date.

**Comment by omnipresent07** [comment]
The environment variable needed by the regulator service to determine where to put the S3 files had incorrect values. This is why the data was empty for certain dates. We'll be resolving this by:

- [ ] 1. Putting this environment variable in the regulator service code and default it to the correct value. 
- [ ] 2. Put a check in regulator to do a count prior to creating file. Not create a file if count is 0.
- [ ] 3. Prepare scripts to create configmaps in kubernetes - [Separate ticket](https://github.cfpb.gov/HMDA-Operations/hmda-devops/issues/909)

**Comment by omnipresent07** [comment]
The regulator files for 01/23 have data now.

**Comment by awolfe76** [comment]
@omnipresent07 - Is step 2 ☝️ done and if so since step 3 is a separate issue, can we close this one?

**Comment by awolfe76** [comment]
@omnipresent07 - 🔔

**Comment by omnipresent07** [comment]
https://github.com/cfpb/hmda-platform/pull/2563
