### ISSUE TITLE
IRS report is generating all 0's

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#2516]
I received a HMDA Help request saying that their IRS report was generating all 0's. I tried with the test bank 0 - a 10, 100, and 1000 row file all generated an IRS with all 0's on HMDA4 and received the same result. See the attached screenshot. IT appears that this issue is repeatable with bank 0, but not with bank 1 files. 

![all 0 irs](https://user-images.githubusercontent.com/41752348/51762811-c5628300-209e-11e9-8609-212fe6208190.PNG)

.

**Comment by omnipresent07** [comment]
Related to #2526

**Comment by omnipresent07** [comment]
Fixed in Sprint 39
