### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#2521]
- [x] Get Telemetry working on hmda-platform w/ metrics to Prometheus.
- [x] Use Telemetry w/o putting jar in docker hub images and ensuring docker images don't break
- [x] Start Integrating Telemetry into hmda-platform -- Akka Streams, Akka HTTP, Akka Actors
- [x] Push metrics to prometheus or statsd
- [x] Use Grifana to pull from prometheus
- [ ] Deploy to k8 for testing - New ticket #2554 created for this

**Comment by omnipresent07** [comment]
PR with 1) telemetry installed 2) working with jenkins 3) deploying to docker hub (w/o telemetry) and deploying to DTR (w/ telemetry) is up for review: https://github.com/cfpb/hmda-platform/pull/2527

**Comment by awolfe76** [comment]
Closed by #2527
