### ISSUE TITLE
/filers public endpoints

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#2523]
Implementation is likely different than `v1` but the responses should be the same.

See [the `v1` docs](https://github.com/cfpb/hmda-platform/blob/master/docs/v1/public-api.md#hmda-filers) for the responses.

The `/filers/<period>` will now be 2018 and the `/filers/<period>/<institutionID>/msaMds` will now use `lei`.

---

These drive the publication UI for [modified LAR](https://ffiec.cfpb.gov/data-publication/modified-lar), [disclosure reports](https://ffiec.cfpb.gov/data-publication/disclosure-reports/2017), and [aggregate reports](https://ffiec.cfpb.gov/data-publication/national-aggregate-reports/2017).

**Comment by kgudel** [comment]
The first endpoint: `/filers/<period>` can be completed now.

The second: `/filers/<period>/<institutionID>/msaMds` is waiting on the new postgres table to be created as part of #2544

**Comment by awolfe76** [comment]
Talked with @kgudel, due to the updates in the data the response here will be similar to `v1` but with some property changes:

#### New response example:

```json
{
    "institutions": [
        {
            "lei": "0",
            "name": "bank-0 National Association",
            "period": "2018"
        },
        {
            "lei": "1",
            "name": "Bak 1",
            "period": "2016"
        }
    ]
}
```

**Comment by kgudel** [comment]
First part addressed in #2562 which will close #2574

**Comment by awolfe76** [comment]
@kgudel - let's ignore the `/filers` endpoint for now.

We'll still need `/filers/<period>/<lei>/msaMds` now that #2544 is closed.

**Comment by omnipresent07** [comment]
Closed by https://github.com/cfpb/hmda-platform/pull/2612
