### ISSUE TITLE
Q617 triggering incorrectly

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#2524]
Q617 states: 
1) If Combined Loan-to-Value Ratio and Property Value are not reported NA or Exempt, then the Combined Loan-to Value Ratio generally should be greater than or equal to the Loan-to-Value Ratio (calculated as Loan Amount divided by the Property Value).

The precision of the calculated LTV should be rounded to match the precision of the CLTV before comparing the two values according to https://github.com/cfpb/hmda-platform/blob/master/hmda/src/main/scala/hmda/validation/rules/lar/quality/Q617.scala.  

Take a calculated LTV of 75.4025 (loan amount = 15080.5 /property value = 20000). If we round these to the same precision as the CLTV (no decimal places) then it becomes 75 which is equal to the CLTV values entered and should not trigger Q617.  However, on the submission portal, Q617 is being triggered for these scenarios.

**Expected behavior:** If the FI reports 75 for CLTV, then property value/loan amount calculation of 75.4025 should have rounded down to 75 and should not flag. Same thing would be true if they reported 75.4 in CLTV, the calculation should round 75.4025 to 75.4 and not flag. However, if the calculation was 75.4625, and the FI reported 75.4 in CLTV, the platform would round an LTV of 75.4625 to 75.5 and the edit would flag. The platform should be mimicking the rounding of CLTV in its calculation of LTV and then flagging.

**Comment by kgudel** [comment]
This issue is being triggered by whole numbers (50) being given a floating decimal place (they become 50.0) on parsing. This tricks the system into believing that a greater level of precision is being reported than what is. The simplest fix for this is to check in the edit if an empty floating decimal place exists rather than change parser behavior.
