### ISSUE TITLE
Identify rules for delimited file input

### ISSUE THREAD

**Issue by ericspry** [cfpb/hmda-platform#253]
The pipe-delimited HMDA file input should be described, such as with CSV, as to escape characters, strings, etc. Identify the rules for file input and any implementation requirements for parsing.

Following the structure of the [RFC 4180 standard](https://www.ietf.org/rfc/rfc4180.txt) should we require the following standards for a pipe delimited HMDA file:
1. Each record (a LAR or Transmittal sheet) is located on a separate line, ending with a line break (CRLF). 
2. The last record in the HMDA file may or may not have an ending line break.
3. A header row is NOT allowed. The structure and order of headers is determined by the HMDA file spec. The first row is always a Transmittal sheet record, all following rows are LARs. 
4. Fields are delimited with a pipe "|" character. Each line should contain the same number of fields throughout the file, according to the HMDA file spec.  Spaces are considered part of a field and should not be ignored.  The last field in each record must not be followed by a pipe. 
5.  Fields, such as character strings, should NOT be surrounded by quotes. Number and string types are presented in the same manner.
6. Fields should NOT contain line feeds or carriage returns. 
7. Special characters in fields, such as pipe characters not to be considered a delimiter, are escaped with a backslash "\" .
8. The MIME type of the file should be text and character set is US-ASCII. 

How can we improve the above and add additional clarity?

**Comment by ericspry** [comment]
On escape characters:  via https://en.wikipedia.org/wiki/Comma-separated_values
CSV is a delimited text file that uses a comma to separate values (many implementations of CSV import/export tools allow other separators to be used). Simple CSV implementations may prohibit field values that contain a comma or other special characters such as newlines. More sophisticated CSV implementations permit them, often by requiring " (double quote) characters around values that contain reserved characters (such as commas, double quotes, or less commonly, newlines). Embedded double quote characters may then be represented by a pair of consecutive double quotes,[10] or by prefixing an escape character such as a backslash (for example in Sybase Central).

**Comment by jmarin** [comment]
@ericspry Since the file spec has already been published and out in the wild for a while, is it ok to close this one?
