### ISSUE TITLE
Additional data needed for edit check process

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-platform#254]
Some of the edits require outside data sources to check. Here is a list of data that we will need to obtain to validate certain edits:
-  [ ] Geography information (valid combinations) - census tract, county, state, MSA/MD, small county flag
-  [ ] MD to MSA crosswalk
-  [ ] CRA filers

Internally as part of the panel process, we will also need these datasets:
-  [ ] Panel (institution information - parent, address, agency code and respondent id)
-  [ ] Branches (list of MSAs with branches by institution)
-  [ ] Prior year data

**Comment by debseidner** [comment]
CRA panel (transmittal sheet) can be found at http://www.ffiec.gov/cra/craflatfiles.htm

**Comment by debseidner** [comment]
A small county for HMDA is one that has a population of less than 30K

**Comment by debseidner** [comment]
FRB posts which MSAs they use for a particular filing year here - https://geomap.ffiec.gov/FFIECGeocMap/CensusUpdates.html. For 2014 and 2015 HMDA data, FRB used 2013 MSAs. For 2016, they are using 2015 MSAs. Census tracts and counties change with the decennial census so have not been updated since the last decennial census.

**Comment by debseidner** [comment]
Prior year data - Do we use 2014 or 2015 data? Most of the test data is a compilation between the two datasets so might even be beneficial to use 2013.

**Comment by debseidner** [comment]
Micropolitan Statistical Areas and Combined Statistical Areas are not used for HMDA reporting (https://www.ffiec.gov/hmda/geocode.htm).

The Edits Doc from the FFIEC also clarifies the micropolitan statistical area further.

**For the State/County/Census Tract combination, a reported census tract will always be verified. This combination is used when the property is located in a Micropolitan Statistical Area and the institution meets all the reporting criteria and is thus required to report all mortgage lending activity. (NA will always be reported in the MSA/MD column because HMDA does not use Micropolitan Statistical Area numbers). In addition, where the county is classified as small it is acceptable for a lender to code census tracts on properties in small counties as NA on the HMDA-LAR form. (If MSA/MD is reported using the valid metropolitan statistical area or metropolitan division (as appropriate) number, then all other property fields must be coded with the valid state/county/census tract combination.)

Note, however, that if you are a bank or savings association that is also required to report CRA data, you must fully geocode the property location on your HMDA data. NA is not valid except in those cases where the property is located in a Micropolitan Statistical Area or is not located in any Metropolitan or Micropolitan Statistical Area; and in those examples, NA would only be reported in the MSA/MD column and the appropriate state, county, and census tract numbers would be reported.

**Comment by debseidner** [comment]
@jmarin I finished researching the submission of 99999 for the MSA field comment from an FI during Pilot for micropolitan statistical areas and this is not the guidance that FRB gives. FIs are supposed to submit the LAR with NA for micropolitan statistical area just as the edits document states. I checked the data from 2012 forward and this is what the data supports as well. There are no '99999' MSAs submitted on the LARs, the micropolitan statistical codes from the Census CBSA files are also not appearing in LARs and the census tracts that fit into these micropolitan statistical areas are showing up with NA in the corresponding MSA fields so it definitely appears that the micropolitan statistical area LARs are being submitted with N/A.

**Comment by jmarin** [comment]
@debseidner Thanks for checking in on this. So it looks like we need not worry about that use case

**Comment by debseidner** [comment]
@jmarin We only need to make sure that we don't have micropolitan CBSA codes in our valid values for MSA/MD.

**Comment by debseidner** [comment]
For 2018, we will probably need to add a feed from the organization that manages Legal Entity Identifier (LEI - https://www.gleif.org/). This will most likely be important for panel and security in addition to the edits. 

Important information that we may want to obtain:

- [ ] Parent Information
- [ ] Institution Legal Address
- [ ] Parent/Top Holder Information
