### ISSUE TITLE
Generate 2019 Disclosure Report (Applications by Tract)

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#2543]
"DISPOSITION OF LOAN APPLICATIONS, BY LOCATION OF PROPERTY AND TYPE OF LOAN"

**Applications by Tract table needs to include the 2018 data disclosure rules require that loan amount be binned to midpoint for the $10,000 interval into which the value falls (i.e. loans between $10,000 and $19,999.99 are binned to $15,000).** See https://github.com/cfpb/hmda-platform/issues/2485

## Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

`lei`
`institution_name`
`table:` "Applications by Census Tract"
`type:` "Disclosure"
`desc:` "Disposition of loan applications, by location of property and type of loan"
`year` "2018"
`report-date`
`msa`

2017 Report example: https://ffiec.cfpb.gov/data-publication/disclosure-reports/2017/3870679/24420/1

## Overall table filters
•	Breaks down the Action Taken type by State-County-Tract Number
•	Subtotaled by Action Taken Type 1, 2, 3, 4, 5

## Census Tract Categorization
•	State/County/Tract Number

## Dispositions
This table includes the following dispositions:

**Loan Type** - These make up the 7 columns in the report. Report Number of records & aggregated loan amount
•	FHA, FSA/RHS & VA (A):  Total Units = 1 through 4; Purpose of Loan = 1; Loan Type = 2, 3, 4
•	Conventional (B): Total Units = 1 through 4; Purpose of Loan = 1; Loan Type = 1
•	Refinancings (C):  Total Units = 1 through 4; Purpose of Loan = 31, 32
•	Home Improvement Loans (D): Total Units = 1 through 4; Purpose of Loan = 2
•	Loans on Dwellings For 5 or More Families (E): Total Units = 5+ Units
•	Nonoccupant Loans from Columns A, B, C ,& D (F): All loans from columns A through D where Occupancy Type = 2, 3
•	Loans On Manufactured Home Dwellings From Columns A, B, C & D (G): All loans from columns A through D where Construction Method = 2

(A), (B), (C), (D) = Categorized as Loans on 1-to-4 Family and Manufactured Home Dwellings
(A), (B) = Sub-categorized as Home Purchase Loans

**Action Taken**
•	Applications Received: Action Taken = 1, 2, 3, 4, and 5
•	Loans Originated: Action Taken = 1
•	Applications Approved but not Accepted: Action Taken = 2
•	Applications Denied by Financial Institution: Action Taken = 3
•	Applications Withdrawn by Applicant: Action Taken = 4
•	File Closed for Incompleteness: Action Taken = 5

## Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

**Comment by omnipresent07** [comment]
It seems last year we had a CSV file using which we grab a county name base don `msamd`, `state`, and `county` i.e. `30300, 53, 003` https://github.com/cfpb/hmda-platform/blob/v1.30.x/census/src/main/resources/jul_2015_cbsa.csv 

Can we use the same csv file this year or do we need an updated file?

**Comment by keileyo** [comment]
We should use the delineation file from August 2017 for data collected in 2018: https://www.census.gov/geographies/reference-files/time-series/demo/metro-micro/delineation-files.html

File download: https://www2.census.gov/programs-surveys/metro-micro/geographies/reference-files/2017/delineation-files/list1.xls

**Comment by omnipresent07** [comment]
@keileyo @chynnakeys Disclosure reports for Bank1 5k row have been generated and are available at the following URL: https://s3.amazonaws.com/cfpb-hmda-public/{env}/reports/disclosure/2018/{lei}/{msa}/1.json (or 2.json)

@wpears [Report.jsx](https://github.com/cfpb/hmda-pub-ui/blob/1359e073094d655366f4b891084e7d003f80d793/src/reports/Report.jsx#L123) Will need to be modified based on the above URL

**Comment by keileyo** [comment]
Table 2 is relevant only for institutions that purchase loans (tend to be the larger institutions). For institutions that don't purchase loans (no records with Action Taken = 6), we want the Table 2 response to mirror the 2017 Table 2 Response. See: https://ffiec.cfpb.gov/data-publication/disclosure-reports/2017/546991/28140/2

**Comment by wpears** [comment]
Looks like Table 2 in this year's data has a different json structure that the front-end expects:

last year:
```
{
...,
"tracts": [
    {
      "tract": "CA/San Joaquin County/0052.07",
      "values": [
        {
          "dispositionName": "FHA, FSA/RHS & VA (A)",
          "count": 0,
          "value": 0
        },
        {
          "dispositionName": "Conventional (B)",
          "count": 1,
          "value": 221
        },
         ...
      ]
    },
    ...
  ]
}
```

this year:
```
{
...,
"tracts": [
    {
      "tract": "Massachusetts/Essex County/221700",
      "dispositions": [
        {
          "title": "Purchased Loans",
          "values": [
            {
              "dispositionName": "FHA, FSA/RHS & VA (A)",
              "count": 0,
              "value": 0
            },
            {
              "dispositionName": "Conventional (B)",
              "count": 0,
              "value": 0
            },
            ...
          ]
      }
    ]
  },
  ...
  ]
}
```

**Comment by omnipresent07** [comment]
@wpears Can the front end be updated to match the format for 2018? Table 1 format and Table 2 format are identical. If it is a big lift on the front end to match table 2 format to table 1, we can change it on the backend.

**Comment by keileyo** [comment]
@omnipresent07 

@chynnakeys and i just checked the 5k bank 0 file against the Table 1 disclosure report. The disclosure report is showing a single application in tract 35003976400, disposition is `file closed for incompleteness` with a loan amount of `$215,000`. The bank 0 test file actually has 50 loans in that tract. All of them are `file closed for incompleteness` and all of them have a loan amount that rounds to `$215,000` so it seems like that part is correct, but the disclosure report isn't aggregating properly, as it should show 50 loans for a total of $10,750,000

One other thing to note - the A&D tables column header that indicates dollar amount is `$000's` I think that should be changed to `$ amount` if we are reporting the whole dollar amount, not rounded to thousands (i.e. `$000's` for a loan of $215,000 indicates a value 215 not 215000 - this is leftover from previous HMDA reporting).

**Comment by omnipresent07** [comment]
@keileyo @chynnakeys 
The Table 1 and Table 2 disclosure reports were ran for Bank1 with 5k rows not for Bank0. The reports for Bank0 were ran with 10 rows. I have now also ran Bank0 5k reports and the `file closed for incompleteness` is showing `10750000` for tract `976400`. Can you please once more validate Bank0 and Bank1. Both have now been ran with 5k rows. 

@wpears the `$000's` table header should be changed to `$ amount` as @keileyo suggested

**Comment by wpears** [comment]
I'll update the headers.

Regarding the Table 2, I think it would be about an equal lift to fix it on the front-end versus the backend, but I'd say it would be preferable to fix it on the backend in case anyone is depending on the current structure in their own custom code (unlikely, but possible).

Are all the report structures identical except for this one table? If so, I think that would add further credence to fixing it on the backend to maintain consistency.

**Comment by keileyo** [comment]
@omnipresent07 instead of using Table 1 or Table A, just use "Applications by Tract" for this report, and instead of Table 2 or Table B, just use "Loans Purchased by Tract." @wpears is making the same changes on the front end so that the tables will render correctly.

**Comment by chynnakeys** [comment]
@omnipresent07 during the review of the disclosure reports, I noticed a few discrepancies using the Bank 0 5K test file: 

## Applications by Tract Table
- If no loan data has been reported for columns A-D, there should be no loan data reported in columns F & G. I have updated this in the ticket with _"All loans from columns A through D"_ 
Example: MSA 12260


## Loans Purchased by Tract Table
- Loans On Manufactured Home Dwellings From Columns A, B, C, & D in MSA 49340 should only populate if Construction Method = 2. All loans in this MSA have a construction method of 1, but they are being reported in this column.

**Comment by omnipresent07** [comment]
Both the reports have been regenerated for Bank 0. Please review.
