### ISSUE TITLE
Change to census and modified-lar

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#2544]
In order to prepare for the disclosure reports we will need to:

- [x] Create new PG table mimicking the output for modified-lar + 6 census fields + MSA Flag + Additional Flag + submission Id
- [x] Change census microservice to return all data as large json output
- [x] Change modified lar so it calls census microservice at startup time and stores all census information in memory
- [x] Change modified lar so it pushes to the newly created PG table with information from Census

**Comment by keileyo** [comment]
@omnipresent07 for the first one, i think its just adding the relevant MSA/MD code for the record (pretty sure this is what you meant by MSA Flag) but just clarifying.

**Comment by omnipresent07** [comment]
The remaining flag is to be implemented in https://github.com/cfpb/hmda-platform/issues/2573
