### ISSUE TITLE
Request CRA filing status at FI information verification

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-platform#255]
Reg C requires CRA filers to provide MSA information in their HMDA filings. We should consider adding a question at the beginning of the filing process as FIs are updating their information for the year or registering for our submission system that asks whether the financial institution is a CRA filer. 

Background on Reg:
1003 Appendix A - current rule
6. Data Reporting for Banks and Savings Associations Required To Report Data on Small Business, Small Farm, and Community Development Lending Under the CRA Regulations.—If your institution is a bank or savings association that is required to report data under the regulations that implement the CRA, you must enter the property location on your HMDA/LAR even if the property is outside the MSAs or MDs in which you have a home or branch office, or is not located in any MSA.

1003.4(e) - new rule
e. Data reporting for banks and savings associations that are required to report data on small business, small farm, and community development lending under CRA.
Banks and savings associations that are required to report data on small business, small farm, and community development lending under regulations that implement the Community Reinvestment Act of 1977 (12 U.S.C. 2901 et seq.) shall also collect the information required by paragraph 4(a)(9) of this section for property located outside MSAs and MDs in which the institution has a home or branch office, or outside any MSA.

**Comment by ericspry** [comment]
This is great. So the workflow here for the filer would be to self-identify as a CRA filer, which would inform edits that are CRA specific.  @debseidner can you list the edits that are CRA specific?

**Comment by debseidner** [comment]
The edit that CRA filer status is important for is #248, which checks to see that MSA/MD, state, county, census tract are a valid combination and not NA for all LARs.

**Comment by Kibrael** [comment]
We will use CRA Panel or associated construction logic in place of self identification.
