### ISSUE TITLE
Q634 possible bug - edit description does not agree with the implementation

### ISSUE THREAD

**Issue by charandas** [cfpb/hmda-platform#2550]
For Q634, the edit description suggests, if more than 25 originated loans are reported with loan purpose of 1, then:

```
(#Originated Purchased) / (#Purchased) < 95%
```

But the implementation ends up using [loanOriginated](https://github.com/cfpb/hmda-platform/blob/master/hmda/src/main/scala/hmda/validation/filing/MacroValidationFlow.scala#L172-L175) in denominator over [here](https://github.com/cfpb/hmda-platform/blob/master/hmda/src/main/scala/hmda/validation/filing/MacroValidationFlow.scala#L95), which is more like `(# Originated Purchased) / (# Originated) < 95%`.

There is either a bug, or edit description would need to change. Can you shed some light on this?

/cc @keileyo

**Comment by keileyo** [comment]
We will look into this - its a legacy edit that we inherited when we took over collection in 2017 and attempted to keep the implementation the same as it had been prior to our collecting the data. @Kibrael do we know how this edit was implemented in 2016 & prior?

**Comment by Kibrael** [comment]
Looking back at the old edit documentation from [2017](https://www.consumerfinance.gov/data-research/hmda/static/for-filers/2017/2017-hmda-fig.pdf) and [2016](https://www.ffiec.gov/hmda/pdf/edit2016.pdf), it looks to me like the test is:

For filers with >25 originated home purchase loans (action taken type = 1, loan purpose = 1):
- are home purchase originations >95% of all home purchase applications

count of records where action taken type = 1, loan purpose = 1 / count of records where loan purpose = 1

**Comment by PatrickHSI** [comment]
@kgudel  here's a test file to trigger this operation for testing. 
[Bank1_100_q634.txt](https://github.com/cfpb/hmda-platform/files/3768818/Bank1_100_q634.txt)
