### ISSUE TITLE
Q600 & Case sensitivity 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#2561]
Q600 should flag regardless if the ULI is duplicated regardless of case sensitivity.  Two records reported in the format below should flag Q600 which is not currently happening. 
ABCDEFGHIJ0123456789
abcdefghij0123456789

**Comment by omnipresent07** [comment]
Is there a sample file for this? From [the code](https://github.com/cfpb/hmda-platform/blob/master/hmda/src/main/scala/hmda/persistence/submission/HmdaValidationError.scala#L448) it seems that we're ignoring case while determining the duplicate ULI. 

The attached sample file with `bank1leifortest1234550gm9pi5ob838ujcr7bsgtf72` duplicate ULI triggers Q600
[clean_file_10_rows_Bank1_syntax_validity.txt](https://github.com/cfpb/hmda-platform/files/2882887/clean_file_10_rows_Bank1_syntax_validity.txt)

**Comment by keileyo** [comment]
yeah i think thats right, im going to close this.
