### ISSUE TITLE
Rename "Rule" implicit class?

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#258]
Up for discussion. See [this comment](https://github.com/cfpb/hmda-platform/pull/89#discussion_r56438023) for context.

We (@lgdean and I) want to suggest `Subject` as a possible new name for the `Rule` implicit class.
Our rationale: In the English sentence "X is numeric", X is the subject of the sentence.

(The reason we think this would be especially valuable is that we were envisioning a refactor where each edit check (e.g. `S010`, `s013`, etc) could inherit from a common class. `Rule` would be a logical name for this class. This could be a separate discussion.)

**Comment by lgdean** [comment]
I am closing this because it seems like there isn't much more discussion to be had at this time.
