### ISSUE TITLE
Q615 - edit language seems incomplete with regards to 0 being with NA/Exempt

### ISSUE THREAD

**Issue by charandas** [cfpb/hmda-platform#2581]
Hi there,

For Q615-1 and Q615-2, it is not clear from [description](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018%20Edit%20Descriptions.txt#L245-L246) (or from FIG) that 0 is included in the same way as NA/Exempt.

The [implementation](https://github.com/cfpb/hmda-platform/blob/master/hmda/src/main/scala/hmda/validation/rules/lar/quality/Q615_1.scala#L23) does use 0 in that way though. Could the language be updated to reflect this?

Thanks.

**Comment by keileyo** [comment]
Yeah, we updated this recently because we did not intend for the edit to be flagged if both total loan costs and total points and fees are 0.
