### ISSUE TITLE
Filer Submission Tracking via Postgres

### ISSUE THREAD

**Issue by PatrickHSI** [cfpb/hmda-platform#2586]
Implement a new postgres table and hmda-platform behavior to track when a filer signs a submission. 

Proposed Table: 

- lei
-submission id 
- signed date

**Comment by omnipresent07** [comment]
[ ] Create table in PG with `lei, submisisonid, sign_date`
[ ] Update hmda-analytics to pull the epoch sign date from cassandra for a submisison id
[ ] Update hmda-analytics to insert records into the new PG table (without delete)
[ ] Test on dev with resetting records and 1 M file
