### ISSUE TITLE
/filers endpoint is throwing 404

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#2630]
Ensure `/v2/reporting/filers/2018/<lei>` endpoint is working on

**Comment by wpears** [comment]
@omnipresent07 the endpoint I was having trouble with was `/v2/reporting/filers/2018` and I'm getting a `400` for it with a message `"Read NULL value for ResultSet column <computed>"`

**Comment by omnipresent07** [comment]
@wpears This should now be working
