### ISSUE TITLE
Generate 2019 Aggregate Report - (Applications by Tract)

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#2637]
## Applications by Tract
 
"DISPOSITION OF LOAN APPLICATIONS, BY LOCATION OF PROPERTY AND TYPE OF LOAN"

## Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

Table A needs to include the 2018 data disclosure rules require that loan amount be binned to midpoint for the $10,000 interval into which the value falls (i.e. loans between $10,000 and $19,999.99 are binned to $15,000). See #2485

`lei`
`table:` "Applications by Tract"
`type:` "Aggregate"
`desc:` "Disposition of loan applications, by location of property and type of loan"
`year` "2018"
`report-date`
`msa`

2017 Report Example: https://ffiec.cfpb.gov/data-publication/aggregate-reports/2017/MD/47894/1

## Overall table filters
•	Breaks down the Action Taken type by State-County-Tract Number
•	Subtotaled by Action Taken Type 1, 2, 3, 4, 5

## Census Tract Categorization

•	State/County/Tract Number

## Dispositions
This table includes the following dispositions:

**Loan Type**
•	FHA, FSA/RHS & VA (A): Total Units = 1 through 4; Purpose of Loan = 1; Loan Type = 2, 3, 4
•	Conventional (B): Total Units = 1 through 4; Purpose of Loan = 1; Loan Type = 1
•	Refinancings (C): Total Units = 1 through 4; Purpose of Loan = 31, 32
•	Home Improvement Loans (D): Total Units = 1 through 4; Purpose of Loan = 2
•	Loans on Dwellings For 5 or More Families (E): 5+ Units
•	Nonoccupant Loans from Columns A, B, C ,& D (F): All loans from columns A through @ where Occupancy Type = 2, 3
•	Loans On Manufactured Home Dwellings From Columns A, B, C & D (G): Construction Method = 2

(A), (B), (C), (D) = Categorized as Loans on 1-to-4 Family and Manufactured Home Dwellings
(A), (B) = Sub-categorized as Home Purchase Loans

**Action Taken**
•	Applications Received: Action Taken = 1, 2, 3, 4, and 5
•	Loans Originated: Action Taken = 1
•	Applications Approved but not Accepted: Action Taken = 2
•	Applications Denied by Financial Institution: Action Taken = 3
•	Applications Withdrawn by Applicant: Action Taken = 4
•	File Closed for Incompleteness: Action Taken = 5

## Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

## Sample Mockup:
![aggregate - apps by tract (table A) 3-21](https://user-images.githubusercontent.com/41752348/54848762-93455a00-4cb8-11e9-9e2d-ca9ade9c632c.jpg)

**Comment by omnipresent07** [comment]
@chynnakeys The Link for 2017 example report has `% Min Pop` and `Median Income As PCT of MSA/MD Median` columns which aren't present in the sample mockup nor in the description. Can you please confirm:
 - Does the 2018 report need to have same columns as 2017 report (A to G + `% Min Pop` and `Median Income As PCT of MSA/MD Median`), if so, how should we calculate the last two columns?
- The sample mockup doesn't include `% Min Pop` and `Median Income As PCT of MSA/MD Median`, is this intentional?

**Comment by keileyo** [comment]
Yeah, we aren't doing those columns for 2018. This table should be the same format as the Applications by Tract disclosure report, but generated for all records. 

I also updated the title from Table A to Applications by Tract - we wont use A, B, C, D etc for these tables. We will just use the names of the tables - @chynnakeys can you please update the rest of the tickets?
