### ISSUE TITLE
Generate 2019 Aggregate Report (Applications by Income, Race, and Ethnicity)

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#2641]
## Applications by Income, Race, & Ethnicity: 

"Disposition of applications by income, race, and ethnicity of applicant"

Report Structure
-------------------
Data model [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

This table needs to include the 2018 data disclosure rules require that loan amount be binned to midpoint for the $10,000 interval into which the value falls (i.e. loans between $10,000 and $19,999.99 are binned to $15,000). See #2485

2017 Report Example: 
https://ffiec.cfpb.gov/data-publication/aggregate-reports/2017/MD/47894/5-1

`lei`
`table`: "Applications by Income, Race, and Ethnicity"
`type`: "Aggregate"
`desc`: "Disposition of loan applications by income, race and ethnicity of applicant"
`year`
`report-date`
`year` "2018"
`applicantincomes`

Overall table filters
---------------------
•	Breaks down Income, Race, and Ethnicity characteristics
•	Subtotaled by Action Taken Type 1, 2, 3, 4, 5, 6

Borrower Characteristic Categorization
---------------------------------------------
* [Race](https://github.com/cfpb/hmda-platform/wiki/Race-Categorization-2018-(v2))
* [Ethnicity](https://github.com/cfpb/hmda-platform/wiki/Ethnicity-Categorization---V2-2018)
* [Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

Dispositions
---------------------------------------------
This table includes the following dispositions:

**Action Taken**
- Applications Received: Action Taken = 1, 2, 3, 4, and 5
- Loans Originated: Action Taken = 1
- Applications Approved but not Accepted: Action Taken = 2
- Applications Denied by Financial Institution: Action Taken = 3
- Applications Withdrawn by Applicant: Action Taken = 4
- File Closed for Incompleteness: Action Taken = 5
- Purchased Loans: Action Taken = 6

Types of A&D Reports
---------------------------------------------
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

## Sample Mockup:
![aggregate - income, race, and ethnicity (table E) 3-21](https://user-images.githubusercontent.com/41752348/54900645-6b1d4d00-4eaa-11e9-958d-39f8493b3fc5.jpg)

**Comment by keileyo** [comment]
@chynnakeys can you remove the minority status rows from the mockup and paste this back? We aren't required to determine minority status (by statute, just race & ethnicity) so lets remove that.

**Comment by omnipresent07** [comment]
closed via #2701
