### ISSUE TITLE
Generate 2019 Aggregate Report (Reporting Financial Institutions)

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#2645]
## Reporting Financial Institutions: 
"LIST OF FINANCIAL INSTITUTIONS WHOSE DATA MAKE UP THE 2018 MSA/MD AGGREGATE REPORT"

## Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

This table needs to include the 2018 data disclosure rules require that loan amount be binned to midpoint for the $10,000 interval into which the value falls (i.e. loans between $10,000 and $19,999.99 are binned to $15,000). See #2485

`table:` "Reporting Financial Institutions"
`type:` "Aggregate"
`desc:` "LIST OF FINANCIAL INSTITUTIONS WHOSE DATA MAKE UP THE 2018 MSA/MD AGGREGATE REPORT"
`year`
`report-date`
`msa`

2017 Report Example: https://ffiec.cfpb.gov/data-publication/aggregate-reports/2017/MD/47894/i

## Overall table filters
•	Includes only institutions whose data make up the 2018 MSA/MD Aggregate Report for that MSA

## Dispositions
This table will not include any dispositions, as we will no longer distinguish between institutions who have a home or branch office in the MSA/MD and institutions who do not have a home or branch office in the MSA/MD.

## Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

## Sample Mockup: 
![aggregate - table G  3-19](https://user-images.githubusercontent.com/41752348/54927636-e9004900-4ee8-11e9-8bbd-a9958d246d42.jpg)

**Comment by omnipresent07** [comment]
Closed via https://github.com/cfpb/hmda-platform/pull/2689
