### ISSUE TITLE
Remove test banks from mLAR search

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#2656]
Exclude test banks from modified LAR search. This is applicable to all data publication products, so I'm not sure if it just makes sense to remove them from the public /filers results altogether. 

Test Bank LEIs:

BANK1LEIFORTEST12345
BANK3LEIFORTEST12345
BANK4LEIFORTEST12345
999999LE3ZOZXUS7W648
28133080042813308004
B90YWS6AFX2LGWOXJ1LD

**Comment by omnipresent07** [comment]
Add filter logic for test banks here: https://github.com/cfpb/hmda-platform/blob/master/hmda-reporting/src/main/scala/hmda/reporting/repository/InstitutionComponent.scala#L69
