### ISSUE TITLE
Change Keycloak logging theme not say test account

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-platform#2659]
![registerWithTitle](https://user-images.githubusercontent.com/13244336/55249452-76fa6d80-5222-11e9-9043-dd7596e772f0.png)

**Comment by wpears** [comment]
This was fixed ~1 month ago with https://github.com/cfpb/hmda-platform/commit/b1e15f7ed3d6ea0c6da3922d997a024875a86421 and was released in [v2.9.7](https://github.com/cfpb/hmda-platform/blob/v2.9.7/kubernetes/keycloak/theme-provider/themes/hmda/login/register.ftl).

Seems like an old release is running in prod.

@kgudel

**Comment by keileyo** [comment]
closing as this is resolved.
