### ISSUE TITLE
Create Race & Ethnicity categorization field in postgres table

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#2667]
In order to facilitate race & ethnicity aggregations for the Aggregate reports, and the ability to filter by Race & Ethnicity for the new query tool, we want to add Race & Ethnicity categorization fields to each record in the modified LAR postgres table:

Categorization rules are a WIP: 
Ethnicity Categorization: https://github.com/cfpb/hmda-platform/wiki/Ethnicity-Categorization---V2-2018

Race Categorization: https://github.com/cfpb/hmda-platform/wiki/Race-Categorization-2018-(v2)

**Comment by keileyo** [comment]
Ethnicity categorizations are complete and can now be coded: https://github.com/cfpb/hmda-platform/wiki/Ethnicity-Categorization---V2-2018

**Comment by keileyo** [comment]
Race categorizations are complete: https://github.com/cfpb/hmda-platform/wiki/Race-Categorization-2018-(v2)

**Comment by keileyo** [comment]
Sex categorization rules: https://github.com/cfpb/hmda-platform/wiki/Sex-Categorization-v2

**Comment by Kibrael** [comment]
Read through race and ethnicity logic, looks good to me.

**Comment by keileyo** [comment]
I may not have made this clear in my first comment, but the Sex categorization should be used to create a Sex categorization :)

**Comment by omnipresent07** [comment]
Closed via #2688 and #2686
