### ISSUE TITLE
Check S305 implementation

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#2682]
Several institutions currently have duplicate records in RDS Postgres and S3 files. 

Duplicates should be rejected by S305 per FIG guidelines.

Review S305 logic to ensure it is performing as expected.

For a list of duplicated ULIs by LEI please see GHE/hmda-devops/issues/1012

**Comment by keileyo** [comment]
@Kibrael S305 works as expected with all of our test files. We would need to recreate files with the specific duplicate LARs to see if we can test those.

**Comment by MichaelFurey17** [comment]
After conducting some tests I recognized no abnormalities. We can continue to monitor the issue, but S.305 works as expected.
