### ISSUE TITLE
Add .CSV file specifications for published data

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#2684]
To increase the utility, we should provide machine readable files that contain headers and datatypes for all our data publications.

These are currently provided for the dynamic dataset, but not on the snapshot page.

- [ ] Add .CSV schema files to the [static data page](https://ffiec.cfpb.gov/data-publication/snapshot-national-loan-level-dataset)
- [x] Add a [code sheet](https://s3.amazonaws.com/cfpb-hmda-public/prod/snapshot-data/2017_publicstatic_codesheet.zip) to the dynamic dataset page

**Comment by Kibrael** [comment]
See [this issue](https://github.com/cfpb/hmda-platform/issues/2687) for discussion

**Comment by MichaelFurey17** [comment]
[WIP PR](https://github.com/cfpb/HMDA_Data_Science_Kit/pull/80) available for 2018 public TS and Panel schemas.

**Comment by MichaelFurey17** [comment]
Issue had been further specified with #2758 and #2759.
