### ISSUE TITLE
Documentation for snapshot/dynamic data releases

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#2687]
@Kibrael @chynnakeys @MichaelFurey17 let's start thinking about what documentation we need to accompany the snapshot & dynamic data release.  Traditionally, this has been:
- [ ] PDF LAR, TS and Panel file specification
- [x] PDF LAR codesheet

Do we need/want anything else?

**Comment by Kibrael** [comment]
Other issues on this topic:
https://github.com/cfpb/hmda-platform/issues/2683
https://github.com/cfpb/hmda-platform/issues/2684

**Comment by MichaelFurey17** [comment]
[WIP PR](https://github.com/cfpb/HMDA_Data_Science_Kit/pull/80) available here for Public TS and Panel Schemas.

**Comment by MichaelFurey17** [comment]
Issue has been specified in #2758 and #2759
