### ISSUE TITLE
common place for generators for bad data?

### ISSUE THREAD

**Issue by lgdean** [cfpb/hmda-platform#270]
Right now we have good-LAR test data generators in `LarGenerators`, and generators for bad values scattered throughout various specs.  Do we want to put them closer to each other, or collect the bad ones somewhere?  (Further complicating things: sometimes a value is just plain bad, and sometimes it's bad depending on some other value.)

This came up in PR #268 but isn't specific to that test.

**Comment by schbetsy** [comment]
Update: We now have `BadValueUtils` that are specific to LAR Validity edit specs. It consolidates many bad value generators, but we have not retroactively gone through existing edits to extract more.

Also, this construction isn't standard for other groups of specs (e.g. TS Syntactical edits), but those groups have less need for bad value generators.
