### ISSUE TITLE
Generator Strategy

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#271]
Since the LAR Generator chooses values at random from the acceptable values for each field, it doesn't always make records that make sense. It creates some LARs that are invalid, which is now becoming an issue because we've started to implement edit checks. (I'm sure this will be an issue with Transmittal Sheets and other generated objects as well).

What's the strategy for testing with generated records? Do we...

1. update the generator so it only makes valid values? This would require adding tons of extra logic to the generators.
2. do extra work in each test to ensure that the records we test with are sufficient to pass the test? This would mean we're testing with differently generated records in each test, and not necessarily testing with valid records.
3. Something else?

**Comment by schbetsy** [comment]
This came up because the current LAR Generator makes records that don't always pass `V262`. So when I run the new `LarValidityEngine` (which I'm working on creating) with generated input, it fails.

**Comment by lgdean** [comment]
Yeah, as I recall, the idea with the LAR Generators back in #71 was to produce something parseable, but not necessarily valid in other senses.

Option 1 seems like a lot of work, and complicated.
Option 2 is what I've seen and done so far, as in [this commit implementing V375](https://github.com/lgdean/hmda-platform/commit/237bc6371c17db7189fcda2c2a4bdbc5c6851033) (which may vanish but see #160).
(This may not actually be less work than in Option 1, though, now that I've put it that way. Hm.)

**Comment by lgdean** [comment]
btw, issue #270 raises a similar question(s) about invalid LARs.

**Comment by schbetsy** [comment]
As we discussed in standup today, Option 2 is sufficient in tests for individual edits. We've already been using that strategy, and it works for individual edits because it's relatively easy to set up.

For testing engines, we discussed not using generators at all. Instead, we'll use files of records whose results we know beforehand. We will create (a) a set of valid records, and (b) sets of records that fail in expected ways.

**Comment by jmarin** [comment]
@schbetsy OK to close?

**Comment by schbetsy** [comment]
We brought up this issue in standup today, and we still support the same conclusion we made in May. Here are the notes from that discussion:

> Generators choose valid values for individual fields. However, since some edits depend on multiple fields interacting, generators don’t always produce records that pass every validation. That’s okay.
> 
> We will use generators to test individual edits, but won’t use generators to test entire engines. Since engines run many edits on each record, setting up generated records to pass every edit would be too complex. Instead, we'll use files of records whose outcomes are known.
