### ISSUE TITLE
Handling of NA Income for aggregate reports

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#2719]
Related to #2641 

@chynnakeys  @keileyo  The income field in the LAR spec can have value [`NA`](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_File_Spec_LAR.csv#L59). In this scenario, what should be the income categorized as? i.e. `<50%`, ` "50-79%"`, `"80-99%"`, `"100-119%"`, ` ">120%"`, or this type of data shouldn't be part of the report?

@kgudel Based on how we handle above, we'll need to change the logic in [`IncomeCategorization`](https://github.com/cfpb/hmda-platform/blob/master/modified-lar/src/main/scala/hmda/publication/lar/parser/IncomeCategorization.scala#L14) since it currently converts income `toDouble` without using `Option` and we get an error

**Comment by keileyo** [comment]
leave the records out of the report.
