### ISSUE TITLE
convert API documentation to a separate repository

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#2722]
Use https://github.com/lord/slate to convert [`V2 Public API Documentation`](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/api/public-api.md) to a separate repository to increase API accessibility

**Comment by PatrickHSI** [comment]
Had some trouble setting up slate but now that it's in place I believe we can start tweaking the current  api documentation to live in this slate environment. 

Slate , spits out fancy CCSS/HTML so all we should have to worry about is how we're going to host/present it to the end user.

<img width="1505" alt="Screen Shot 2019-05-13 at 5 23 07 AM" src="https://user-images.githubusercontent.com/44584592/57611965-f083bc00-7541-11e9-8c94-8e239890d2b4.png">
