### ISSUE TITLE
2019 Edits Changes Strategy 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#2743]
Develop strategy in order to handle versions of edits that exist in 2018 and are changed in 2019. 
- We do not want to just change the edit code because the edit should function as it currently does in for 2018 resubmissions and modifications should apply only to 2019 submissions and forward. 

@kgudel has some thoughts to start this discussion

**Comment by kgudel** [comment]
One option for doing this would be to create multiple edit engines such as this one: (LarEngine)[https://github.com/cfpb/hmda-platform/blob/master/hmda/src/main/scala/hmda/validation/engine/LarEngine.scala]. We could have a LarEngine2018 and LarEngine2019 and depending on what route was hit `/2018/` or `/2019/` we would run the appropriate engine on the file.

As the engine is essentially just a list of edits creating a new one with the modified edits should be simple to do.
