### ISSUE TITLE
Race Categorization Issues v2 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#2764]
After a 2nd round of testing on the Race categorization, I found the following issues:

1) Joint - there are still issues with records that should have a "Joint" categorization being assigned a minority race.  If ANY of Race of Co-Applicant: 1-5 are reported 5 (White) AND ANY of Race of Applicant: 1-5 are reported a minority race, then the record needs to be categorized as Joint. 
- Instances of Race of Applicant: 1 = 1, Race of Applicant: 2 = 5, Race of Co-Applicant: 1 = 5, all else are blank. Categorized as American Indian or Alaska Native when it should be Joint 
- Records with Race of App: 1 = 5, Race of App: 2 = Asian, Race of Co-App: 1 = 5, all else are blank. Categorized as Asian when they should be Joint. 
- Records with Race of App: 1-5 contain Asian and White codes, Race of Co-App: 1 = 5 (White). Categorized as Asian when they should be Joint
- Records with Race of App: 1 is 3, Race of App: 2 is 5, Race of Co-App 1 or 2 is 5. Categorized as Black when they should be Joint
- Same scenario as above, but swapping in the Native Hawaiian or Other Pacific Islander codes also results in a categorization of Native Hawaiian or Other Pacific Islander when they should be Joint. 

2) Other
- A record with only Asican codes in Race of App: 1-5, and Asian + Native Hawaiian codes in Race of Co-App: 1-5. Categorized as Race Not Available when it should be Asian

3) The updated instructions on the Wiki state:
IF
Co-Applicant Race: 1, 2, 3, 4 or 5 has one or more minority race (1, 2 21, 22, 23, 24, 25, 26, 27, 3, 4, 41, 42, 43, or 44)
AND
Applicant Race: 1 equals White (5)
AND
Applicant Race 2, 3, 4 and 4 are Blank
THEN
Categorize as Joint

This is not being applied correctly. A number of records have Race of Applicant: 1 =5, Race of Applicant 2-5 are blank, and Race of Co-App 1-5 contain at least one minority race. These are being categorized as "Race not Available" when it should be "Joint"

**Comment by PatrickHSI** [comment]
@chynnakeys  @keileyo  

For these rules , there doesn't seem to be any listing for `BlackOrAfricanAmerican`,`AmericanIndianOrAlaskaNative`, or `White` is this correct?

```IF

Applicant Race: 1, 2, 3, 4 and 5 contain only some combination of 2, 21, 22, 23, 24, 25, 26, 27, or 5 or blanks
AND

Co-applicant Race: 1, 2, 3, 4, or 5 does not equal White (5)
THEN

Categorize as Asian (2)
IF

Applicant Race: 1, 2, 3, 4 and 5 contain only some combination of 4, 41, 42, 43, 44, or 5 or blanks
AND

Co-applicant Race: 1, 2, 3, 4, or 5 does not equal White (5)
THEN

Categorize as Native Hawaiian or Pacific Islander```


Also 

```
White
IF

Applicant Race: 1 = 5
AND

Applicant Race: 2, 3, 4, 5 are blank
AND

Co-applicant Race: 1 = 5, 6, 7, or 8
AND

Co-applicant Race: 2, 3, 4 and 5 are blank
THEN

Categorize as White
```

What should I account for in the event in which Applicant Race: 1, 2, 3, 4 and 5 contain only some combination of White? This only handles the event winch fields 2-5 are blank

**Comment by keileyo** [comment]
@PatrickHSI you cant report white more than once in Race: 1-5, and yes the "some combination" is correct for White, Black and American Indian or Alaska Native because there are not disaggregated categories for those races (i.e. there are no specific American Indian tribes as codes 11, 12, etc) and you can only report each code once.

**Comment by keileyo** [comment]
@PatrickHSI. @chynnakeys and i will continue adding to this comment with any issues with the latest generation. 

5/22/19 findings:
- Race of Applicant: 1 is 5, Race of Co-Applicant: 1 is 5, all else are blank. Categorized as Joint, should be White.
