### ISSUE TITLE
Static & Dynamic Dataset Fields 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform#2768]
The static and dynamic datasets need to include additional fields that are part of the modified LAR table but not part of the generated modified LAR .txt files. 

1) Conforming Loan Limit Flag 
2) Derived MSA/MD 
3) 6 appended census fields 

Documentation for the static and dynamic datasets should include these fields.

**Comment by Kibrael** [comment]
All of the public LAR datasets inherit from the same data table. The Static and Dynamic LAR loan level datasets will contain the derived fields for race, sex, and ethnicity. 

This will ensure consistency with data outputs and the associated documentation which will facilitate the use and understanding of the data.
