### ISSUE TITLE
New Database Tables for 2019 in DEV

### ISSUE THREAD

**Issue by PatrickHSI** [cfpb/hmda-platform#2820]
The following tables need to be created in support of the 2019 filing season development.

- [x] institutions2019
- [x] transmittalsheet2019
- [x] loanapplicationregister2019
- [x] modifiedlar2019
- [x] submission_history2019
- [x] institutions_emails_2019

Create HMDA_BETA scehma  with the following tables

- [x] institutions2019
- [x] transmittalsheet2019
- [x] loanapplicationregister2019
- [x] institutions_emails_2019
- [x] modifiedlar2019
- [x] submission_history2019
- [x] institutions2018
- [x] transmittalsheet2018
- [x] loanapplicationregister2018
- [x] institutions_emails_2018
- [x] modifiedlar2018
- [x] submission_history2018

**Comment by omnipresent07** [comment]
@PatrickHSI For the beta schema the table names _should not_ change. We will have a different schema name, but the table names will remain the same. i.e. `loanapplicationregister2019` instead of `loanapplicationregister2019_beta`

**Comment by PatrickHSI** [comment]
@Omnipresent  Updated to reflect your comment
