### ISSUE TITLE
Perform testing on new edits

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#2830]
As new edits are created, perform testing on them to ensure that they are working correctly. Test 2018 edit behavior and 2019 behavior to make sure that both are behaving how they should.

**Comment by chynnakeys** [comment]
@BarakStout it appears that the table for edit Q645 is not displaying the loan amount or loan purpose when the edit is triggered
![image](https://user-images.githubusercontent.com/41752348/67974459-62dc7b80-fc0a-11e9-8940-2cde1561ab7b.png)

**Comment by PatrickHSI** [comment]
@chynnakeys I can fix this via the backend and the front end should adapt without any changes.

**Comment by BarakStout** [comment]
@chynnakeys should be fixed now thanks to @PatrickHSI 

<img width="1084" alt="Screen Shot 2019-11-04 at 1 01 18 PM" src="https://user-images.githubusercontent.com/34528865/68145285-771ec200-ff03-11e9-959c-0995902d2c16.png">

**Comment by omnipresent07** [comment]
@chynnakeys version v2.12.5 for backend and v2.17.0 for frontend are deployed to beta. So this ticket is no longer blocked.

**Comment by chynnakeys** [comment]
Q645 looks good inprod3 beta
