### ISSUE TITLE
Modified LARs/IRS showing up blank

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#2978]
I received an inquiry about two institutions who's modified LARs were showing up blank. I confirmed that this is the case, however upon reviewing the institutions, they have loans in their LAR on the platform. 
Institutions: 
West Michigan Credit Union (254900TJCZAM25V2WZ38) (IRS was also blank)
Get A Rate LLC (549300YTNLQPR4PKXG57)

**Comment by omnipresent07** [comment]
Linked: https://github.com/cfpb/hmda-platform/issues/2985
