### ISSUE TITLE
Add health check end point for data browser redis 

### ISSUE THREAD

**Issue by BarakStout** [cfpb/hmda-platform#2989]
We should add a health check to data browser to check redis status. Ideally it should get the first key from redis (or any key we know should be there...like AK and action_taken=1) and it will return 500 if it can't fetch data from redis...it won't fall back to the DB.

**Comment by omnipresent07** [comment]
This health check should include:
- [ ] Whether data-browser can fetch from Redis
- [ ] Whether data-browser can connect to the DB
- [ ] Whether it can query S3
