### ISSUE TITLE
Support multiple formats on single LAR validation endpoint

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#299]
As discussed on https://github.com/cfpb/hmda-platform/pull/287#issuecomment-215137769, it would be useful to support validating multiple formats (specifically pipe-delimited) in a single request.

>The only question I have at this point is with the API design itself.  Is it really useful to have a `/parse` resource?  What's the use case for just parsing?  Our _current_ use is validating the pipe-delimited format, which requires two calls to validate in this scheme.  It seems more useful to `/validate` with multiple formats.  We could do this via different `Content-Type`s (`application/json` and...`text/plain`? (there is no official mime for pipe-delimited)).  We'd probably also want a default, though not sure which that would be.

**Comment by jmarin** [comment]
Done here https://github.com/cfpb/hmda-platform/pull/516
