### ISSUE TITLE
Filing API returning incorrect submission code when quality & macro present

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform#2990]
Repro:
 - Upload a file with quality and macro edits present (say `/data/clean_test_files/bank_0/clean_file_100_rows_Bank0_syntax_validity.txt`).
 - Note that quality edits are reported
<img width="1255" alt="Screen Shot 2019-08-06 at 5 03 58 PM" src="https://user-images.githubusercontent.com/1558033/62585167-4d0a2500-b86c-11e9-95fb-d0ac4001f973.png">
- Return to `/filing/2018/institutions`
 - Note that bank0 reports that there are only macro edits (and that quality edits have been verified)
<img width="785" alt="Screen Shot 2019-08-06 at 5 02 08 PM" src="https://user-images.githubusercontent.com/1558033/62585138-28ae4880-b86c-11e9-9cec-39f0115bdb79.png">

In the submission flow, the UI has access to edits and so is using them directly to report the correct presence of quality edits. However, this is not true on the institutions page, where we only have access to the submission status code and associated message/description.

The submission status code returned as part of `/v2/filing/institutions/<lei>/filings/<filingPeriod>` should correctly report the presence of quality edits, should they exist.

**Comment by omnipresent07** [comment]
Closed in favor of #3093
