### ISSUE TITLE
Enrich loanapplicationregister table with derived and census fields

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#2994]
There are certain fields in `loanapplicationregister` that aren't part of `modifiedlar` table e.g. `uli` and `application_date`. For 2019 ensure all of these fields are being inserted into `modifiedlar` table

**Comment by ericspry** [comment]
> There are certain fields in `loanapplicationregister` that aren't part of `modifiedlar` table e.g. `uli` and `application_date`. For 2019 ensure all of these fields are being inserted into `modifiedlar` table

~~modifiedlar`` regulator lar table
