### ISSUE TITLE
Discuss building registration into the HMDA Platform

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#3053]
Currently, new filers have to head to a Salesforce form: https://hmdahelp.consumerfinance.gov/accounthelp/ in order to register their institution on the platform. 

We should discuss the feasibility of creating a registration form within the HMDA Platform.
Includes but isn't limited to: 
Having registration form available directly to end user bypassing HMDA Help
Integration with the GLEIF API to validate LEI
Validation of fields being input

**Comment by PatrickGoRaft** [comment]
@chynnakeys @omnipresent07  This ties into issue #3508 

We'll keep both in mind when we schedule the discussion for this.
