### ISSUE TITLE
qualityExists macroExist flags in /latest endpoint

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#3176]
In the `/latest` endpoint add two new flags `qualityExists` and `macroExists`. These flags will be `false` by default and only turn `true` when there are any quality of macro errors. If there are no quality of macro errors, the flags will be `false`.

**Comment by wpears** [comment]
As with https://github.com/cfpb/hmda-platform/issues/3093, these flags should be added to the SubmissionStatus.scala object, so that they're available both from `/latest` but also in the submissions array of objects at `/v2/filing/institutions/<lei>/filings/<filingPeriod>`
