### ISSUE TITLE
Data browser endpoint to fetch LEIs and Counties

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#3193]
Data-browser shall provide two new endpoints -- one for list of LEIs (with lei and name) and second for list of counties (county code and name). Need to discuss how to fetch the county name. 

These endpoints should cache the results in redis

**Comment by proratesinc** [comment]
Would love to know how this is progressing ... LEIs seem to be another layer of complexity.
County Name seems easy enough, Using FIPS
[CountyCodes.xlsx](https://github.com/cfpb/hmda-platform/files/3795181/CountyCodes.xlsx)
... the code should be easy as well, Table lookup.
FYI - https://www.nws.noaa.gov/nwr/data/SameCode.txt

**Comment by proratesinc** [comment]
Here is a screenshot of LEI and Institution names (filtered), There are 200k + records in the US.
I had some instruction from Boomberg to get this from the GLEI? site.

![Capture](https://user-images.githubusercontent.com/25375114/67995319-10e62680-fc07-11e9-9ac0-a5cff78cd4de.PNG)

see totals at bottom
