### ISSUE TITLE
Institution not displaying in "Reporting Financial Institutions" table

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#3201]
Rayne State Bank & Trust Company is an institution whose disclosure report was recedntly regenerated. See #3171. https://ffiec.cfpb.gov/data-publication/disclosure-reports/2018/549300DISOL963J03Q15/29180/1

They are now reporting that their institution is not displaying in the MSA/MD aggregate report, reporting financial institutions table. I have confirmed this and the table may need to be regenerated.   

See here: https://ffiec.cfpb.gov/data-publication/aggregate-reports/2018/LA/29180/i

**Comment by omnipresent07** [comment]
Aggregate reports are generated from the static dataset. The date of the static dataset is as of August 7th. The submission date of this institution is September 11th. This is why the data isn't included in aggregate reports.
