### ISSUE TITLE
Remove Two Edits from Quarterly Filing Platform 

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#3220]
Edits V627 and V716 should be removed/turned off from the quarterly filing platform.

**Comment by BarakStout** [comment]
Can we get a test file for this please?

**Comment by omnipresent07** [comment]
V716 is part of 2020 yearly filing (https://github.com/cfpb/hmda-platform/issues/3206) and not implemented yet so it is not part of the 2020 quarterly filing.
