### ISSUE TITLE
Make All Timestamps Line Up

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-platform#3261]
Currently different tables that include a timestamp (ts table, submission history). Currently when the timestamp is record it is the timestamp of the insertion into the table. it should be the timestamp of the submission.

**Comment by Kibrael** [comment]
In one case the Submission HIstory and TS timestamps are 6 days apart. The difference caused confusion as a filer is saying their data should be present and it is not accessible in the Enterprise systems and won't be for several more days.

**Comment by PatrickHSI** [comment]
@KennethGudel @Kibrael  This might have been an isolated incident.  I recommend we close this issue and have a discussion on it.

**Comment by PatrickHSI** [comment]
@Kibrael As we discussed, when there's a server issue that delays the PG tables from updating before the next regulator file generation. We'll run the regulator publishing job manually to minimize the wait for the updated data. 

Closing this issue. No code change needed.
