### ISSUE TITLE
Update Parser handling of special and control characters

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#3291]
Consider stripping special characters that have caused parsing errors on the platform

- [x] Carriage Returns

- [x] Pipes at the end of LAR lines, which currently causes a parsing error "110 fields provided, 110 fields expected"

- [x]  Byte order marks

- [x] New line characters

**Comment by PatrickHSI** [comment]
@chynnakeys  @Kibrael  can you provide a test files where these issues were encountered? I've handled all but the BOM issue and would like to confirm with the data that presented this problem.
