### ISSUE TITLE
Improve logic for V608

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#3298]
The ULI vs NULI logic split should be more complicated than just checking string length. Checking the string length to determine if the record has a ULI vs a NULI actually diminishes the value of the test.

Proposed:
for all records where action taken != 6 (purchased), if the first 20 characters of the ULI/NULI equal the LEI in the record then the record contains a ULI and should be tested accordingly. 

This proposal does not check conditions to check a purchased loan for ULI vs NULI.

**Comment by Kibrael** [comment]
FIG 2021 discussion.

**Comment by chynnakeys** [comment]
@Kibrael Q648 for 2020 says "If Action Taken equals 1, 2, 3, 4, 5, 7, or 8, the first
20 characters of the ULI should match the reported LEI." does this take care of the issue?

**Comment by Kibrael** [comment]
Yeah, done!
