### ISSUE TITLE
API - List of institutions for a user

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#331]
`/institutions/period/<period>` (period is being used in this case to represent a time period, year or year and quarter)

`GET` - Complete list of institutions a user can/could file for a given year.

[Example](https://github.com/cfpb/hmda-platform-ui/blob/c7590b1e6bd3243a8cd7909463ab8e2dc8c046a5/server/json/user1-institutions.json)

**Comment by jmarin** [comment]
See #412
