### ISSUE TITLE
Sanitize Institutions Email Domain List

### ISSUE THREAD

**Issue by PatrickHSI** [cfpb/hmda-platform#3318]
If a list of an institutions email domains contains extra white space characters between the comma separated values, the domain look-up endpoint wont be able to find the domain. 

i.e. 
`aaa.com, bbb.com` 

" bbb.com" will be entered into the email table vs "bbb.com" and the endpoint wont be able to find it.

**Comment by omnipresent07** [comment]
@kgudel Is this covered in the recent PR that addresses sanitization?

**Comment by PatrickHSI** [comment]
Restarting Travis CI check
