### ISSUE TITLE
Move 2017 Filers Endpoint to 2018 Platform

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-platform#3343]
Currently the public filers endpoint: `https://ffiec-api.cfpb.gov/public/filers/2017/<lei>/msaMds` which is used by `hmda-publication` for displaying disclosure reports is served from the v1-platform.

**Comment by omnipresent07** [comment]
The S3 file for 2017_filers is stored in: https://s3.amazonaws.com/cfpb-hmda-public/prod/snapshot-data/2017/2017_filers.json
