### ISSUE TITLE
API - List edits, of a single type, for a submission

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#335]
`/institutions/<institution>/submissions/period/<period>/<submission>/syntactial|validity|quality|macro`

`GET` - Edits for a given submission, of a single type.

Examples:
[syntactical](https://github.com/cfpb/hmda-platform-ui/blob/c7590b1e6bd3243a8cd7909463ab8e2dc8c046a5/server/json/syntactical.json)
[validity](https://github.com/cfpb/hmda-platform-ui/blob/c7590b1e6bd3243a8cd7909463ab8e2dc8c046a5/server/json/validity.json)
[quality](https://github.com/cfpb/hmda-platform-ui/blob/c7590b1e6bd3243a8cd7909463ab8e2dc8c046a5/server/json/validity.json)
[macro](https://github.com/cfpb/hmda-platform-ui/blob/c7590b1e6bd3243a8cd7909463ab8e2dc8c046a5/server/json/macro.json)

**Comment by schbetsy** [comment]
To clarify: is this a list of all edits (of the indicated type) that **failed** for this submission?
