### ISSUE TITLE
Validity Edit displays incorrect values

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#3414]
A HMDA Help user reached out with a question regarding the Co-Applicant or Co-Borrower, Name and Version of Credit Scoring Model value. They entered 8888, which is an incorrect value, but what is displayed is -1. 

![LAR file shows 8888](https://user-images.githubusercontent.com/41752348/72096860-05079680-3313-11ea-8c62-622ce63bec34.PNG)
![validity edit displays -1](https://user-images.githubusercontent.com/41752348/72096861-05079680-3313-11ea-9eb6-a8864b66717d.PNG)

**Comment by kgudel** [comment]
[HMDA_2019_2.txt](https://github.com/cfpb/hmda-platform/files/4047761/HMDA_2019_2.txt)
Attaching a file that triggers the error. Both `Credit Score of Co-Applicant or Co-Borrower` and `Credit Score of Applicant or Borrower` display as `-1` though `-9` is entered.
