### ISSUE TITLE
[Qrtrly] Sign endpoint 405 error

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-platform#3428]
I have previously been able to complete quarterly filings from the front-end.  Recently I've been seeing a 405 error on `GET` calls.

![hmda4-sign-405](https://user-images.githubusercontent.com/2592907/72451460-364fee80-3779-11ea-9709-99ba84b01cb1.png)

Response: HTTP method not allowed, supported methods: POST

Example path:
`/v2/filing/institutions/B90YWS6AFX2LGWOXJ1MD/filings/2020/quarter/Q3/submissions/9/sign`

This happens for both Q3 and Q1 of 2020

Q3 Test File:
[Q3_2020_BankMD-clean_file_100_rows.txt](https://github.com/cfpb/hmda-platform/files/4065996/Q3_2020_BankMD-clean_file_100_rows.txt)

**Comment by PatrickGoRaft** [comment]
Resolved via #3451
