### ISSUE TITLE
Set S3 Content-Disposition to 'attachment' for mLAR with header

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-platform#3442]
For the files in s3://cfpb-hmda-public/prod/modified-lar/2018/header/\<lei>_header.txt

Can you please update the `Content-Disposition` of these files to `attachment`?

[AWS UI](https://docs.easydigitaldownloads.com/article/1172-how-do-i-force-files-to-download-in-amazon-s3) | [AWS CLI](https://forums.aws.amazon.com/thread.jspa?messageID=677818)

When accessed from the UI the new files are loaded in the browser as plain text instead of being saved to the user's machine, as the previously files are. 

## Previous headerless files download as expected
<img width="717" alt="success-download" src="https://user-images.githubusercontent.com/2592907/72865202-2b72ed80-3c94-11ea-9144-f54734a7fd16.png">

## New headered files load as plain text
<img width="800" alt="plain-text-display" src="https://user-images.githubusercontent.com/2592907/72865207-2dd54780-3c94-11ea-985b-bb2e36c2dce7.png">

**Comment by zencircle** [comment]
AWS S3 UI --> Select Folder -> Change Metadata --> Key(Content Disposition), Value (Attachment)
- [ ] 2018
- [ ] 2017

**Comment by omnipresent07** [comment]
@zencircle the `/prod/modified-lar/2017/header/` folder exists now with files in it. Lets add content disposition to that as well similar to 2018

**Comment by meissadia** [comment]
Everything looking good from the front-end.  Thanks @omnipresent07 and @zencircle
