### ISSUE TITLE
Census file for 2020

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#3492]
Similar to a census file for 2018 and 2019, we need a census file for 2020. As part of this ticket, the LAR Engine for 2020 shall also be updated to fetch the new 2020 census file rather than it fetching the 2019 file (existing).

**Comment by Kibrael** [comment]
FFIEC Census flat files are available [here](https://www.ffiec.gov/censusapp.htm), but not usually until Fall.

For Census data handling, please see the GHE/HMDA-Operations/hmda-devops/wiki/Census-and-Demographic-Data wiki.

Code to download, parse, and trim the file is available [here](https://github.com/cfpb/hmda-census)
