### ISSUE TITLE
Q615-1 clarification request: does not trigger when both values are 0

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#3499]
@chynnakeys 

The Platform does not currently trigger if both TLC and Origination Charges = 0. However, the language in the FIG indicates that it should. 

Clarify FIG language to indicate that when both values are 0 this edit will not trigger.

**Comment by chynnakeys** [comment]
Will change language in 2020 FIG to "If Total Loan Costs and Discount Points are not reported NA or Exempt, and are both nonzero numbers, then Total Loan Costs generally should be greater than Discount Points."

**Comment by Kibrael** [comment]
moved to [HMDA Frontend](https://github.com/cfpb/hmda-frontend/issues/267)
