### ISSUE TITLE
Q648 and NULI

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#3503]
Hello, should the Q648 check ignore exempt filers using an NULI?

**Comment by chynnakeys** [comment]
@jmurphy-asurity the Q648 edit only checks ULIs, not NULIs.

**Comment by jmurphy-asurity** [comment]
Thanks for the quick response.  I don't see anything in the code that excludes NULI's, and when I submit a test file with an NULI the platform flags Q648.  Is it just not yet complete?

**Comment by PatrickGoRaft** [comment]
Being tracked here [3557](https://github.com/cfpb/hmda-platform/issues/3557)

**Comment by Kibrael** [comment]
Fixed in #3557, which is now merged.
