### ISSUE TITLE
Error with S306 & Q600 Edit table display

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#3528]
The “error: field name mismatch” shows up in a table with Q600 edits. It appears that this is because there are two ULI columns. There should only be one ULI column. 

![image](https://user-images.githubusercontent.com/41752348/76345575-fbca8400-62d9-11ea-9c96-c0479111fbbd.png)

**Comment by BarakStout** [comment]
Also in S306 

![s306edit2020q1](https://user-images.githubusercontent.com/34528865/77357842-3511e380-6d1f-11ea-88ec-45af0b40a902.png)
