### ISSUE TITLE
Remove cell separation by commas in edit reports

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#3530]
Reference issue:  https://github.com/cfpb/hmda-frontend/issues/290

**Comment by PatrickGoRaft** [comment]
@chynnakeys  could you provide a sample submission file to reproduce this issue?

**Comment by chynnakeys** [comment]
@PatrickGoRaft 
[Chynna Bank_500_q614_1.txt](https://github.com/cfpb/hmda-platform/files/4349392/Chynna.Bank_500_q614_1.txt)
