### ISSUE TITLE
Update Conforming Loan Limit Logic for 2019

### ISSUE THREAD

**Issue by PatrickGoRaft** [cfpb/hmda-platform#3531]
The conforming loan limit logic for 2019 needs to be updated.

**Comment by Kibrael** [comment]
[Is this](https://www.fhfa.gov/DataTools/Downloads/Pages/Conforming-Loan-Limits.aspx) the correct source for the data?

**Comment by Kibrael** [comment]
[FullCountyLoanLimitList2019_HERA-BASED_FINAL_FLAT.xlsx](https://github.com/cfpb/hmda-platform/files/4314778/FullCountyLoanLimitList2019_HERA-BASED_FINAL_FLAT.xlsx)
[FullCountyLoanLimitList2020_HERA-BASED_FINAL_FLAT.xlsx](https://github.com/cfpb/hmda-platform/files/4314779/FullCountyLoanLimitList2020_HERA-BASED_FINAL_FLAT.xlsx)

**Comment by kgudel** [comment]
This will also include adding the 2020 file and updating the logic to determine which set of loan limits to run the flag logic against.

**Comment by Kibrael** [comment]
[FHFA conforming limit page](https://www.fhfa.gov/DataTools/Downloads/Pages/Conforming-Loan-Limits.aspx)
[map of loan limits](https://www.fhfa.gov/DataTools/Tools/Pages/Conforming-Loan-Limits-Map.aspx)
[loan limit addendum, contains max value calc](https://www.fhfa.gov/DataTools/Downloads/Documents/Conforming-Loan-Limits/CLLAddendum_CY2020.pdf)

**Comment by Kibrael** [comment]
[addendum for 2018 HMDA data](https://www.fhfa.gov/DataTools/Downloads/Documents/Conforming-Loan-Limits/CLLAddendum_CY2019.pdf)
