### ISSUE TITLE
Add census file for 2020

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#3533]
Add Census file for 2020 yearly edits

**Comment by Kibrael** [comment]
FFIEC Census flat files are available [here](https://www.ffiec.gov/censusapp.htm), but not usually until Fall.

For Census data handling, please see the GHE/HMDA-Operations/hmda-devops/wiki/Census-and-Demographic-Data wiki.

Code to download, parse, and trim the file is available [here](https://github.com/cfpb/hmda-census)

**Comment by Kibrael** [comment]
duplicate of [this ticket](https://github.com/cfpb/hmda-platform/issues/3492)
