### ISSUE TITLE
Integrate 2017 Data in the Data Browser

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-platform#3551]
This work is in a number of components:

- Create PSQL table schema for 2017 data
- Determine if all filters are applicable to 2017 data
   - if not remove or edit filter options to applicable values for the 2017 route
- Create new route for 2017 data

**Comment by kgudel** [comment]
1. Action Taken - Same
1. Loan Type
 - code 4 `FSA/RHS-guaranteed (Farm Service Agency or Rural Housing Service)` vs `USDA Rural Housing Service or Farm Service Agency guaranteed (RHS or FSA)`
1. Loan Purpose
 - `1, 2, 3` vs `1,2,31,32,4,5`
1. Lien Status
 - `1,2,3,4` vs `1,2`
1. Construction Method
 - Not in 2017
1. Total Units
 - Not in 2017
1. Ethnicity
 - Reportedly Differently (no derived ethnicity for 2017)
1. Race
 - Reportedly Differently (no derived race for 2017)
1. Sex
 - No derived field in 2017 (no derived sex for 2017)
1. Loan Products
 - Not in 2017
1. Dwelling Categories
 - Is Property Type in 2017

**Comment by Kibrael** [comment]
Construction Method, Total Units, and potentially MF affordable units are what map to Property Type in the 2017 data.
