### ISSUE TITLE
Q653 not handling Exempt

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#3584]
The platform is flagging Q653 when the CLTV has been set to `Exempt`.  Is this the expected behavior?

**Comment by jmurphy-asurity** [comment]
FYI this same edit is flagging NA as well as Exempts.

**Comment by chynnakeys** [comment]
@jmurphy-asurity we have updated our code to not flag when the CLTV is NA or Exempt; an update to the FIG and the beta platform will be available this week.
