### ISSUE TITLE
Review Code for Exempt and NA text to check implementation

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-platform#3621]
Any field accepting `Exempt` should require that spelling and capitalization format.

Any field accepting `NA` should require that spelling and capitalization format.

**Comment by chynnakeys** [comment]
@Kibrael This is actually noted in the FIG: 
Text entries in alphanumeric fields do not need to use all uppercase letters with the exception of:
 “NA” used when the reporting requirement is not applicable;
 "A capital “E” at the beginning of any “Exempt” response. "

Perhaps this needs to be updated in the code?

**Comment by Kibrael** [comment]
Yes, I think it would be a code change or check if the FIG already contains those instructions.

**Comment by chynnakeys** [comment]
The FIG contains instructions to ensure that Exempt and NA are entered correctly. We should ensure that the code does the same.

**Comment by PatrickGoRaft** [comment]
@Kibrael  @chynnakeys  upon review  the applicable fields are checked against  the case sensitive values  "NA"  and "Exempt" via validity edits. We do not however enforce this format for alphanumeric values when parsing LARs. 

We would need to make this a code change to trigger a parsing error in cases such as "na" or "EXEMPT".
