### ISSUE TITLE
No API access to data for years other than 2018

### ISSUE THREAD

**Issue by o1lo01ol1o** [cfpb/hmda-platform#3686]
Currently

```console
curl -L "https://ffiec.cfpb.gov/v2/data-browser-api/view/csv?&states=NY&years=2018"
```
will download records from `s3`.  However, changing `years` to any other value retrieves only headers.

Are other years supported via API?  If not, can they be obtained in total from `s3` manually?

**Comment by PatrickGoRaft** [comment]
Hello @o1lo01ol1o , at the moment only 2018 data has been made available via the Data Browser API as the 2019 data has yet to be published. 

Data prior to year 2018 can be obtained via the legacy data browser application. Please refer to the data-browsers FAQ page:

https://ffiec.cfpb.gov/documentation/2018/data-browser-faq/
