### ISSUE TITLE
Conforming Loan Limit Incorrectly Calculated

### ISSUE THREAD

**Issue by ccoxtn** [cfpb/hmda-platform#3704]
The logic is reversed when calculating the Conforming Loan Limit when the state data is being used. 

As an example, here are the rules for one unit properties according to the [wiki doc](https://github.com/cfpb/hmda-platform/wiki/Derived-Fields-Categorization):

>Lien Status = 1, Total Units = 1, Reference the minimum and maximum conforming limits for the STATE for 1 unit.
If Loan Amount is <= **lowest** possible limit for the state, assign a value of C
If Loan Amount is > **highest** possible limit for the state, assign a value of NC
If loan amount > the lowest possible limit but <= highest possible limit, assign a value of U`

and here is your [code](https://github.com/cfpb/hmda-platform/blob/master/common/src/main/scala/hmda/parser/derivedFields/ConformingLoanLimit.scala#L120) 

```
if (loan.lienStatus == SecuredByFirstLien && loan.totalUnits == 1 && loan.amount <= state.oneUnitMax)
    "C"
else if (loan.lienStatus == SecuredByFirstLien && loan.totalUnits == 1 && loan.amount > state.oneUnitMin)
    "NC"
```

The correct code to match the published rules would be:
```
if (loan.lienStatus == SecuredByFirstLien && loan.totalUnits == 1 && loan.amount <= state.oneUnitMin)
    "C"
else if (loan.lienStatus == SecuredByFirstLien && loan.totalUnits == 1 && loan.amount > state.oneUnitMax)
    "NC"
```

There are similar errors in all 16 else statements for this branch of code.

**Comment by ericspry** [comment]
Hey Chris, great catch!
