### ISSUE TITLE
Q648 for NULI code/FIG mismatch

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#3721]
Q648 was updated in  #3557 to not fire on NULIs, but the FUIG was never updated to reflect this change.

**Comment by chynnakeys** [comment]
@jmurphy-asurity the FIG does not mention NULIs in the edit, because it is only targeted to trigger for ULIs.

**Comment by jmurphy-asurity** [comment]
OK, so if the FIG has a `Data Field Name` of only ``Universal Loan Identifier (ULI)` rather than `Universal Loan Identifier (ULI) or NonUniversal Loan Identifier (NULI)` we should assume that NULIs are excluded from the edit check?  Is that also true for S306?

**Comment by chynnakeys** [comment]
That is correct @jmurphy-asurity
