### ISSUE TITLE
Data Browser 2019 & 2017 Record Counts

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-platform#3722]
In order to display `Warning: This dataset may be too large to be opened in standard spreadsheet applications` on the frontend, we need to know the number of records for each State/County/MSAMD.

Please provide for both 2017 and 2019.

- county Counts: FIPS code => # records [[reference]](https://github.com/cfpb/hmda-frontend/blob/master/src/data-browser/constants/countyCounts.js)
- msamd Counts: 5 digit msamd code => # records [[reference]](https://github.com/cfpb/hmda-frontend/blob/master/src/data-browser/constants/msamdCounts.js)
- state Counts: 2 letter abbreviation => # records [[reference]](https://github.com/cfpb/hmda-frontend/blob/master/src/data-browser/constants/stateCounts.js)

**Comment by PatrickGoRaft** [comment]
@meissadia  counts  provided for both data sets. Please contact me if you have any issues with them.

**Comment by meissadia** [comment]
I've rolled up the 2017 county counts for `NA`s, so I think it's safe to close this.
