### ISSUE TITLE
Travis OpenJDK Reference Build Error

### ISSUE THREAD

**Issue by PatrickGoRaft** [cfpb/hmda-platform#3761]
Travis is currently experiencing an issue referencing the openjdk  resource. 

https://travis-ci.community/t/jdk-14-retrieval-error/9195/3

https://travis-ci.community/t/installing-java-14-fails-with-travis-setup-java-command-not-found/8626/10

**Comment by omnipresent07** [comment]
Fixed because https://jdk.java.net/ is responding now
