### ISSUE TITLE
Resolve errors with keycloak theme when upgrading to 11.0.0

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#3790]
when upgrading to 11.0.0 we see jquery related errors (image below). These are most likely because the upgrade of keycloak has a higher order for jquery than the keycloak theme. This only happens on keycloak 11.0.0 and not on 10.0.2

<img width="1451" alt="Screen Shot 2020-08-07 at 10 58 32 AM" src="https://user-images.githubusercontent.com/44377678/89658907-1d399700-d89d-11ea-99e3-d7ce269939bf.png">

**Comment by kgudel** [comment]
Closes in #3791
