### ISSUE TITLE
Review info in devops census data wiki to move to platform wiki

### ISSUE THREAD

**Issue by audayshankar** [cfpb/hmda-platform#3836]
Review: GHE/HMDA-Operations/hmda-devops/wiki/Census-and-Demographic-Data

Once reviewed, move to hmda-platform wiki or public census repo

**Comment by Kibrael** [comment]
The public wiki should contain methodology instructions for matching LAR to Census data.

**Comment by audayshankar** [comment]
Update can be found here: https://github.cfpb.gov/HMDA-Operations/hmda-devops/wiki/Census-and-Demographic-Data#methodology-used-to-map-census-to-lar-data
