### ISSUE TITLE
Create an endpoint for hmda-help to find the most recent signed submission id of a filer

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#3846]
a filer can have multiple submission ids. as a hmda-help user it would be beneficial to find out the most recent submission id of a filer.

**Comment by meissadia** [comment]
@Omnipresent On HMDA Help we use the `/v2/filing/institutions/FRONTENDTESTBANK9999/filings/2019/submissions/latest` endpoint to determine the latest submission ID is, if it exists.
