### ISSUE TITLE
review the TTL value for tag_views table

### ISSUE THREAD

**Issue by zencircle** [cfpb/hmda-platform#3863]
Currently TTL value is indefinite
https://github.com/cfpb/hmda-platform/blob/master/hmda-sql-doc/cassandra-scripts.txt#L142
Based on the events per day update the value
https://doc.akka.io/docs/akka-persistence-cassandra/current/events-by-tag.html#cleanup-of-tag-views-table

Note: 
We have seen errors while running `nodetool repair` and `nodetool sstableupgrade` and suspect tag_views data is not deleted properly

**Comment by omnipresent07** [comment]
Opened issue with Lightbend

**Comment by omnipresent07** [comment]
confirmed - if the data needs to be kept forever then the TTL must be 0 for tag_views
