### ISSUE TITLE
Transmittal Sheet (only) syntactical edit checks (2017)

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#39]
- [ ] S100 Activity Year #40 
- [ ] S013 Timestamp #41 
- [ ] S028 Timestamp #42

**Comment by lgdean** [comment]
Is there any work left on this issue that wouldn't be covered by #96, #97, and #98? We'd like to make sure we aren't stepping on your toes when we pick up those issues. (And if this one can be closed then that'd be nice too!)

**Comment by jmarin** [comment]
I don't think there is. This sort of ticket with checkboxes became unpopular once we automated the creation of GitHub issues, so it's a bit legacy. I will review tickets and close those that are already done. Thanks
