### ISSUE TITLE
Platform and Frontend dockerhub images

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#3999]
Are you planning to push new release images to Docker hub this year?  The last version I see is `v2.14.2`, from 9 months ago.  I see that `latest` is still being updated there.

**Comment by jmurphy-asurity** [comment]
I know you're all busy with submission, but are you planning on addressing this?  It's difficult for us to tell which changes are getting released.  If you aren't planning on maintaining the releases please let me know so that I can make other arrangements.

**Comment by omnipresent07** [comment]
hmda-platform v2.20.2 and hmda-fronend v1.2.12 have both been pushed to docker hub. In addition to the `latest` tag, all new releases will be pushed to Docker Hub going forward.
