### ISSUE TITLE
Exempt interestRate does not trigger Q646

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#4016]
The interestRate field is specified in the FIG as allowing the value `Exempt`.  Should it trigger a `Q646` if that value is used?  The FIG says `Your file indicates that at least one exemption code was used. Please verify that your institution is eligible for a partial exemption  pursuant to the 2018 HMDA Rule.`  Is the intention of this Q check to only trigger is a code like `1111` is used, rather than the word `Exempt`?

**Comment by chynnakeys** [comment]
fix LGTM @PatrickGoRaft
