### ISSUE TITLE
hmda-platform_kafka exit code 127

### ISSUE THREAD

**Issue by mdulog** [cfpb/hmda-platform#4037]
Hi Everyone

I am attempting to run this project using docker compose but i get an exit 127 code for the kafka container. All the other containers are up but the hmda-platform errors out because it cant connect to the container that contains kafka.

Below are the listed commands.

C:\Users\Administrator\Documents\Projects\hmda-platform> docker-compose up -d hmda-platform
Creating network "hmda-platform_default" with the default driver
Creating hmda-platform_zookeeper_1 ... done
Creating hmda-platform_cassandra_1 ... done
Creating hmda-platform_kafka_1     ... done
Creating hmda-platform_hmda-platform_1 ... done
C:\Users\Administrator\Documents\Projects\hmda-platform> docker-compose ps
            Name                           Command                State                        Ports                    
------------------------------------------------------------------------------------------------------------------------
hmda-platform_cassandra_1       docker-entrypoint.sh cassa ...   Up         7000/tcp, 7001/tcp, 7199/tcp,               
                                                                            0.0.0.0:9042->9042/tcp, 9160/tcp            
hmda-platform_hmda-platform_1   /bin/sh -c bin/hmda-platfo ...   Up         1099/tcp, 19999/tcp, 0.0.0.0:8080->8080/tcp,
                                                                            0.0.0.0:8081->8081/tcp,                     
                                                                            0.0.0.0:8082->8082/tcp, 9080/tcp            
hmda-platform_kafka_1           wait-for-it.sh zookeeper:2 ...   Exit 127                                               
hmda-platform_zookeeper_1       /bin/sh -c /usr/sbin/sshd  ...   Up         0.0.0.0:2181->2181/tcp, 22/tcp, 2888/tcp,   
                                                                            3888/tcp

**Comment by omnipresent07** [comment]
@mdulog Can you please post more details of the error logs and the images that are running on your system using `docker images` and `docker ps -a`? We've tried on our end and other open source contributors who have been able to run the hmda-platform locally on windows machine using `docker-compose up hmda-platform`. Please feel free to post to this ticket and we will open the ticket again.
