### ISSUE TITLE
V719 - meaning of *Alphanumeric*

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#4070]
For V719, does *alphanumeric* include punctuation? Financial Institution Name just has to have a character that isn't a digit?

**Comment by PatrickGoRaft** [comment]
Thank you for your inquiry @jmurphy-asurity.  This does include punctuation as defined in the code [here](https://github.com/cfpb/hmda-platform/blob/master/hmda/src/main/scala/hmda/validation/rules/ts/validity/V719.scala).
