### ISSUE TITLE
Q637 not flagging

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#4075]
I do not believe Q637 is working correctly.  The edit text says: `Q637|No more than 15% of the loans in the file should report Action Taken equals 5. Your data indicates a percentage outside of this range.|Action Taken; Total Number of Entries Contained in Submission`

If I take your clean_file_5_rows_Bank0_2020.txt file and replace the first row with the fourth row from clean_file_100_rows_Bank0_2020.txt, then I have one `Action Taken = 5` in five records.  This should flag Q637, but it doesn't.

I believe this bug exists in the current version of the platform, but I can't be certain, because I'm running the last version you published to docker hub, which is out of date.  If you guys could update the docker images that would be very helpful.

**Comment by omnipresent07** [comment]
We believe Q637 is working as expected. It is important to note that Q637 is a Macro Quality Error. If you are using the API, you will have to verify the quality step in order to see the macro edits.
