### ISSUE TITLE
Vendor filing on behalf of Institution

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#4097]
Is there currently any ability for a third party vendor to file on behalf of an Institution.  If not, is there any plan to add this ability?

**Comment by chynnakeys** [comment]
Hello @jmurphy-asurity currently vendors can test filer data on the beta platform. However, we will take your suggestion into consideration. On a related note, the CFPB is conducting testing sessions to gather feedback about HMDA APIs - is this something you would be interested in? If so, please contact me at chynna.keys@cfpb.gov. Thank you!
