### ISSUE TITLE
Create API endpoint for Activity Year

### ISSUE THREAD

**Issue by nickgrippin** [cfpb/hmda-platform#410]
We need to create an endpoint that will accept the front end call in the form `/period/<period>` (e.g. `/period/2017`).  This year will presumably need to be stored somewhere and made available to the validations.  The work for this ticket also includes changing the validations listed below to reference the stored activity year.

Current validations that require activity year:
#182
#96
#131

**Comment by hkeeler** [comment]
I'm going to piggyback on this issue as its pretty closely related. :)

If/when we merge https://github.com/cfpb/hmda-platform/pull/452#issuecomment-236234651, we'll have a place to put the _filing period_, and thus available for the above-mentioned edits ([Q022](https://github.com/cfpb/hmda-platform/issues/182), [S100](https://github.com/cfpb/hmda-platform/issues/96), [S270](https://github.com/cfpb/hmda-platform/issues/131)).

I'm envisioning something like:

**`FilingPeriod`**
```scala
case class FilingPeriod(id: String, start: LocalDate, end: LocalDate, due: LocalDate)
```
...or even...

```scala
sealed abstract class FilingPeriod(id: String, start: LocalDate, end: LocalDate)
sealed object Filing2017 extends FilingPeriod("2017", LocalDate.parse("2017-01-01"), LocalDate.parse("2017-12-31"))
```

...and then we could add this as an attribute of `ValidationContext`:

**`ValidationContext`**

```scala
case class ValidationContext(filingPeriod: FilingPeriod, Option[Institution])
```

...and _**then**_ the edits could go something like:

**`Q022`**
```scala
def apply(lar: LoanApplicationRegister, ctx: ValidationContext): Result = {
    val appDate = LocalDate.parse(lar.applicationDate, BASIC_ISO_DATE)
 
     applicationYear is between(ctx.filingPeriod.start, ctx.filingPeriod.end)
}
```
in addition, we can remove the version of `apply` that returns a `Future[Result]`.

**`S270`**
```scala
def apply(lar: LoanApplicationRegister, ctx: ValidationContext): Result = {
    var actionTakeDate = LocalDate.parse(lar.actionTakenDate, BASIC_ISO_DATE)

    actionTakenDate is between(ctx.filingPeriod.start, ctx.filingPeriod.end)
}
```

**`S100`**
```scala
def apply(ts: TransmittalSheet, ctx: ValidationContext): Result = {
    ts.activityYear is equalTo(ctx.filingDate.start.getYear)
}
```

Also, let's consider https://github.com/cfpb/hmda-platform/issues/469 when we implement this.

**Comment by lgdean** [comment]
This approach makes sense to me.
I would probably also want the `FilingPeriod` to be able to answer questions about whether a date is within it, but that level of detail can be figured out at coding time.
