### ISSUE TITLE
Filter list of institutions by user

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#412]
See #331 
The list of institutions returned needs to be filtered according to the user that is logged in. The approach that has been discussed at this point is that the list of institutions to be returned will be part of a request header

**Comment by jmarin** [comment]
See #441

**Comment by schbetsy** [comment]
I know we need to filter the institution list in the `/institutions` API response. Is this issue referring to any additional times we need to filter that list? (i.e. is there anywhere else that the system returns a list of institutions that needs to be user-specific?)
