### ISSUE TITLE
Is data for Denial Reason available from the public HMDA data browser API?

### ISSUE THREAD

**Issue by buchmayne** [cfpb/hmda-platform#4229]
I have been working on a project and using the HMDA data browser API. I've been asked to get data for "Denial Reason" and I was wondering if this data is available through the API. I reviewed the API source code, particularly this [file](https://github.com/cfpb/hmda-platform/blob/master/data-browser/src/main/scala/hmda/dataBrowser/api/DataBrowserDirectives.scala) and it doesn't seem like `Denial  Reason` is an end point. However, I am not very familiar with Scala so I wasn't certain. I am just looking to verify whether or not it is available through the API. Lastly, thanks for providing this tool for researchers!

**Comment by Kibrael** [comment]
Denial Reason is one of the data fields contained in the Loan Application Register [(LAR) dataset](https://ffiec.cfpb.gov/documentation/2021/lar-data-fields/).

Denial Reason is included in the fields available in the public release. The [HMDA Data Browser](https://ffiec.cfpb.gov/data-browser/data/2020?category=states) and [related API Docs](https://cfpb.github.io/hmda-platform/#data-browser-api) are probably what you're looking for.

**Comment by audayshankar** [comment]
Apologies for the very delayed response on this ticket, this github issue got lost in the shuffle over the years. To close the loop, here is the answer to the inquiry you posed on Oct 20, 2021:

Denial reason is not a filter available on the Data Browser API, so you will not be able to download the analysis you are looking for directly from the Data Browser. However, the analysis can still be completed if you download the subset of data you want to analyze with any geographic filters, maybe Action Taken = 3, Application Denied, or [one of the other existing filters for the data browser](https://ffiec.cfpb.gov/documentation/tools/data-browser/data-browser-filters). With the resulting dataset, you'll be able to use the data field [Denial Reason](https://ffiec.cfpb.gov/documentation/publications/loan-level-datasets/lar-data-fields#denial_reason-1), to complete the race/denial reason analysis using your own analysis software.

If you have any further HMDA related questions, please reach out to HMDAHELP@cfpb.gov for more timely assistance!
