### ISSUE TITLE
2022 Quarterly Edits: S307

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#4239]
Edit #: S307
Edit Type: Validity
Category: Transmittal Sheet
Data Fields: Calendar Quarter; Action Taken

Instructional Text for Users: Please confirm the information below and update our file accordingly.

Edit Logic: 

The HMDA File does not contain any covered loans or applications with a final action taken date in the quarter being reported. The HMDA file must contain one or more records with an action taken date in the quarter being reported.

**Comment by lchen-2101** [comment]
the description is probably not hooked up correctly:
![image](https://user-images.githubusercontent.com/73617864/142930910-12dce55b-4038-4af0-b775-3ea1a0c2c691.png)
