### ISSUE TITLE
Create a Translation of Keycloak get token Error Messages

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-platform#4294]
When using the keycloak API error messages can be vague.

We should create or find a translation of keycloak error messages to more useful user actions.

**Comment by PatrickGoRaft** [comment]
Adding to this ticket, a  stack trace gets thrown when invalid tokens are passed along with API calls. We can find a better way to catch these. 

```
 scala.UninitializedFieldError: failed to get keycloak public key                                                                                                                   ```

**Comment by kgudel** [comment]
Closing with the documentation update and opening a new ticket to address the stack trace issue.
