### ISSUE TITLE
Builds not being tagged on docker hub

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#4309]
Hello.  The most recent tag on docker hub is 2.20.6, while the most recent release here is 2.20.15.  Are you planning on pushing the releases to docker hub again?

**Comment by PatrickGoRaft** [comment]
@jmurphy-asurity  hmda/hmda-platform:v2.20.15 is available on Docker Hub. Please let me know if you have any issues accessing the image.
