### ISSUE TITLE
Research: update akka persistence cassandra plugin from 0.101 to latest (1.0.5)

### ISSUE THREAD

**Issue by lchen-2101** [cfpb/hmda-platform#4325]
We currently use version [0.101](https://github.com/cfpb/hmda-platform/blob/master/project/Version.scala#L12) of akka persistence cassandra plugin which is out of date, at this moment, the latest version is 1.05. Upgrade would bring new features/configurations, however upgrade is not straightforward, as some of the configurations have changed, e.g. enabling the plugin was called `cassandra-journal` in 0.101, it is now `akka.persistence.cassandra.journal`

**Comment by zencircle** [comment]
https://github.com/cfpb/hmda-platform/blob/master/project/Version.scala#L12

**Comment by lchen-2101** [comment]
link to migration guide: https://doc.akka.io/docs/akka-persistence-cassandra/current/migrations.html#migrating-from-0-80-to-1-0
datastax driver guide: https://github.com/datastax/java-driver/blob/4.0.0/core/src/main/resources/reference.conf#L469-L524
