### ISSUE TITLE
Add Institution Type and Parent data to Institution data model

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#438]
Once our initial Institution model in good shape, let's add institution type and parent data.  This should unblock edits [V110](https://github.com/cfpb/hmda-platform/issues/105) and [Q033](https://github.com/cfpb/hmda-platform/issues/178), which both require these data element.

This is dependent on #437.

**Comment by hkeeler** [comment]
We actually did a bit of this work on PR https://github.com/cfpb/hmda-platform/pull/452.  With that PR we do have an `InstitutionType`, each of which designated as _depository/non-depository_.  However, not all types are represented, and what we do have are all _depository_:

* Bank
* Credit Union
* Savings & Loan

We also have some [temporary types](https://github.com/cfpb/hmda-platform/pull/452/files#diff-eae408d1158c3baa5448f38605801612R24) for testing, that should be replace with real values once we know what they are.  Hopefully, a semi-final list can be compiled as part of this issue.

The following are mentioned within edits:

* Bank,
* Saving Association (same thing as S&L I believe)
* Independent Mortgage Company
* Mortgage Banking Subsidiary

Hopefully, each can be represented as an `InstitutionType`. If not, we may need another level of categorization, and/or some combination of `InstitutionType` with parent data.

As for parent institution data adding to `Institution`, it _could_ be as simple as adding a `parents: Set[Institution]` attribute.

**Comment by lgdean** [comment]
Created #534 and #563 for some miscellaneous loose ends; can now close this ticket.
