### ISSUE TITLE
Add location, branch, and CRA data to Institution data model

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#439]
In order to unblock edit [Q595](https://github.com/cfpb/hmda-platform/issues/213), we must add Metropolitan Statistical Area / Metropolitan Division (MSA/MD) data to Institution.  Edit [Q030](https://github.com/cfpb/hmda-platform/issues/248) requires this data, but also requires branch and Community Reinvestment Act (CRA) data.

If branch or CRA data proves difficult to implement, we could split this issue in two, and deal with just MSA/MD data first.

This issue is dependent on https://github.com/cfpb/hmda-platform/issues/438.

**Comment by Kibrael** [comment]
CRA data can be found here:
https://www.ffiec.gov/cra/reporter16.htm

**Comment by jmarin** [comment]
Closing, since Q595 is not being implemented
