### ISSUE TITLE
[Filing] Add Support for Secure Websockets

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-platform#4418]
This is a blocker for [#cfpb/hmda-frontend](https://github.com/cfpb/hmda-frontend/issues/591)
 
When running the Frontend/Platform locally, connections via `ws://` are successful. In the DEV, these connections are blocked by security restrictions.  Attempting `wss://` connection in DEV results in immediate failure.  
 
I've double checked the NGINX configuration and `wss://` connections are allowed in the deployed Frontend image. 
 
Description | Screenshot
---|---
When the Frontend is deployed to our DEV environment, `ws://` connections are blocked due to security restrictions | <img width="893" alt="ws-from-https" src="https://user-images.githubusercontent.com/2592907/160478651-d3469abc-372b-4120-ac13-a84d36608a26.png">
I've tried switching over to secure websockets `wss://` but the connection immediate errors out | <img width="897" alt="wss-from-https" src="https://user-images.githubusercontent.com/2592907/160478761-1437ebc4-0a9c-47de-a676-676b62cc8589.png">

**Comment by meissadia** [comment]
I've been investigating setting the authorization header as part of the websocket connection request from the Frontend but it does not appear to be supported by web browsers. 
 
Options
  - Send bearer token as a cookie https://stackoverflow.com/a/48618910
    - Pro: Might work
    - Con: Backend would need modification to look for token in an unexpected place
  - Send headers `onOpen` https://stackoverflow.com/a/59796300
    - Pro: Would allows us to securely send our auth info
    - Con: Would require adjustment on the backend to support a modified auth flow
  - Misuse the `protocol` parameter of the websocket to send the auth token https://stackoverflow.com/a/44314168
    - Pro: Simple to implement on the Frontend
    - Con: Would this be sent in the open? Is it secure?
    - Con: Backend would need modification to look for the auth token in an unexpected place 
  - Configure separate auth token generation for websocket connections https://stackoverflow.com/a/52749848
    - Pro: Might actually work
    - Con: Would require the development of a new backend service
    - Con: Complex integration needed on both ends
  - Send token as a URL parameter https://stackoverflow.com/a/42596786
    - Con: Token could be intercepted and abused

**Comment by PatrickGoRaft** [comment]
looks like we're getting an odd error with the latest tweaks to websocket code 

Looking at it from the AWS side and Java script side as I don't see an issue within the hmda-platform 

https://stackoverflow.com/a/72257868

@meissadia  had to add more verbose logging to the UI to find this hidden error :

```
 [close] event there is at least a code: 1006 along with a wasClean: false which basically just indicates that the connection died, but again, does not provide any additional context about what caused it to die. 
```

**Comment by PatrickGoRaft** [comment]
For all intents and purposes this has been implemented  and working in our deployed environments. Holding off on roll out until after filing season.
