### ISSUE TITLE
create style guide

### ISSUE THREAD

**Issue by lgdean** [cfpb/hmda-platform#442]
We discussed making a style guide. It'd be nice not to spend time in PRs [discussing](https://github.com/cfpb/hmda-platform/pull/252/files/39839fb1ada32f02ec5917b7e15534c164dc87a1#r56214852) things like capitalization when an acronym appears in a variable name. (It'd be even better to have as many as possible of these questions answered by an automated process before commit!)

It's nobody's top priority at the moment. Here are relevant links so we have them handy when it is.

* the official [Scala style guide](http://docs.scala-lang.org/style/naming-conventions.html), which addresses many questions, but not all;
* [Paypal's style guide](https://github.com/paypal/scala-style-guide), an example providing one possible answer to the acronym question;
* discussion of [Python style at CFPB](https://github.com/cfpb/back-end/issues/14), which may help remind us of relevant things to include;
* CFPB [front-end standards](https://github.com/cfpb/front-end/).

**Comment by ericspry** [comment]
This is out of scope for the HMDA Ops program.
