### ISSUE TITLE
on unexpected errors, return 500

### ISSUE THREAD

**Issue by lgdean** [cfpb/hmda-platform#443]
In #430 we had a failure that was causing an exception to be thrown, and the relevant endpoint not to return. That specific problem was fixed, but in general, it would be better to return a 500 rather than simply not giving the client any information.

May depend on #433.
May be separate pieces of work for different parts of the API.

**Comment by kgudel** [comment]
After having done some research into this, in the cases that I have tested, the route will always return in 20 seconds after, the akka default request-timeout. @lgdean do you remember anything more specific about the error?

**Comment by kgudel** [comment]
Also, @schbetsy I believe you might also remember this error?

**Comment by lgdean** [comment]
Somewhat more detail: in bug #426, an edit was failing to find the necessary geo-data file, and when that happened, the server wasn't usefully informing of an error, but was instead failing to return.  (I can't say for sure that it went on for more than 20 seconds, but I suspect so.)  This was happening with the single-LAR validation endpoint.  That particular bug was fixed, but others may occur, and hanging forever is not a good/informative way to fail in an unexpected situation.

It's possible that this behavior has changed since then, but it'd be good to check.  (And note: the code in `LarHttpApi` that looks at first glance like it might handle this case, was already there at the time of this bug.)  One approach would be to re-introduce the very same bug (locally, of course!) and see what happens.

**Comment by kgudel** [comment]
I am unable to replicate this error. If it is alright with @lgdean and @schbetsy I think it would be best to close this ticket for and come back to it if we find similar errors in the future?
