### ISSUE TITLE
State/County and tract mismatch

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#4436]
If a file contains NA for field 17 (county), and a full valid 11 digit FIPS for field 18 (tract) then no validity checks are flagged.  I think this should be flagged by V627: `If County and Census Tract are not reported NA, they must be a valid combination of information. The first five digits of the Census Tract must match the reported five-digit County FIPS code.`

**Comment by audayshankar** [comment]
V627 is flagged only when both county AND census tract is reported NA. 
Action Item: 
- Determine if V627 should be flagged if one field is NA and the other is reported with a value. 
- Investigate if there are cases in which the above is a valid input or revise edit, if needed.
