### ISSUE TITLE
FIDataCSVParser error handling

### ISSUE THREAD

**Issue by nickgrippin** [cfpb/hmda-platform#449]
Currently, `FIDataCSVParser` and the associated `FIData` object do not handle errors passed back from the parsers.  In the case of a parsing error, they should fail and return a list of errors in the appropriate format (undetermined).

**Comment by jmarin** [comment]
@nickgrippin Has this been done already?

**Comment by kgudel** [comment]
This ticket refers to [this piece of code](https://github.com/cfpb/hmda-platform/blob/master/parser/src/main/scala/hmda/parser/fi/FIDataCsvParser.scala) which ignores any lines that fail to parse and collect any that do, as opposed to the parsers themselves which do return an option with either the error or the parsed line. However, as far as I am aware this code is not actually being used yet anywhere in the codebase. And without knowing how this code is to be used it is unclear if it should be changed.

**Comment by nickgrippin** [comment]
Yeah, this is why I put this issue into a separate ticket.  @jmarin, I remember talking with you about this ticket; did we come up with a solution for how to handle parser errors here?

**Comment by nickgrippin** [comment]
Is this ticket OK to close?

Pending an answer on #611
