### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#4625]
The last release on GH and Docker is v2.3.4 released on Dec 20, 2022.  Is that really the code the production platform is running?  If not can we get an update here and on Docker hub?

**Comment by PatrickGoRaft** [comment]
Thank you for reaching to the HMDA Ops team @jmurphy-asurity , 

We've finalized the recent patches and updates( which includes   the resolution to the [Q646 Bug)](https://github.com/cfpb/hmda-platform/issues/4609) to the HMDA Platform via ,, `v2.3.5` release.  The version has been made available via Docker Hub  tagged `hmda/hmda-platform:v2.3.5`. 

The team values your input and patience.
