### ISSUE TITLE
Dev friendly docker-compose

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#464]
Update docker-compose config to make development a bit more friendly.

For example,adding a `volumes:` on the UI side to allow us to still watch for changes during development ([an example in grasshopper](https://github.com/cfpb/grasshopper/blob/master/docker-compose.yml#L38)).

**Comment by jmarin** [comment]
@awolfe76 Is this done?

**Comment by awolfe76** [comment]
Yep, good to go. Thanks!
