### ISSUE TITLE
V716 for Quarterly

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#4661]
In the `Supplemental Guide for Quarterly Filers for 2022`  it says `Reinstated edits V627 and V716 for quarterly filers`, but the 2022 and 2023 quarterly submission is not including V716.  Is this an oversight in the Guide, or in the Edits?

**Comment by audayshankar** [comment]
Thank you for your question/feedback. Edit V716 was reinstated in 2022. The edit should be appearing now in the quarterly platform for Q1.
