### ISSUE TITLE
Create Test Files for 2024

### ISSUE THREAD

**Issue by audayshankar** [cfpb/hmda-platform#4706]
Bank 1 - Abhi
- [x] V660 - https://github.com/cfpb/hmda-platform/issues/4706#issuecomment-1765455311
- [x] V665 - https://github.com/cfpb/hmda-platform/issues/4706#issuecomment-1765440340
- [x] [V662](https://github.com/cfpb/hmda-platform/issues/4700) - https://github.com/cfpb/hmda-platform/issues/4706#issuecomment-1765342515
- [x] [V667](https://github.com/cfpb/hmda-platform/issues/4702) - https://github.com/cfpb/hmda-platform/issues/4706#issuecomment-1765438896
- [x] [V720](https://github.com/cfpb/hmda-platform/issues/4701) - https://github.com/cfpb/hmda-platform/issues/4706#issuecomment-1766460054
- [x] [Q660](https://github.com/cfpb/hmda-platform/issues/4699) - https://github.com/cfpb/hmda-platform/issues/4706#issuecomment-1765467139

Bank 0 - Oso
- [ ] [V662](https://github.com/cfpb/hmda-platform/issues/4700)
- [ ] [V667](https://github.com/cfpb/hmda-platform/issues/4702)
- [ ] [V720](https://github.com/cfpb/hmda-platform/issues/4701)
- [ ] [Q660](https://github.com/cfpb/hmda-platform/issues/4699)

**Comment by audayshankar** [comment]
V662 Bank 1
[Bank 1_2024 V662-1.txt](https://github.com/cfpb/hmda-platform/files/12922310/Bank.1_2024.V662-1.txt)
[Bank 1_2024 V662-2.txt](https://github.com/cfpb/hmda-platform/files/12922311/Bank.1_2024.V662-2.txt)

Question: Is it redundant that we both V662-1 and V662-2 show up in both cases? Since the "and the reverse must be true" already covers the opposite case. Or do we have this to make the coding logic easier?
![image](https://github.com/cfpb/hmda-platform/assets/58990254/a3626331-b7e5-4cc1-8954-2621c22a1d44)

**Comment by audayshankar** [comment]
V667 Bank 1
[Bank 1_2024 V667-1.txt](https://github.com/cfpb/hmda-platform/files/12922830/Bank.1_2024.V667-1.txt)
[Bank 1_2024 V667-2.txt](https://github.com/cfpb/hmda-platform/files/12922831/Bank.1_2024.V667-2.txt)


The language for V667-1 needs to be updated to include 12, 13, 14, 15
![image](https://github.com/cfpb/hmda-platform/assets/58990254/7ae4faf8-c8f6-4e54-ac23-6b2f435419f1)

**Comment by audayshankar** [comment]
V665 needs to be coded in + language updated to include the new enumerated fields (12, 13, 14, 15) for co-applicant credit scoring model

![image](https://github.com/cfpb/hmda-platform/assets/58990254/9e49c464-77f5-4347-a035-3a090fa5b947)

**Comment by audayshankar** [comment]
The language for V660 needs to be updated to include 12, 13, 14, and 15. However, the edit is coded right because it doesn't trigger when I use 12-15. The issue is just with the language.

[Bank 1_2024 V660.txt](https://github.com/cfpb/hmda-platform/files/12922893/Bank.1_2024.V660.txt)


![image](https://github.com/cfpb/hmda-platform/assets/58990254/f9968bd7-3ced-44f8-a663-c9d02def198c)

Similar issue to V665, when Field 64 is left blank, it triggers a formatting error that displays Valid Values. The possible valid values need to be updated to include 11, 12, 13, 14, & 15.
![image](https://github.com/cfpb/hmda-platform/assets/58990254/c623b851-c3a1-4592-ab82-ea4e69105f8c)

[Bank 1_2024 V660 - Blank field test.txt](https://github.com/cfpb/hmda-platform/files/12922908/Bank.1_2024.V660.-.Blank.field.test.txt)

**Comment by audayshankar** [comment]
Changes: The edit doesn't trigger Q660-1, Q660-2, Q660-3 separately as some of our others edits do. All edits just appear under the umbrella of Q660. Can we change that or is the code all linked together? 

Q660-1 looks good - [Bank 1_2024 Q660-1.txt](https://github.com/cfpb/hmda-platform/files/12922944/Bank.1_2024.Q660-1.txt)

Q660-2 looks good - 
[Bank 1_2024 Q660-2.txt](https://github.com/cfpb/hmda-platform/files/12922968/Bank.1_2024.Q660-2.txt)

Q660-3 - It looks like a comma is triggering the edit, which I don't believe it's supposed to based off the FIG (test file: 
[Bank 1_2024 Q660-3 Comma.txt](https://github.com/cfpb/hmda-platform/files/12922996/Bank.1_2024.Q660-3.Comma.txt))

![image](https://github.com/cfpb/hmda-platform/assets/58990254/6bddad8a-4d1a-40eb-a316-0fadf7e9320b)


Does not trigger (tbd is contained within a phrase) [Bank 1_2024 Q660-3.txt](https://github.com/cfpb/hmda-platform/files/12922971/Bank.1_2024.Q660-3.txt)
Triggers - [Bank 1_2024 Q660-3 tbd.txt](https://github.com/cfpb/hmda-platform/files/12922985/Bank.1_2024.Q660-3.tbd.txt)


### Language Change for Q660

Current: Please review the Street Address length and contents of the following LAR record(s) as they should be less than 100 characters and free of special characters or phrases such as (;,&,tbd,and, ? , !, *, %, ^, @, [, ], {, } ,<,>_, +, =).

Suggested: Please review the Street Address length and contents of the following LAR record(s) as they should be less than 100 characters and free of special characters or phrases such as (;,&,tbd,and, ? , !, *, %, ^, @, [, ], {, } ,<,>_, +, =) **that may indicate an incorrect address or that multiple addresses were reported**
- I would like to get a second opinion on the above

**Comment by audayshankar** [comment]
V720-3 & V720-4: Looks good
[Bank 1_2024 v720-4.txt](https://github.com/cfpb/hmda-platform/files/12929659/Bank.1_2024.v720-4.txt)

Thought for future: Should we implement an upper limit on credit scores?

**Comment by offoaro** [comment]
Q660

Everything is looking fine for this edit

<img width="436" alt="Screenshot 2023-10-19 111315" src="https://github.com/cfpb/hmda-platform/assets/114685069/563baa33-df6a-4eec-82ba-c8fe217dffc9">
<img width="456" alt="Screenshot 2023-10-19 110849" src="https://github.com/cfpb/hmda-platform/assets/114685069/cf7647a0-9f97-4eee-aa89-21d6d7f7b2ae">

**Comment by offoaro** [comment]
V662 1 & 2 are both also being triggered, so working fine 
<img width="396" alt="Screenshot 2023-10-19 141558" src="https://github.com/cfpb/hmda-platform/assets/114685069/5e7df572-c3d0-47b6-8f0e-acaa49cf64fb">
<img width="389" alt="Screenshot 2023-10-19 141809" src="https://github.com/cfpb/hmda-platform/assets/114685069/309da756-4d86-499f-ae1e-e71dd49941f3">
[2024-4-B90YWS6AFX2LGWOXJ1LD_ 662.txt](https://github.com/cfpb/hmda-platform/files/13046274/2024-4-B90YWS6AFX2LGWOXJ1LD_.662.txt)

**Comment by offoaro** [comment]
V667 1&2 being triggered 
<img width="392" alt="Screenshot 2023-10-19 152305" src="https://github.com/cfpb/hmda-platform/assets/114685069/5a329b37-0e11-4832-b6af-53b03cb3526c">
[Bank 0_2024 Clean 3 Lines 667.txt](https://github.com/cfpb/hmda-platform/files/13046907/Bank.0_2024.Clean.3.Lines.667.txt)

**Comment by offoaro** [comment]
V720 1,2,3,&4 Are working fine as well
<img width="374" alt="Screenshot 2023-10-20 105207" src="https://github.com/cfpb/hmda-platform/assets/114685069/35975efa-8b84-4ee6-a932-38d59b7bffa8">
<img width="401" alt="Screenshot 2023-10-20 104707" src="https://github.com/cfpb/hmda-platform/assets/114685069/c6e2d8bd-c790-4e07-94dc-18db785d60da">
[2024-4-B90YWS6AFX2LGWOXJ1LD_ (v220).txt](https://github.com/cfpb/hmda-platform/files/13056263/2024-4-B90YWS6AFX2LGWOXJ1LD_.v220.txt)

**Comment by mmahmood4444** [comment]
Q660### 

All 4 edits underneath Q660 have been triggered, good! 

![image](https://github.com/cfpb/hmda-platform/assets/129897217/6693a3a9-b442-4c8e-8264-401f59c44c46)

[Q660 2024 FIG TESTING.txt](https://github.com/cfpb/hmda-platform/files/13056237/Q660.2024.FIG.TESTING.txt)

Note: When I applied only one trigger (100 character one) the language that appears looks like this:
![image](https://github.com/cfpb/hmda-platform/assets/129897217/941f7281-f294-4a04-bf78-c0671b229261)

I found this confusing for user because other edits language isn't the same. For instance:

Q660 says 

Q660-1 edit (1 found)

but then Q655 will look like this 

Q655 edit (1 found)

![image](https://github.com/cfpb/hmda-platform/assets/129897217/e3302743-c4d5-419d-875d-7c1d688af823)

Suggestion: There is a number added before the word "edit" for some and for others there isn't. This should all be the same for ALL quality edits.

**Comment by PatrickGoRaft** [comment]
> V665 needs to be coded in + language updated to include the new enumerated fields (12, 13, 14, 15) for co-applicant credit scoring model
> 
> ![image](https://user-images.githubusercontent.com/58990254/275673513-9e49c464-77f5-4347-a035-3a090fa5b947.png)
> 
> [Bank 1_2024 V665.txt](https://github.com/cfpb/hmda-platform/files/12922843/Bank.1_2024.V665.txt)
> 
> Also when I tried to test V665-1 (Credit Score of Co-Applicant or Co-Borrower must be a number, and cannot be left blank.), it looks like the valid values that show up in the Formatting Error view don't include Credit Scoring Models 11, 12, 13, 14, or 15 ![image](https://user-images.githubusercontent.com/58990254/275674479-e02c995d-0cd9-4df3-83bb-3b8a87ac7104.png)
> 
> [Bank 1_2024 V665 - Blank Field Test.txt](https://github.com/cfpb/hmda-platform/files/12922874/Bank.1_2024.V665.-.Blank.Field.Test.txt)

![Screen Shot 2023-10-23 at 2 04 23 AM](https://github.com/cfpb/hmda-platform/assets/44584592/59c487dd-f622-4895-8a00-2a7a661b7160)

**Comment by PatrickGoRaft** [comment]
@mmahmood4444 thank you for the thorough review,  to follow up on your question edits only usually have a `-#` after them if they're split into multiple sub edits. 

For Q660 there are two different rules that can trigger under it i.e. Q660-1 and Q660-2 ( some can have up to 4 sub edits) . It's better for the filer to get the granular  details of which part of the rule the LAR row triggered rather than clumping together the entire set in a message.

**Comment by mmahmood4444** [comment]
V667 Edit 1 & 2 

![image](https://github.com/cfpb/hmda-platform/assets/129897217/c26249e1-ff91-43cd-9521-7e119217b740)

Both of these edits are getting triggered with the error in the co-applicant data field. 15 is now in the language, great!
[V667 EDIT 2024 FIG .txt](https://github.com/cfpb/hmda-platform/files/13080313/V667.EDIT.2024.FIG.txt)

**Comment by mmahmood4444** [comment]
V662 Edit 

![image](https://github.com/cfpb/hmda-platform/assets/129897217/7584176b-ac54-41a1-8610-ff9ee5c950ba)
[V662 EDIT 2024 FIG.txt](https://github.com/cfpb/hmda-platform/files/13127162/V662.EDIT.2024.FIG.txt)
Looking good!

**Comment by mmahmood4444** [comment]
V720 Edit 

![image](https://github.com/cfpb/hmda-platform/assets/129897217/c091cfb3-3f6f-471f-96a8-41a0b2969c0a)
![image](https://github.com/cfpb/hmda-platform/assets/129897217/231c0a3f-cdd7-49f5-a159-da4b6ff959fb)

All edits have been triggered :)

[v720 Edit.txt](https://github.com/cfpb/hmda-platform/files/13127310/v720.Edit.txt)
