### ISSUE TITLE
Update Github Landing Page 

### ISSUE THREAD

**Issue by PatrickGoRaft** [cfpb/hmda-platform#4768]
- [ ] References to platform infrastructure diagrams 
- [ ] Remove/Updatee outdated testing badging

**Comment by victoriaatraft** [comment]
in the event that anyone needs the working file to that graphic, [it's located here](https://www.figma.com/file/Csf75wQLFjBSRZhL12vNA1/Proposal-Graphics?type=design&node-id=3010%3A1535&mode=design&t=sMdTFQwYX9Hkbplc-1)
![Uploading hmda_platform_diagram.png…]()
