### ISSUE TITLE
Prevent upload to existing submission

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#484]
Avoid uploading data to a submission that already exists and has data

**Comment by schbetsy** [comment]
This is necessary because "create a submission" and "upload a file" are two separate steps in the UI (and two separate endpoints in the API). Why is that? Why does "create a submission" have to be a basically-empty action?

**Comment by lesgou** [comment]
Initial discussions occurred in #264, to be able to record each state in case any errors cropped up.

**Comment by awolfe76** [comment]
Yes, what @lesgou said. I _think_ it was as simple as it would give us the ability to see those steps and provide feedback if necessary. 

Also [this file](https://github.com/cfpb/hmda-platform-ui/blob/master/submission-states.md) has the states as the front-end sees them today.

**Comment by schbetsy** [comment]
Thank you @lesgou for linking to the discussion (I knew we had, but I didn't know where). 
Thank you @awolfe76 for linking to the current source of truth (I'm glad to know it exists 👍 ).

**Comment by wpears** [comment]
Yeah, to echo the others, it allows us more flexibility in handling the start of the submission process without also having to worry about the chunks of data streaming in.

If the first call is to the Upload endpoint, any internal stuff needed to be done before handling the data will require that data being buffered somewhere. If the system is heavily loaded/constrained for resources this could be trouble.

More generally, the single call gives us less ability to slow the intake of data/handle the pace of the submission process as we see fit. In the same heavy-load scenario, maybe we wait to actually create the submission until we have enough resources available/until more containers are spun up to handle the request. Two endpoints allow us to do this comfortably without having to worry about holding on the the data somewhere or dropping it on the floor.

**Comment by jmarin** [comment]
Just a comment on this statement:

_If the first call is to the Upload endpoint, any internal stuff needed to be done before handling the data will require that data being buffered somewhere. If the system is heavily loaded/constrained for resources this could be trouble._

Our upload mechanism is based on the [Reactive Streams](http://www.reactive-streams.org/) standard ,which is designed to prevent this sort of problem and doesn't do arbitrary buffering, which can cause out of memory problems under sufficient load. If you haven't before, I recommend reading the section titled **"The Problem"** in that document, as well as the higher level architectural concepts in the [Reactive Manifesto](http://www.reactivemanifesto.org/). 

The behavior under load with `Akka HTTP` is that the upload itself will be slowed down by applying back pressure across the network (behaving, in essence, as a slower network connection). Sounds like magic, but it works.

**Comment by wpears** [comment]
Yeah, I was simplifying somewhat for expediency; the real system would likely *be able* to handle upload as the first action just fine in most scenarios. I think from an understanding-the-system, tracking-errors, and reducing-operational-complexity point of view, separate calls still makes sense. Also, it gives us more hooks in the front-end to be able to respond based on submission state (what if they've already filed and signed?). Being able to do that with out having to manage the upload stream I think is much nicer, even if Akka HTTP gives you the bandwidth limiting for free.

**Comment by jmarin** [comment]
@wpears We're in agreement regarding the separation of create / upload. I was just providing a bit more context on _how_ it works once it hits our backend system.
