### ISSUE TITLE
Validation (2017): V155 (Respondent E-Mail Address)

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#50]
A valid e-mail address for the institution must be provided and must be in the format of username@exampledomain.topleveldomain. The e-mail address shall not contain any spaces and must contain only one @ symbol. The e-mail address shall not contain "@.", ".@" and ".." character strings

**Comment by hkeeler** [comment]
Dupe of #103.  Closing.

**Comment by hkeeler** [comment]
Dupe of #103.  Closing.
