### ISSUE TITLE
Parse and validate single lar in one request

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#501]
Combine parse and validate functionality into one HTTP call (keeping the separate endpoints, as an additional feature). Input should be a single LAR text line in CSV format, output is a list of errors (if any)

**Comment by nickgrippin** [comment]
Should this include parameters for which validations to run, or should I assume `all`?

**Comment by jmarin** [comment]
I think it makes sense to follow the same convention as the existing validation API (accept parameters for filtering), see https://github.com/cfpb/hmda-platform/blob/master/api/src/main/scala/hmda/api/http/LarHttpApi.scala#L49
