### ISSUE TITLE
Update API doc

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#507]
#493 was merged so we should update the [API documentation](https://github.com/cfpb/hmda-platform/blob/master/Documents/API.md) to show the headers that are required.

_Came across this while trying to run docker-compose setup. It runs but I get a `Failed to load resource: the server responded with a status of 403 (Forbidden)` on the API call, which is good._

**Comment by wpears** [comment]
Also the `fid` key in the data response of `/institutions/<institution>` should be updated to `institutionId` via https://github.com/cfpb/hmda-platform/pull/506
