### ISSUE TITLE
Should the /lar/* resources require/allow authorization?

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#523]
As discussed on https://github.com/cfpb/hmda-platform/pull/515#discussion_r75381145, we need to figure out if the following resources should require or allow some form of authorization:

### `/lar/parse`
This _seems_ like this could be completely anonymous.  Is there anything in the parsing routine that deals with institution-specific data?

### `/lar/validate`
This one's a bit more interesting.  The current implementation of `/lar/validate` excludes all edits requiring institution data by passing in `ValidationContext(None)` into the various `Check`s.  In order to include these edits, you must pass in a valid `institutionId` instead, such as `ValidationContext(institutionId`).  The tricky bit is _how_?  There is no `institutionId` in the URI, and the current `CFPB-HMDA-Institutions` header allows for multiple `institutionId`s, so that's not-so-great either.

### Options

1. Do nothing, and leave these completely anonymous.  This of course means the institution-specific edits would never be run outside of full submission.
1. Use the current authorization headers.  However, this one falls down if a given user is associated with more than one institution.  Perhaps we could get the `institutionId` from the parse results, and if it's present in the header, proceed with validation.  Sounds pretty kludgy.
1. Create separate URIs for authorized and unauthorized.  The authorized could include the `institutionId` _and_ use the standard authorization headers.

I personally like option 1 and 3.

**Comment by jmarin** [comment]
I think 1 is what makes most sense, and was under the impression that we had agreed on that already (perhaps wrongly). This was never supposed to replace a full submission, even if an institution had just one LAR. It might be a good idea to make it more explicit in the documentation

**Comment by hkeeler** [comment]
I'm also fine with no. 1.  If that's the case, I think we should document which edits will be excluded when submitting against `/lar/validate`.  As of now, that'd at least be all institution-related edits ([S025](https://github.com/cfpb/hmda-platform/issues/94), [V110](https://github.com/cfpb/hmda-platform/issues/105), [Q030](https://github.com/cfpb/hmda-platform/issues/248), [Q033](https://github.com/cfpb/hmda-platform/issues/178), [Q595](https://github.com/cfpb/hmda-platform/issues/213)).
