### ISSUE TITLE
In /institutions change period to id

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#525]
On #521 I noticed the following:
```json
"filings": [
  {
    "id": "2017",
    "institutionId": "12345",
    "status": "not-started"
  },
  {
    "id": "2016",
    "institutionId": "12345",
    "status": "completed"
  }
]
```
Notice it has an `id` for the filings. What is being returned now is a `period`:
```json
{
  "period": "2017",
  "institutionId": "0",
  "status": "not-started"
}
```

**Comment by awolfe76** [comment]
We can have the conversation of `id` vs `period` here. I'm ok either way, but if forced to vote would go for what I think is the easy path and use `id` since it has been that in the docs and UI for a while.

@jmarin @wpears

**Comment by hkeeler** [comment]
Per @kgudel on https://github.com/cfpb/hmda-platform/pull/521#issuecomment-241028611:
>So I believe that returning `period` is actually more accurate than returning `ID`. Would it be acceptable to change the API docs to reflect the naming change?

I agree with this.  This really isn't the `id` of the filing, it's the `id` of the period.  We _could_ call it `periodId`, but I think it's cleaner to keep it just `period`.

Also, we may well end up with a true `filing.id` in our backed data store at some point.  I don't think it will ever need to be represented in the API, but it would be confusing to have `filing.id` mean different things in API vs. data store.

**Comment by jmarin** [comment]
+1 on keeping it as id

**Comment by awolfe76** [comment]
Based on standup, leaving it as period. This issue can be used to update the documentation.

We should also remember to keep in mind that there may be an `id` added later.
