### ISSUE TITLE
500 error on /submissions/latest API call

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#531]
When running the integration of back-end and front-end using docker-compose we noticed a `500 internal server error` on the `/institutions/0/filings/2017/submissions/latest` API call.

@wpears pointed out that this is likely due to the `/latest` not being accepted by the back-end.

~~For now, this issue is a question of whether the front-end needs to update to not use the `/latest` or if the back-end wants to update to accept it.~~

Back-end will implement. 

@cfpb/hmda-team-write

**Comment by jmarin** [comment]
Yeah, latest is not implemented. It should be quite straightforward to add I think
