### ISSUE TITLE
500 error on POST to /institutions/0/filings/2017/submissions/latest

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#535]
Based on the conversation from https://github.com/cfpb/hmda-platform/pull/533, when running the setup locally with docker-compose the `POST` to `/institutions/0/filings/2017/submissions/latest` returns a `500 Internal Server Error`.

Also, from the [API docs in the PR](https://github.com/cfpb/hmda-platform/pull/533/files#diff-853a8f52dcda495b60f31ee64a0fe01d) it doesn't look like there is a `POST` available to the `/institutions/0/filings/2017/submissions/latest` endpoint. This is probably ok. On the front-end we should be using `/institutions/<institution>/filings/<period>/submissions/<submissionId>` to upload the file.

---

#### Screenshot with request highlighted:
![screen shot 2016-08-25 at 10 40 51 am](https://cloud.githubusercontent.com/assets/2932572/17973518/c26abc04-6ab0-11e6-8887-a2c457f7b6cb.png)

---

#### File upload (changed to .txt to allow for upload, you can change it back to .csv)
[test.txt](https://github.com/cfpb/hmda-platform/files/437300/test.txt)
_this file is not formatted correctly, but a response should be returned_

---

#### Possible response?
You can see in the UI that we rendered "Error uploading file". So the 500 error was taken care of. Should there be a better way to handle this?

**Comment by nickgrippin** [comment]
@awolfe76, I'm a little confused by this issue.  It looks like `POST`ing to the endpoint returns a 500 error, but it also sounds like `POST` should not be behavior supported by the backend.  

Are you asking for a more logical response to the `POST` than a 500 error?

**Comment by awolfe76** [comment]
I think that 500 error makes sense in this case. Originally I didn't, but after looking more I saw the same thing you mention:

> It looks like POSTing to the endpoint returns a 500 error, but it also sounds like `POST` should not be behavior supported by the backend.

Was really just curious to see what others thought.

IMO, this is mostly likely going to be turned into a front-end issue ... to not `POST` to `.../latest` and instead use the endpoint already defined in the API docs.

**Comment by nickgrippin** [comment]
After talking with @jmarin,  `POST`ing to this endpoint should return a `405 Method Not Allowed` error.  For some reason, it's not.  I'll look into that and make sure the `.../latest` endpoint returns a `405`.

@awolfe76, will that resolve this issue?

**Comment by awolfe76** [comment]
It does as long as we don't want to be able to `POST` to the `/latest` endpoint and always require an `<submissionId>` there instead. I don't have a strong feeling either way.

@wpears

**Comment by awolfe76** [comment]
Any more thoughts on this? Are we working toward returning the `405` for the `POST` to `.../latest` or will be allow that?

**Comment by nickgrippin** [comment]
I'm working on making it return a `405` for this one.  That will make it match the other unsupported calls.

**Comment by awolfe76** [comment]
Thanks @nickgrippin. I'll create an issue on the front-end so we are doing a `POST` there.

**Comment by awolfe76** [comment]
Create https://github.com/cfpb/hmda-platform-ui/issues/205
