### ISSUE TITLE
Simplify edit states

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#546]
The states that __really__ need to be captured in the application for validation are: 

* Validating
* Validated
* Validated with errors

**Comment by awolfe76** [comment]
👍  ... as part of this lets create a `submission-states.md` file here that the front-end can reference. Right now [this doc](https://github.com/cfpb/hmda-platform-ui/blob/master/submission-states.md) is in the front-end repo but we'll remove it when this is ready.
