### ISSUE TITLE
Add ParsedWithErrors to Parser persistence

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#552]
When a parsing fails, `HmdaFileParser` should create a `ParsedWithErrors` event and publish it to the event stream

**Comment by schbetsy** [comment]
The validation actor set a precedent where, when it completes with errors, it publishes an event to the event stream called `ValidationCompletedWithErrors`, then the event processor updates the submission  status to `ValidatedWithErrors`.

To follow that pattern in the parser, I'll publish an event called `ParsingCompletedWithErrors` and update submission status to `ParsedWithErrors`.
