### ISSUE TITLE
add year to ValidationContext

### ISSUE THREAD

**Issue by lgdean** [cfpb/hmda-platform#563]
Add filing year to `ValidationContext`, now that it exists.  That way, edits that need it can get it that way.

We could perhaps also put the "timestamp" needed for S013 in there.  That one is puzzling because it's still not clear (at least to me) what it means, but the meaning is probably separate from the question of how to pass the information into the edit.  In any case, if it's blocked, then it doesn't need to be part of this ticket.  But if it's easy to go ahead and include, then we might as well.

**Comment by lgdean** [comment]
Hm. I see now that PR #560 has removed `TsValidationApi`, which was the previous (placeholder) way of passing this information around.

**Comment by jmarin** [comment]
See #96
