### ISSUE TITLE
Document required aggregations for macro quality edits

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#565]
Macro edits require information about the whole submission. For instance, many compare data to the total number of LARs in the submission. Review edits and document if there are any other data points that should be processed and included in a lookup structure or database.

**Comment by kgudel** [comment]
This is currently closed with the attached document, but can be re-opened if more information is required. Will update with the files location if necessary.
[Macro_Aggregation.docx](https://github.com/cfpb/hmda-platform/files/480473/Macro_Aggregation.docx)
.
