### ISSUE TITLE
Update /institutions/<institution>endpoint

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#600]
From standup discussion we talked about making the "status" endpoints consistent.

The `/institutions/<institution>` endpoint currently returns a filing array:

```json
"filings": [
    {
      "period": "2017",
      "institutionId": "12345",
      "status": "not-started"
    },
    {
      "period": "2016",
      "institutionId": "12345",
      "status": "completed"
    }
]
```

It should probably return something like

```json
"filings": [
    {
        "period": "2017",
        "institutionId": "12345",
        "status": {
            "code": 1,
            "message": "not-started"
        }
    },
    {
        "period": "2016",
        "institutionId": "12345",
        "status": {
            "code": 2,
            "message": "in-progess"
        }
    }
]
```

to be more like the `/institutions/<institution>/filings/<period>/submissions/latest` endpoint. With the codes and messages being:
- `1` - `not-started`
- `2` - `in-progress`
- `3` - `cancelled`
- `4` - `completed`

__Note__: I'm not sure of the order of codes or the exact messages.

**Comment by awolfe76** [comment]
Quick question, does the idea of `cancelled` seem better for the filing or for the submission? Seems like the submission is what gets cancelled, not the filing. I don't think they would cancel a filing ever, that would mean that they weren't required to file. Right?

If that is right we'll have to create an issue to add the `cancelled` state to the `/institutions/<institution>/filings/<period>/submissions` endpoint.

**Comment by jmarin** [comment]
Yeah, I agree that `cancelled` probably doesn't belong in `filings`. I'm not even sure what action triggers a cancellation in submissions either. Is this something that the user would do?

**Comment by awolfe76** [comment]
We have talked about the idea of a "Cancel Submission" button, but haven't implemented anything for it. Its a nice-to-have feature so at this point I think its ok to hold off it that for a bit and wait until later to implement. Just my opinion.

Another thing that could be called a cancellation maybe when the submit that first time and it has errors (or even without errors) and they choose to re-submit again. That first submission could be considered `cancelled`. Maybe we can call is something else or provide a message saying `Cancelled by resubmission`, but I think it works.

**Comment by awolfe76** [comment]
Due to #604 removing the `/institutions/<institution>/summary` this issue should apply to `/institutions/<institution>`. I've updated the title and comment.

**Comment by debseidner** [comment]
@awolfe76 @jmarin I have seen submissions show up in the current data file and then be cancelled the following time we download the data (i.e. have rows with enddate is null in the sql server and then have enddate filled in by a date the following month). I think it is the case that a financial institution sends in a filing and then are told that they don't have to file by the Board. The reason in the case I saw last is that the institution only reported purchases and if the institution doesn't originate any loans itself, it does not need to file. But, this happens VERY infrequently.

**Comment by awolfe76** [comment]
Thanks @debseidner. Looks like both of those are a good reason to have a "cancel" button. Wonder if we should ask for a reason too? Not really required, but might be good to know.

**Comment by debseidner** [comment]
I think it would definitely be cool to know but I am not sure we can. I think @lesgou got some guidance on asking about reasons. Not sure if this would be covered in that or not but looping her in.

**Comment by lesgou** [comment]
Don't think it would be allowed

**Comment by awolfe76** [comment]
Sounds good. I'll create a few issues around creating an endpoint for this and adding something to the UI. Thanks @lesgou and @debseidner.
