### ISSUE TITLE
Return Transmittal Sheet edits in `/edits` API endpoint

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#606]
Depends on #605

**Comment by awolfe76** [comment]
Just some quick thoughts on the possible response (happy to hear better ideas). 

We can return edits in 2 possible ways, by edit and by row. Adding the transmittal sheet (ts) likely changes changes both responses.

### By edit
If returning by edit does have a simple `"ts"` flag get us there? That way, in the UI, where we output loadId we could output that it was the TS. (We would have to change the column heading on tables in the UI to avoid confusion.) But the response might look like this:
```json
{
  "type": "syntactical",
  "edits": [
    {
      "edit": "synedit1",
      "ts": true,
      "lars": [
        {
          "lar": {"loanId": "s1"}
        },
        {
          "lar": {"loanId": "s2"}
        },
        {
          "lar": {"loanId": "s3"}
        }
      ]
    },
    {
      "edit": "synedit2",
      "ts": false,
      "lars": [
        {
          "lar": {"loanId": "s4"}
        },
        {
          "lar": {"loanId": "s5"}
        }
      ]
    }
  ]
}
```

### By row
If returning by row I think we need to add a `"ts": {}` to the response, in addition to the `"lars": []`. That way we could output the TS edits either as a separate table or in rows labeled as TS. The response might look like:
```json
{
  "ts": {
    "edits": [
      {
        "edit": "edit1",
        "type": "validity"
      },
      {
        "edit": "edit2",
        "type": "syntactical"
      }
    ]
  },
  "lars": [
    {
      "lar": {"loanId": "lar1"},
      "edits": [
        {
          "edit": "edit1",
          "type": "validity"
        },
        {
          "edit": "edit2",
          "type": "quality"
        }
      ]
    },
    {
      "lar": {"loanId": "lar2"},
      "edits": [
        {
          "edit": "edit3",
          "type": "syntax"
        }
      ]
    }
  ]
}
```

_Thanks @jmarin for bringing this up and walking through it with me._
