### ISSUE TITLE
Okay to remove `FIDataCsvParser` class?

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#611]
We've changed our strategy for reading and parsing HMDA files between the beginning of the project and now. Currently, we persist each line of the file individually (using `HmdaRawFile`), then parse each line separately (using `TsCsvParser`).  So, `FIDataCsvParser`, which has methods to break up a file into an `Iterable` and parse the whole thing, is not used. I believe it's a relic of our previous strategy.

Can `FiDataCsvParser` (and corresponding `FiDataDatParser`) be removed?

cc @jmarin

**Comment by jmarin** [comment]
Pending some experiments I'm doing as part of this [ticket](https://github.com/cfpb/hmda-platform/issues/597), I think so. It's been in the back of my mind for a while, but haven't pulled the trigger yet, want to make sure I don't need to revive it.
