### ISSUE TITLE
Getting a "400 The request content was malformed: Unexpected end of multipart entity" on /submissions/<submissionId>

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#618]
When running the docker-compose set up I'm seeing this error:
`POST http://192.168.99.100/api/institutions/0/filings/2016/submissions/8 403 (Forbidden)`

I can see that the correct headers are there (I think).

```
POST /api/institutions/0/filings/2016/submissions HTTP/1.1
Host: 192.168.99.100
Connection: keep-alive
Content-Length: 0
Pragma: no-cache
Cache-Control: no-cache
Origin: http://192.168.99.100
cfpb-hmda-institutions: 0,1,2,3
cfpb-hmda-username: fakeuser
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36
content-type: application/json
Accept: */*
Referer: http://192.168.99.100/0/2016
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
```

Can someone else try this? Or if you know the problem let me know?

**Comment by awolfe76** [comment]
You can use [the `api-updates` branch](https://github.com/cfpb/hmda-platform-ui/tree/api-updates) which has a few updates to match up with the API.

**Comment by awolfe76** [comment]
Based on https://github.com/cfpb/hmda-platform/pull/622 I tried setting the `Content-Type` to `multipart/form-data` but still get the 403. I also tried [this sample file](https://github.com/cfpb/hmda-platform/blob/master/parser/src/test/resources/txt/FirstTestBankData_clean_407_2017.txt) from `hmda-platform/blob/master/parser/src/test/resources/txt/`.

New request headers:
```
POST /api/institutions/0/filings/2017/submissions/5 HTTP/1.1
Host: 192.168.99.100
Connection: keep-alive
Content-Length: 53943
Pragma: no-cache
Cache-Control: no-cache
Origin: http://192.168.99.100
CFPB-HMDA-Institutions: fakeinstitution
CFPB-HMDA-Username: fakeuser
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36
Content-Type: multipart/form-data
Content-Disposition: inline; filename="FirstTestBankData_clean_407_2017.txt"
Accept: */*
Referer: http://192.168.99.100/0/2017
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
```

**Comment by awolfe76** [comment]
__Update__
The `403` has been resolved.
I'm now see a `400` error with a response of `The request content was malformed: Unexpected end of multipart entity`. I've update the issue title to show that.

**Comment by jmarin** [comment]
@awolfe76 Has this been resolved?

**Comment by awolfe76** [comment]
Yep, we're good. Closing.
