### ISSUE TITLE
Encode response on all API endpoints

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#620]
Encode the response with the encoding that is requested by the client via the `Accept-Encoding` header. 

See documentation [here](http://doc.akka.io/docs/akka/2.4.7/scala/http/routing-dsl/directives/coding-directives/encodeResponse.html#encoderesponse)

**Comment by schbetsy** [comment]
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]
