### ISSUE TITLE
Should /submissions/latest also return new id format?

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#627]
The `GET` for `/institutions/<institution>/filings/<period>/submissions/latest` says it will return 
```json
{
  "id": 3,
  "status": {
    "code": 1,
    "message": "created"
  }
}
```
And it does. But, should it return the new id format like we see in the `GET` for `/institutions/<institution>/filings/<period>` and the `POST` for `/institutions/<institution>/filings/<period>/submissions`?

```json
{
  "id": {
    "institutionId": "0",
    "period": "2016",
    "sequenceNumber": 1
  },
  "status": {
    "code": 1,
    "message": "created"
  }
}
```

**Comment by schbetsy** [comment]
I'd say yes. It was probably just an oversight that we haven't updated the format yet.
