### ISSUE TITLE
GET for /submissions/<submissionId>

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#628]
After a file upload the front-end immediately starts polling `GET - /institutions/<institution>/filings/<period>/submissions/<submissionId>` for check for status updates. Right now this endpoint is returning `HTTP method not allowed, supported methods: POST`.

Create the `GET` for this endpoint. Expected response being something like:
```json
"status": {
    "code": 1,
    "message": "created"
  }
```
where the `code` would be updating based on the [submission statuses](https://github.com/cfpb/hmda-platform/blob/master/Documents/submission-status.md). This response could also include more information like:
```json
{
  "id": {
    "institutionId": "0",
    "period": "2016",
    "sequenceNumber": 1
  },
  "status": {
    "code": 1,
    "message": "created"
  }
}
```

**Comment by schbetsy** [comment]
I assumed this purpose was already served by the `latest` endpoint. Is that one still necessary? 

Here it is, for reference:

`/institutions/<institution>/filings/<period>/submissions/latest`

`GET` - The latest submission for some institution and period

Example response, with HTTP code 200:

```json
{
  "id": 3,
  "status": {
    "code": 1,
    "message": "created"
  }
}
```

**Comment by awolfe76** [comment]
Good call @schbetsy! That endpoint will work. I'll make an update to the front-end to do that.
Closing this one.

_Just a note, that response will change with #627._
