### ISSUE TITLE
GET all parser errors for an uploaded file

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#629]
`/institutions/<institutionId>/filings/<period>/submissions/<submissionId>/parseErrors`
`GET` - List of each line of the submission that had parse errors, and the text of each error.
## Option 1

``` json
{
  "transmittalSheetErrors": [
    "Record Identifier is not an Integer",
    "Agency Code is not an Integer"
  ],
  "larErrors": [
    {
      "lineNumber": 2,
      "errorMessages": [
        "Incorrect number of fields. found: 32, expected: 39"
      ]
    },
    {
      "lineNumber": 4,
      "errorMessages": [
        "Record Identifier is not an Integer"
      ]
    },
    {
      "lineNumber": 11,
      "errorMessages": [
        "Loan Type is not an Integer",
        "Property Type is not an Integer",
        "Loan Purpose is not an Integer",
        "Owner Occupancy is not an Integer"
      ]
    }
  ]
}
```
- Pros: if the bank's file software has line numbers, it will be easy for them to find and correct errors.
- Cons: We are not currently persisting line number of each error, so we'd have to change how we persist errors. Adding line numbers may not be easy.
## Option 2

``` json
{
  "transmittalSheetErrors": {
    "line": "g|8800009923|t|201801171330|2017|99-0123456|412|FIRST TEST BANK|1275 First Street NE|Washington|DC|20002|FIRST BANK PARENT INC.|1700 G ST NW|WASHINGTON|DC|20552|Brian Jones|666-666-6666|555-555-5555|brian.jones@bank.com||||||||||||||||||",
    "errorMessages": [
      "Record Identifier is not an Integer",
      "Agency Code is not an Integer"
    ]
  },
  "larErrors": [
    {
      "line": "2|8800009923|3|8299422144|20170613|1|2|2|1|5|3|4|20170719|NA   |NA|NA |NA     |2|2|3| | | | |3| | | | |1|2|37|",
      "errorMessages": [
        "Incorrect number of fields. found: 32, expected: 39"
      ]
    },
    {
      "line": "t|8800009923|3|9471480396|20170919|1|1|2|1|40|3|4|20171018|NA   |45|067|950f.00|2|5|3| | | | |8| | | | |1|5|59|0| | | |NA   |2|1",
      "errorMessages": [
        "Record Identifier is not an Integer"
      ]
    },
    {
      "line": "2|8800009923|4|2185751597|20170328|n|h|c|d|25|3|3|20170425|NA   |45|067|9504.00|2|5|3| | | | |8| | | | |2|5|34|0| | | |NA   |2|1",
      "errorMessages": [
        "Loan Type is not an Integer",
        "Property Type is not an Integer",
        "Loan Purpose is not an Integer",
        "Owner Occupancy is not an Integer"
      ]
    }
  ]
}
```
- Pros: they can see the line they submitted and why it errors. They can use that to find and correct the errors in their files.
- Cons: In our current persistence model, each line's error set is not closely associated with its raw text. It might not be easy to figure out which line goes with which errors.

**Comment by schbetsy** [comment]
I wasn't sure what design would be best for this endpoint. What are your thoughts on the pros and cons of each option?
@awolfe76 from a usability/front-end perspective?
@jmarin from a back-end perspective?

**Comment by awolfe76** [comment]
Would it help anything to return the `loanId` instead of the whole line or a line number? We're doing something similar to that with the edits too.

**Comment by jmarin** [comment]
Unless I misunderstood your question, I think that if parsing fails we can't construct an object that contains a `loan`, and thus it's impossible to pass the `loanId` back. We can do that with edits because we have properly formed `LAR` records at that point

**Comment by awolfe76** [comment]
Makes sense. Does that stop the 2 examples @schbetsy mentions too?

**Comment by jmarin** [comment]
I don't see anything wrong with those options after a quick look. We can derive the line number and the error messages are output from the parsing operation

**Comment by awolfe76** [comment]
The best scenario maybe to have both line number and the full row, but I talked with @lesgou and @Kibrael a bit and __option 1, line number, like a good place to start.__

Displaying the full row in the UI could be a bit painful (especially for 2018), but we can probably find a way to do it; show n number of characters but provide the rest in a download.

**Comment by awolfe76** [comment]
In talking with @lesgou a bit more, line number is the way to go for the UI. Outputting the row in the UI won't be very helpful.

The row data will be helpful in a download though. So something to keep in mind, should we return the row data immediately and then piece together the download (csv) all on the front-end or should we make that another API call to download the file?
