### ISSUE TITLE
Add mock responses for endpoints

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#632]
From stand-up discussion today ...

After the demo showing the `/edits` endpoint working with the UI we agreed that there were only a few endpoints remaining and that we were at a point where we could start to take care of https://github.com/cfpb/hmda-platform-ui/issues/178, removing the mock API from the front-end. To help with moving that forward we can "mock" the remaining few endpoints on the back-end.

_This will not complete those endpoints, but will allow us to see responses from them. It also doesn't include all endpoints, just enough to get the front-end to a better place._

- [ ] `/institutions/<institution>/filings/<period>/submissions/<submissionId>/irs` `GET` [example](https://github.com/cfpb/hmda-platform-ui/blob/master/server/json/irs.json)
- [ ] `/institutions/<institution>/filings/<period>/submissions/<submissionId>/irs` `POST`
    - accepts true or false
    ```json
    {"verified": true}
    ```
    - returns ([example](https://github.com/cfpb/hmda-platform-ui/blob/master/server/json/receipt.json))
    ```json
    {
        "timestamp": <timestamp>,
        "receipt": <receipt-hash>
    }
    ``` 
- [ ] `/institutions/<institution>/filings/<period>/submissions/<submissionId>/sign` `GET`
    - returns a [receipt](https://github.com/cfpb/hmda-platform-ui/blob/master/server/json/receipt.json) (nulls if not signed)
- [ ] `/institutions/<institution>/filings/<period>/submissions/<submissionId>/sign` `POST`
    - accepts true or false
    ```json
    {"signed": true}
    ```
    - returns ([example](https://github.com/cfpb/hmda-platform-ui/blob/master/server/json/receipt.json))
    ```json
    {
        "timestamp": <timestamp>,
        "receipt": <receipt-hash>
    }
    ``` 
- [ ] `/institutions/<institution>/filings/<period>/submissions/<submissionId>/summary` `GET` [example](https://github.com/cfpb/hmda-platform-ui/blob/master/server/json/summary.json)

**Comment by nickgrippin** [comment]
@awolfe76: should the mock responses be varied, or is it acceptable if they're static?

**Comment by jmarin** [comment]
@nickgrippin @awolfe76 Based on our discussion yesterday about this, it's fine if they are static. I think the mock api is returning a file right now, a similar approach works.

**Comment by awolfe76** [comment]
For `/institutions/<institution>/filings/<period>/submissions/<submissionId>/irs` `POST` if we can have it return  
```json
{
    "timestamp": <timestamp>,
    "receipt": <receipt-hash>
}
```
if `{"verified": true}`.

And return
```json
{
    "timestamp": null,
    "receipt": null
}
```
if `{"verified": false}` that would be nice.

The same thing for `/institutions/<institution>/filings/<period>/submissions/<submissionId>/sign` `POST` based on `{"signed": true/false}`.

__And only if that's pretty easy.__ Other than that static works for everything.
