### ISSUE TITLE
Change output for macro edits API

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#634]
Macro edits don't have a list of `LAR` that fail the edit check (they are applied to all the file). Modify the API so that it only lists the macro edits, without an empty list of `LAR` in each reported error.
Depends on #633

**Comment by awolfe76** [comment]
In case its helpful, [here](https://github.com/cfpb/hmda-platform-ui/blob/9f575f60fb58756806f89b4706b7156d925d348a/server/json/macro.json) is what the front-end is currently using.
