### ISSUE TITLE
Add status to endpoints

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#647]
In trying to test the `POST` for the IRS and signature endpoints I realized that status isn't being updated to allow for that. I modified front-end code locally to make sure things were working and they are 👍 . But we should add the `status` object to the endpoints to verify. Plus I think that this is the correct way to handle this ... that way we're relying on the back-end for the status.

Endpoints to update:
_I'm guessing these values can be hard-coded for now but will be handled like other status updates in the future._
- `/institutions/<institution>/filings/<period>/submissions/<submissionId>/irs` `GET`
  - `code` should be `10`
- `/institutions/<institution>/filings/<period>/submissions/<submissionId>/irs` `POST`
  - `code` should be `10` if `verified: false` or `11` if `verified:true`
- `/institutions/<institution>/filings/<period>/submissions/<submissionId>/sign` `GET`
  - `code` should be `11`
- `/institutions/<institution>/filings/<period>/submissions/<submissionId>/sign` `POST`
  - `code` should be `11` if `verified: false` or `12` if `verified:true`

**Comment by nickgrippin** [comment]
So, what's currently being returned is:
```
{
  "timestamp": 1476809530772,
  "receipt": asd0f987134asdlfasdflk
}
```
and you would like:
```
{
  "timestamp": 1476809530772,
  "receipt": asd0f987134asdlfasdflk
  "status":
  {
    "code": 11,
    "message": "IRS report verified"
  }
}
```
