### ISSUE TITLE
Update POST to /institutions/<institution>/filings/<period>/submissions/<submissionId>

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#648]
This endpoint currently returns a plain text status. 

Can we update to return updated `status` object with the correct code from the [submission status doc](https://github.com/cfpb/hmda-platform/blob/97dcd30ea45b8f2bb7cbda916d13fdfecdaa1ea4/Documents/submission-status.md)? So instead of `uploaded` we would see

``` json
"status": {
    "code": 3,
    "message": "uploaded"
}
```

I also did a quick test on an invalid file format and saw this response:

``` json
{
"httpStatus":400,
"message":"Invalid File Format",
"path":"/institutions/0/filings/2017/submissions/43"
}
```

Can that (and other errors) be updated with the status object as well? Would this be a `code` of `-1`?

**Comment by nickgrippin** [comment]
@awolfe76:  Just to be clear, you want a 200 response with the status object instead of the current 400 response?

**Comment by awolfe76** [comment]
Sorry for the confusion. First thing is to have the `text` response be changed to the `status` object. Right now on a successful upload we just see `uploaded`, that would be good to have the `status` object instead.

The second part was just a question really, can we add anything to that `400` (and possibly other errors)? I __*don't*__ think we should change it to a `200` but was curious if we could add the `status` object to it as well?

Make sense?

**Comment by nickgrippin** [comment]
We would lose the `httpStatus` and `path` fields from the current response.  Is that acceptable?  If so, I see no problem with doing that switch.

**Comment by awolfe76** [comment]
So we couldn't do something like this?
```json
{
  "httpStatus":400,
  "status": {
    "code": 3,
    "message": "Invalid File Format"
  },
  "path":"/institutions/0/filings/2017/submissions/43"
}
```

**Comment by nickgrippin** [comment]
We use an `ErrorResponse` object for the current response, and I had switched it over to a `SubmissionStatus` to pass back the code and message.  But I'm not sure if I'm comfortable adding the `SubmissionStatus` to the `ErrorResponse`, because it's being used on several other endpoints unrelated to submissions.  Would it be all right to just have the code and message?  As far as I'm aware, the `httpStatus` and `path` fields are a bit redundant anyways.

**Comment by awolfe76** [comment]
So you're saying something like this?
```json
{
  "code": -1,
  "message":"Invalid File Format"
}
```

I _think_ that would be ok. Would the success still look like this?
```json
"status": {
  "code": 3,
  "message": "uploaded"
}
```

**Comment by nickgrippin** [comment]
This is what I'm currently getting back on a successful upload:
```
{
  "code": 3,
  "message": "uploaded"
}
```
And on an unsuccessful upload:
```
{
  "code": -1,
  "message": "Submission 1 not available for upload"
}
```

**Comment by awolfe76** [comment]
Let's give that a try. If somethings up we'll work it out.

**Comment by schbetsy** [comment]
Is there a specific reason why we only want the submission status, not any other info? I believe it would actually be easier/cleaner on the back end if we return the whole submission json, like this:
```json
    {
      "id": {
        "institutionId": "0",
        "period": "2017",
        "sequenceNumber": 3
      },
      "status": {
        "code": 3,
        "message": "uploaded"
      }
    }
```

**Comment by awolfe76** [comment]
@schbetsy - that's definitely ok. The main goal was to start to remove cases where we're ["manually" updating the submission status](https://github.com/cfpb/hmda-platform-ui/blob/1f87c8885fc2465164de38a8d6a7b2fb428a0c0f/src/js/actions/index.js#L319) on the front-end; would rather rely on the back-end.

So 👍  if there's more info and its easier.

**Comment by awolfe76** [comment]
@schbetsy - might want to take a look at #655 too, if you haven't already.

**Comment by nickgrippin** [comment]
@awolfe76: Would adding the Submission ID be of any additional value to the front-end?

**Comment by awolfe76** [comment]
We don't do anything with it in this case, just doesn't hurt if its easier to do.
