### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#65]
Let's setup [Travis CI](https://travis-ci.org/) so we know all tests pass before we merge.

**Comment by jmarin** [comment]
@hkeeler This has to be done by someone with admin rights, which I don't possess. The travis.yml file has been part of this project from the beginning, we just need to activate it. 
/cc @ericspry

**Comment by marcesher** [comment]
hey @jmarin and @hkeeler, I can certainly take care of this

**Comment by marcesher** [comment]
Should be all set up.

Though... are you sure you couldn't have done this yourself by adding the webhook in the hmda-platform repo's settings, and then going to travis-ci.org and toggling on the repo?

**Comment by jmarin** [comment]
Thanks @marcesher we're all set. I am pretty sure I couldn't toggle the project in Travis, I tried but it was grayed out for me and under a section that said "you need to be admin to enable these" or something like that.
