### ISSUE TITLE
Setup Test Coverage

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#66]
We've been using https://coveralls.io/ for our test coverage in grasshopper, however, it's been a bit glitchy with our grasshopper projects, even reporting coverage incorrectly at times.  There are alternatives, like [CodeCov](https://codecov.io/).  Let's investigate and implement.  If we _do_ go with something different, let's incorporate those same changes back into the grasshopper projects as well.

See: https://github.com/cfpb/grasshopper-parser/issues/29

**Comment by jmarin** [comment]
@hkeeler I think this has to be done by someone with admin rights on the cfpb account
/cc @ericspry

**Comment by ericspry** [comment]
checking with @marcesher ..

**Comment by ericspry** [comment]
Implemented with this PR https://github.com/cfpb/hmda-platform/pull/79
