### ISSUE TITLE
Implement toDAT method (TransmittalSheet)

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#67]
Implement function that outputs the Transmittal Sheet in DAT format. The specification can be accessed [here](http://www.ffiec.gov/hmda/pdf/spec2016.pdf) (pages 8 and 9)

https://github.com/cfpb/hmda-platform/blob/master/model/shared/src/main/scala/hmda/model/fi/ts/TransmittalSheet.scala#L27

**Comment by schbetsy** [comment]
The file specification says "Numeric fields are unpacked, unsigned, and right-justified." Does that imply that alphanumeric fields are left-justified? That seems to be the case in the `FITestData` file.

**Comment by schbetsy** [comment]
I'm interested in pairing on this one, @jmarin. It seems like generating DAT files is much more complex than generating CSV.

**Comment by schbetsy** [comment]
Removing Sprint 3 milestone, since we decided not to generate DAT in our app (for now).
