### ISSUE TITLE
Implement toDAT method (Loan Application Register)

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#68]
https://github.com/cfpb/hmda-platform/blob/master/model/shared/src/main/scala/hmda/model/fi/lar/LoanApplicationRegister.scala#L27

[File spec](http://www.ffiec.gov/hmda/pdf/spec2016.pdf) (pages 10 and 11)

**Comment by lgdean** [comment]
putting this one off for now, as in #67
