### ISSUE TITLE
SubmissionBasePathSpec failures

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#684]
This test seems to fail occasionally, perhaps due to ordering of checks for data

**Comment by nickgrippin** [comment]
I'm not able to reproduce this locally.  Does this happen when running the test individually, or the whole suite?

**Comment by jmarin** [comment]
This is _hard_ to reproduce in any shape or form. It happens rarely. I think a thorough review of the logic might be useful, to see if we can pinpoint any mistakes. Thanks
