### ISSUE TITLE
Implement toCSV method (Loan Application Register)

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#69]
https://github.com/cfpb/hmda-platform/blob/master/model/shared/src/main/scala/hmda/model/fi/lar/LoanApplicationRegister.scala#L22

See example for Transmittal Sheet [here](https://github.com/cfpb/hmda-platform/blob/master/model/shared/src/main/scala/hmda/model/fi/lar/LoanApplicationRegister.scala#L22)

[File Spec](http://www.ffiec.gov/hmda/pdf/spec2016.pdf) (pages 10 and 11)

**Comment by schbetsy** [comment]
OK to close this issue?
