### ISSUE TITLE
Change test from fixed data to property based testing

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#70]
The following test uses hard coded data. Change to use ScalaCheck's generators

https://github.com/cfpb/hmda-platform/blob/master/parser/shared/src/test/scala/hmda/parser/fi/lar/LarDatParserSpec.scala

Depends on #71

**Comment by schbetsy** [comment]
Since we aren't implementing DAT generators, I don't think I can use property-based testing for the LarDatParser. I can make the test more robust, but I'd like to wait until we've settled on which DAT sample files to use.

**Comment by schbetsy** [comment]
Ok to close?

**Comment by jmarin** [comment]
Fine with me

**Comment by lgdean** [comment]
me too!
