### ISSUE TITLE
Implement LAR test data generators

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#71]
https://github.com/cfpb/hmda-platform/blob/master/parser/shared/src/test/scala/hmda/parser/fi/lar/LarGenerators.scala

For an example, look at the Transmittal Sheet [generators](https://github.com/cfpb/hmda-platform/blob/master/parser/shared/src/test/scala/hmda/parser/fi/ts/TsGenerators.scala)

**Comment by hkeeler** [comment]
This _seems_ closable now with #82 and #84 merged.  We may get more strict with dates and geo-related fields at some point (see https://github.com/cfpb/hmda-platform/pull/84#issuecomment-191516995), but this seems good for this sprint.  Closing.
