### ISSUE TITLE
Remove `InstitutionRepository`?

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#711]
I noticed while reviewing something else that the code in [`InstitutionRepository.scala`](https://github.com/cfpb/hmda-platform/blob/master/model/shared/src/main/scala/hmda/model/institution/InstitutionRepository.scala) isn't called by anything. Okay to delete that file and the associated specs?

**Comment by jmarin** [comment]
Yes. It was on my todo list as part of the work I'm doing on panel, but if you want to send a PR removing it that helps
