### ISSUE TITLE
Verify edits

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#715]
Implement verification of quality / macro edits. This requires some coordination with the front end team. To my knowledge, there isn't a clearly defined workflow for this yet (it might be worthwhile to coordinate with @lesgou as well). A first (incomplete) cut was being implemented [here](https://github.com/jmarin/hmda-platform/tree/verify-edits). The idea behind this implementation is that once the user verifies an edit it is removed from the list of errors being returned. It is unclear if this is how it should work, but it should serve as a point of departure for discussion.

**Comment by schbetsy** [comment]
I agree you'll need to coordinate with the front end team on the design of this feature. My understanding of this feature was different from what's written here, so it's possible the design is still in flux.

(For the record: I thought edits would still appear in the list after they were verified. The user will want to be able to see and review all of their edits and justifications. It's true that verified edits shouldn't block a user from submitting the filing, but they should still be visible.)

**Comment by awolfe76** [comment]
I think @schbetsy is right. For edits that need verification they should stay visible. While it would be nice to be able to remove them, there's a good chance that the filer would want to change their answer.

**Comment by awolfe76** [comment]
#725 gets us started here.
