### ISSUE TITLE
Adding field data to edits endpoints

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#717]
See https://github.com/cfpb/hmda-platform-ui/issues/96

To help the filers read edits easier on the front-end, the `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits` and `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits/<syntactical|validity|quality|macro>` endpoints need field metadata added.

I _think_ we would need a `desc` for the edit itself,  a list of `fields` (with the `name` and `friendlyName`) the edit is applied to, and a list of `values` (with the `value` and the `field`) entered for each.

__Possible__ response example:
```json
{
    "edit": "S025",
    "ts": true,
    "desc": "A friendly description of this edit",
    "fields": [
        {
            "name": "fieldName",
            "friendlyName": "Field name"
        },
        {
            "name": "fieldName2",
            "friendlyName": "Field name 2"
        }
    ],
    "lars": [
         {
            "lar": {
                "loanId": "s1",
                "values": [
                    {
                        "value": "value",
                        "field": "fieldName"
                    },
                    {
                        "value": "value",
                        "field": "fieldName2"
                    }
                ]
            }
        }
    ]
}
```

_Note: I'm sure there are other ways to implement this, including adding new endpoints. Happy to hear suggestions._

**Comment by wpears** [comment]
I'd probably prefer the `lars` structured like:

```
"lars": [
  {
    "loanId": "s1",
    "field1": "field1value",
    "field2": "field2value"
   }
]
```

which, instead of having an object with a single `lar` key which refers to the actual lar object, just includes the lar object. Also, rather than having the lar object's field values be stuck in the `values` array, they are just included directly as part of the object.

**Comment by schbetsy** [comment]
So the new format for the edits endpoint looks like this?

I wanted to confirm the format of the endpoint in general. Also, specifically, I'm wondering about the field names in the `"rows"` objects. Should they be the friendly names?

```json
{
  "syntactical": {
    "edits": [
      {
        "edit": "S010",
        "description": "The first record identifier in the file must = 1 (TS). The second and all subsequent record identifiers must = 2 (LAR)",
        "rows": [
          {
            "loanId": "Transmittal Sheet",
            "Record Identifier": "2"
          },
          {
            "loanId": "s11234",
            "Record Identifier": "8"
          }
        ]
      },
    ]
  },
  "validity": {
    "edits": [
      {
        "edit": "S215",
        "description": "If Action taken type = 6, then date application received must = NA.",
        "rows": [
          {
            "loanId": "s11234",
            "Action Taken Type": "6",
            "Date Application Received": "19991231"
          },
          {
            "loanId": "s11678",
            "Action Taken Type": "6",
            "Date Application Received": "20171231"
          }
        ]
      }
    ]
  },
  "quality": {},
  "macro": [
    {
        "edits": [
            {
               "edit": "q007",
               "justifications": [
                 {
                   "value": "don't worry",
                   "selected": false
                 },
                 {
                   "value": "be happy",
                   "selected": false
                 }
               ]
            }
        ]
    }
  ]
}
```

**Comment by awolfe76** [comment]
I think that looks good.

2 things:
- I think `loadId` should be `rowId` in the `rows: []`, that was transmittal sheet makes sense.
- And the macro is being worked on. You can see it [here](https://github.com/jmarin/hmda-platform/blob/b1256c7dcae1c40c6d306b2f24902daa96a29797/Documents/API.md) under the `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits/<syntactical|validity|quality|macro>` endpoint, the "`POST` - Provides verification for macro edits" section (I've pointed out the formatting issues in that PR).

> Should they be the friendly names?

I think so, that's what we'll use on the front-end.

**Comment by awolfe76** [comment]
Based on the conversation here and in #718 what we have [above](https://github.com/cfpb/hmda-platform/issues/717#issuecomment-267416094) is good except we'll [wrap the fields](https://github.com/cfpb/hmda-platform/issues/718#issuecomment-267444595) in a `fields` object and switch `loanId` to `rowId`. For example:

```json
"edits": [
  {
    "edit": "V215",
    "description": "If Action taken type = 6, then date application received must = NA.",
    "rows": [
      {
        "rowId": "s11234",
        "fields":
        {
          "Action Taken Type": "6",
          "Date Application Received": "19991231"
        }
      },
      {
        "rowId": "s11678",
        "fields":
        {
          "Action Taken Type": "6",
          "Date Application Received": "20171231"
        }
      }
    ]
  }
]
```

@schbetsy - double check me please.

**Comment by schbetsy** [comment]
Is it okay if I take over this issue? It's closely related to the remaining work on #718, so I'd like to do both at the same time.

**Comment by jmarin** [comment]
@schbetsy Yes please, I forgot to reassign some of these. Thanks
