### ISSUE TITLE
Allow edits to be returned by row

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#718]
See https://github.com/cfpb/hmda-platform-ui/issues/272

We need to allow filers to be able to sort edits by LAR row.

One way to handle this would be to add a `sortBy` parameter to the `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits` endpoint. This endpoint would default to the current response, but a request to `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits?sortBy=row` would return the edits grouped by LAR row.

__Possible__ json response:
```json
{
  "rows": [
    {
      "rowId": "s1",
      "edits": [
        {
          "edit": "S025",
          "desc": "A friendly description of this edit",
          "fields": [
            {
              "name": "fieldName",
              "friendlyName": "Field name"
            },
            {
              "name": "fieldName2",
              "friendlyName": "Field name 2"
            }
          ],
          "values": [
            {
              "value": "value",
              "field": "fieldName"
            },
            {
              "value": "value",
              "field": "fieldName2"
            }
          ]
        }
      ]
    }
  ]
}
}
```

**Comment by schbetsy** [comment]
This should wait until #717 is finished to avoid conflicts.

**Comment by schbetsy** [comment]
_Not sure if this was already discussed elsewhere. If so, let me know_

I'm curious: why are the `fields` and `values` separate JSON objects in the response? Is that better than combining them, from an API usability perspective? Here's a possible example where they're combined (I substituted realistic values into the fields, so I could understand better):

```json
{
  "rowId": "s1",
  "edits": [
    {
      "edit": "V210",
      "desc": "Date application received must be in YYYYMMDD format; month and day must be in the range 01-12 and 01-31, respectively or equal NA. YYYY must be numeric and the first two digits of the number must equal 20.",
      "fields": [
        {
          "name": "loan.applicationDate",
          "friendlyName": "Date Application Received",
          "value": "19991231"
        }
      ]
    }
  ]
}
```

**Comment by schbetsy** [comment]
Another question: Does this endpoint not need to separate the edits by edit type? From your example, it looks like we can put all of the edits in the same list, regardless of whether they're Syntactical, Validity, or Quality. 

Should the Edits By Row endpoint return Macro edits at all?

**Comment by awolfe76** [comment]
@schbetsy for the first question, I think the conversation in #717 is related.

> Does this endpoint not need to separate the edits by edit type?

I don't think so. We'll just list them how they come back by row ... at least for now. I could see where it might make more sense to the filer but we can do that later I think.

> Should the Edits By Row endpoint return Macro edits at all?

I think we'll need them. This is really to give the filer an option, they may want to view the edits this way instead. But we'll still need to show macro. Its likely the format of the macro response is the same either way, by row or by edit type, so still its own object.

**Comment by schbetsy** [comment]
Here's a draft of this endpoint, from my current understanding. @awolfe76 I'll need your eyes on this again. (Thanks for all of your input so far!)

(I left the Macro edits section blank, since a different issue is handling that)

```json
{
  "rows": [
    {
      "rowId": "Transmittal Sheet",
      "edits": [
        {
          "editId": "S020",
          "description": "Agency code must = 1, 2, 3, 5, 7, 9. The agency that submits the data must be the same as the reported agency code.",
          "Agency Code": 4
        }
      ]
    },
    {
      "rowId": "8299422144",
      "edits": [
        {
          "editId": "S020",
          "description": "Agency code must = 1, 2, 3, 5, 7, 9. The agency that submits the data must be the same as the reported agency code.",
          "Agency Code": 11
        }
      ]
    },
    {
      "rowId": "4977566612",
      "edits": [
        {
          "editId": "V550",
          "description": "Lien status must = 1, 2, 3, or 4.",
          "Lien Status": 0
        },
        {
          "editId": "V555",
          "description": "If loan purpose = 1 or 3, then lien status must = 1, 2, or 4.",
          "Loan Purpose": 1,
          "Lien Status": 0
        },
        {
          "editId": "V560",
          "description": "If action taken type = 1-5, 7 or 8, then lien status must = 1, 2, or 3.",
          "Action Taken Type": 3,
          "Lien Status": 0
        }
      ]
    }
  ],
  "macroResults": {}
}
```

**Comment by awolfe76** [comment]
Seeing it now it feels like we should wrap the fields. Something like:
```json
{
  "rowId": "8299422144",
  "edits": [
    {
      "editId": "S020",
      "description": "Agency code must = 1, 2, 3, 5, 7, 9. The agency that submits the data must be the same as the reported agency code.",
      "fields": [
        {
          "Agency Code": 11
        }
      ]
    }
  ]
},
```

My thought being how else would we know the which properties are the fields. If the `edits:[]` response would only ever have `editId`, `description`, and then the fields in the objects we would be ok. But if it changes we'd be in trouble ... maybe? If so we can add that to #717 too.

**Comment by schbetsy** [comment]
That makes sense. When there's more than one relevant field, which do you prefer?
```
"fields":{  
   "Lien Status":0,
   "Action Taken":6
}
```
or
```
"fields":[  
   {  
      "Lien Status":0
   },
   {  
      "Action Taken":6
   }
]
```

**Comment by awolfe76** [comment]
I think 
```
"fields":{  
   "Lien Status":0,
   "Action Taken":6
}
```
looks cleaner.
