### ISSUE TITLE
Add pagination to endpoints

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#719]
See https://github.com/cfpb/hmda-platform-ui/issues/274

We'll need pagination on a few endpoints:
- [ ] ~`/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits/<syntactical|validity|quality|macro>`~
- [ ] `/institutions/<institution>/filings/<period>/submissions/<submissionId>/irs`(see #864)
- [x] `/institutions/<institution>/filings/<period>/submissions/<submissionId>/parseErrors` (#821)
- [ ] ~`/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits/<type>/<edit>`~

There are a few ways to handle this but a _possible_ addition to the responses could be, using `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits/syntactical` as an example:
```json
"_links": {
  "self": ".../edits/syntactical?page=3",
  "first": ".../edits/syntactical",
  "prev": ".../edits/syntactical?page=2",
  "next": ".../edits/syntactical?page=4",
  "last": ".../edits/syntactical?page=53"
},
"count": 20,
"total": 1054
```

~~We could also add a `?limit=x` parameter but I'm not sure we need to yet.~~ I think the default should be 20 but happy to hear otherwise. (I'm just saying 20 ... not much thought behind it.)

`/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits` probably doesn't need pagination but should probably return only the first 20 edits for each edit type.

**Note** - macro edits don't need pagination, at least in our UI. So maybe we need do the `?limit=x` now so we can get all of them. There are only 33 rows for macro. **Or**, up the minimum returned to 40 to cover that.

**Comment by jmarin** [comment]
Can you clarify the `_links` part? Are those supposed to be URLs for navigation? If that is the case, I think it's leaking the HTML UI into the backend, which I don't think is a good idea

**Comment by awolfe76** [comment]
In doing a bit of research on it I saw that pattern a few times and thought it was looked useful:
https://developers.facebook.com/docs/graph-api/using-graph-api#cursors
https://developer.atlassian.com/confdev/confluence-server-rest-api/pagination-in-the-rest-api (have to click "view the response")
And some others. Its basically just returning what the links would be, just URLs, not really HTML.

But it's definitely possible without the full URLs too.

**Comment by hkeeler** [comment]
👍 The whole `_links` pattern comes from the [HAL](http://stateless.co/hal_specification.html) format.  It has been adopted by quite a few APIs.  And yes, the intent is for each of those links to reference API resources, not return HTML directly.

There's another good example of HAL `_links` under _Embedded Resources_ on https://sookocheff.com/post/api/on-choosing-a-hypermedia-format/.

Looks like someone has started a [akka-http-hal](https://github.com/marcuslange/akka-http-hal) project.  Doesn't look like anyone is really using it (yet?), but could be helpful if we want to borrow some ideas from.

If it seems like it will be tricky implementing this on the backend, we may want to just start with:

1. Adding SQL-like [`limit` and `offset`](https://www.postgresql.org/docs/9.6/static/queries-limit.html) query params...with smart defaults.
1. Adding a `count` attribute to the results.

With these, you have all the data you need to calculate your `next`, `prev`, `last`, etc. links.

Interestingly, there's some discussion on this topic going on over on the _API Standards_ PR.
* https://github.com/cfpb/development/pull/121#discussion_r90121665

**Comment by nickgrippin** [comment]
I can understand the design pattern here, and see how it would be used.

My question is: why would we want the back-end to be responsible for pagination?  It seems like a much simpler (and quicker) solution to have the front-end to request the entire data set and just present each subset, advancing when the user clicks `next`.  This way, we avoid excessive API calls and the longer load times while waiting for each call to finish.

**Comment by awolfe76** [comment]
@nickgrippin - mostly because the dataset could be very large. Thousands, if not 10's of thousands, of objects could be returned from the edits endpoints.

**Comment by schbetsy** [comment]
I'll use the `parseErrors` endpoint as an example, so I can know how it should look. I made a rough draft of the design below, based on @awolfe76 's spec and bits of the HAL documentation. Let me know what should change.

Also, how should the counting work? Does the example below count as 4 results (if we're counting lines of the HMDA file)? Or as 8 results (if we're counting individual errors)?

Key features:

- it still has `transmittalSheetErrors` and `larErrors` at the top level, like before
- it now also has `total`, `count`, and `_links` at the top level
- `href` has the path of the current resource, but with the pagination query string replaced by `{ref}`
- `self`, `first`, `prev`, `next`, and `last` are query strings to replace the `{ref}` in the `href`

```json
{
  "transmittalSheetErrors": [
    "Record Identifier is not an Integer",
    "Agency Code is not an Integer"
  ],
  "larErrors": [
    {
      "lineNumber": 2,
      "errorMessages": [
        "Incorrect number of fields. found: 32, expected: 39"
      ]
    },
    {
      "lineNumber": 4,
      "errorMessages": [
        "Record Identifier is not an Integer"
      ]
    },
    {
      "lineNumber": 11,
      "errorMessages": [
        "Loan Type is not an Integer",
        "Property Type is not an Integer",
        "Loan Purpose is not an Integer",
        "Owner Occupancy is not an Integer"
      ]
    }
  ],
  "count": 20,
  "total": 103,
  "_links": {
    "href": "/institutions/<institution>/filings/<period>/submissions/<submissionId>/parseErrors{rel}",
    "self": "?page=3",
    "first": "",
    "prev": "?page=2",
    "next": "?page=4",
    "last": "?page=6"
  }
}
```

**Comment by awolfe76** [comment]
Looks good to be @schbetsy. I would vote for the first option in this case, that the rows (lines) would be the count, not the errors. So 4.

**Comment by awolfe76** [comment]
Also, not sure what your plan was for this issue, but if you wanted to break this out into multiple PRs, with parse errors being the first, that would be useful on the front-end too. We could implement the pagination for those and then later apply it to other endpoints as they are built.

**Comment by awolfe76** [comment]
Closing.

#821 did the parse errors endpoint.
#845 is created for the edits.
#864 is created for IRS.
