### ISSUE TITLE
Change institution status?

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#720]
_More of a question to get other thoughts but **no rush**_

The `institution` endpoint returns:
```json
{
  "id": "12345",
  "name": "First Bank",
  "status": {
    "code": 1,
    "message": "active"
  }
}
```
where `active` means "on panel". 

Can we change that message to `on-panel` or something similar to make it more clear? To me, `active` means the bank is still doing business. 

Or, as @hkeeler [points out](https://github.com/cfpb/hmda-platform/issues/720#issuecomment-264975710) maybe we remove it from the `/institutions` endpoint and instead make changes to the `/institutions/<institution>` endpoint and the `institutions/<institution>/filings/<period>` endpoint.

Same for the `code: 0` where the message is `inactive`. To me, that sounds like the institution is not doing business anymore.

Maybe 
`0`: `not-on-panel`
`1`: `on-panel`

Or maybe it should just be something like (take from https://github.com/cfpb/hmda-platform/pull/411#issuecomment-226312782):
```json
"filings": [
  {
    "period": "2017",
    "institutionId": "12345",
    "required": true,
    "start": 0,
    "end": 0
  }
]
```
That is found in both the `/institutions/<institution>` and  `institutions/<institution>/filings/<period>` endpoints.

This would require updates to:
- [ ] [institution status](https://github.com/cfpb/hmda-platform/blob/master/Documents/institution-status.md)
- [ ] [api](https://github.com/cfpb/hmda-platform/blob/master/Documents/API.md)

**Comment by hkeeler** [comment]
`institution.status` was not (originally) intended to indicate whether an institution is on/off panel.  It was a more general indicator of whether an institution that is in our system and perhaps _used_ to file, but is no longer _active_, likely due to it being merged with some other institution, going out of business, etc.  There have been several questions about this in the past, and seems more confusing than useful at this point.  I think we may want to remove it all together for now.  We'd won't be in this situation in year-one anyway.

In my opinion, the of/off panel indicator should be on the `institution/<institution_id>/filing/<period>` resource.  That way you can look at each filing over time for a given institution, and see if it was required or not for that period.  Way back on https://github.com/cfpb/hmda-platform/pull/411#issuecomment-226312782 we discussed something like this.

**Comment by awolfe76** [comment]
> In my opinion, the of/off panel indicator should be on the institution/<institution_id>/filing/<period> resource.
👍

**Comment by schbetsy** [comment]
I think this change makes sense. Let me confirm that we agree on what should happen.

1. Remove the `status` field from the Institution, so the institution's info will now look like this:
```json
{
  "id": "0",
  "name": "Bank 0"
}
```

2. Add a field to the Filing detail that shows whether the institution is required to file (is "on panel") for that filing period. The filing info would look like this:
```json
{
  "institutionId": "0",
  "status": {
    "code": 1,
    "message": "not-started"
  },
  "required": true,
  "end": 0,
  "start": 0,
  "period": "2017"
}
```

Is that what we're going for?

**Comment by awolfe76** [comment]
I think that's it @schbetsy. But maybe `required` should be something more explicit, `filing-required`?
@hkeeler

**Comment by hkeeler** [comment]
@schbetsy, yes, that's essentially it.  I think that gets us in good shape.  Also, I think `required` is _OK_, but I'm not married to it if someone else has a strong opinion.

**Comment by schbetsy** [comment]
Is the concept of `InstitutionStatus` useful at all anymore as part of the Institution model? That is, should I only remove it from the API response, or should I remove it from the app entirely? @hkeeler

**Comment by hkeeler** [comment]
I think we can remove it entirely.  We may need it (or something similar) in future years, but I don't think it serves any purpose as of now.  Basically, we're not going to be adding any institutions that can't file, so they're all going to be `active`.

Also, even when we _do_ have `inactive` banks in the system, we could control this by just not giving them a "filing" for that period.  That would leave them in the system, but they could no longer file.

**Comment by schbetsy** [comment]
#728 and #731 should be sufficient to close this issue.

For the record: The Filing object now has a `filingRequired` field, but there is currently no logic to populate that value.
