### ISSUE TITLE
Update edits response to let TS be part of the edits []

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#721]
_Just a question, no rush_

#623 added `ts: true` to the `/edits` and `/edits/<type>` endpoints, like this:

```json
"edits": [
  {
    "edit": "S025",
    "ts": true,
    "lars": [
      {
        "lar": {"loanId": "s1"}
      },
      {
        "lar": {"loanId": "s2"}
      },
      {
        "lar": {"loanId": "s3"}
      }
    ]
  }
]
```

Rather than have `ts: true` it might be better remove the `ts:true` and rename the `lars: []` to `rows: []` and then change the `lar: {}` to `row: {}` and `loanId` to `rowId`. (`rowId` would either be "Transmittal Sheet" or the loan ID.) This would let us just have the transmittal sheet be a normal part of the edits.

```json
"edits": [
  {
    "edit": "S025",
    "rows": [
      {
        "row": {"rowId": "Transmittal Sheet"}
      },
      {
        "row": {"rowId": "s2"}
      },
      {
        "row": {"rowId": "s3"}
      }
    ]
  }
]
```

Thoughts?

**Comment by kgudel** [comment]
I have completed work on this in working on #717 . Will post a PR of that work broken out.
