### ISSUE TITLE
Make sure filing status is updated based on submission status

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#722]
In the UI, if you view the list of institutions Bank 0 is `1: not-started`. Clicking begin filing takes you to the upload screen. Uploading a file runs through the process. At this point Bank 0's status should be `2: in-progress`. But, when you go back to the institutions listing page you'll see that Bank 0 is still listed as `1: not-started`. 

In talking with @jmarin it seems like the filing status isn't being updated based on the submission status.

It should work like this:
- if no submission status, filing = 1 (not-started)
- if submission status is greater than or equal to 1 **and** less than 12, filing status = 2 (in-progess)
- if submission status is 12, filing status = 3
- ~~if submission status is 13, filing status = 1~~

Those are with the current setup.

~~There will be another issue created about the statuses ... do we need a status of `failed` for the filings and do we need a status of `cancelled` for the submissions? Coming soon.~~

_#723 may change this_

**Comment by nickgrippin** [comment]
@awolfe76: Just to clarify, since a filing can have multiple submissions:  are these if ANY submission status meets these cases?  So if there's a submission with status 3 and another with status 12, would the filing status = 3?

Also, we don't have a submission status with a code of 13.  Could you clarify what you meant by that?

**Comment by awolfe76** [comment]
> Just to clarify, since a filing can have multiple submissions: are these if ANY submission status meets these cases? So if there's a submission with status 3 and another with status 12, would the filing status = 3?

The filing status should be dependent only on the latest submission using the `sequenceNumber`. (I think we should probably have a submission status that tells us they re-submitted but we can worry about that later.)

> Also, we don't have a submission status with a code of 13. Could you clarify what you meant by that?

I'm not sure now, probably a typo, but it doesn't work.
Removed it above. Good catch.
