### ISSUE TITLE
Question: Updates to filing and submission status

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#723]
Currently we have a `4: cancelled` status for the [filings](https://github.com/cfpb/hmda-platform/blob/ac9f01670aa03aca7e03a1903e312b6db453fb65/Documents/filing-status.md) and a `-1: failed` status for [submissions](https://github.com/cfpb/hmda-platform/blob/ac9f01670aa03aca7e03a1903e312b6db453fb65/Documents/submission-status.md).

The `4: cancelled` status for filings means "The filing has been cancelled, signifying that the filing is no longer required." I'm not sure what the "signifying that the filing is no longer required" part means. Is that saying that an institution is no longer on the filing panel?

Should we add a status to each so they have matching statuses? Should we add a `5: failed` status for filings and a `-2: cancelled` status for submissions?

_If changes come out of this issue they could change #722_

**I should add that we do have the idea (no issues created yet) of a "Cancel" button that would cancel a current submission.**

**Comment by jmarin** [comment]
I have a bit of a problem with `cancelled` for submissions. It might be tricky for the user to interpret exactly how this works. Once we upload a file, the processing pipeline starts, automatically. How / when would they cancel? It might be confusing that they hit "cancel" and the platform is still processing data. Due to the asynchrony of our system it's hard to guarantee when we process a cancel message. We do it _eventually_, but I think that's hard to communicate back in a UI.

**Comment by hkeeler** [comment]
Per @awolfe76: 
>The `4: cancelled` status for filings means "The filing has been cancelled, signifying that the filing is no longer required." I'm not sure what the "signifying that the filing is no longer required" part means. Is that saying that an institution is no longer on the filing panel?

Yeah, that's not what `cancelled` is supposed to mean.  A filing goes into a `cancelled` state only from `completed` when they want/need to re-file.  We also discussed calling this `revoked` if that clarifies it at all.  See https://github.com/cfpb/hmda-platform/pull/411#issuecomment-226338262 and the comments that follow for more discussion on this.

Per @awolfe76: 
>Should we add a status to each so they have matching statuses? Should we add a `5: failed` status for filings and a `-2: cancelled` status for submissions?

I don't think so.  A filing should just remain `in-progress` while in the process of getting a _good_ submission into the system.  Once you _sign_ a given valid submission, then you transition the filing to `complete`.

Here's the [state diagram](https://github.com/cfpb/hmda-platform/pull/411#issuecomment-226531309) we originally used to discuss this.

Per @jmarin: 
>I have a bit of a problem with `cancelled` for submissions. It might be tricky for the user to interpret exactly how this works. Once we upload a file, the processing pipeline starts, automatically. How / when would they cancel? It might be confusing that they hit "cancel" and the platform is still processing data. Due to the asynchrony of our system it's hard to guarantee when we process a cancel message. We do it _eventually_, but I think that's hard to communicate back in a UI. 

I can see how this would be a problem.  For our initial version, can we just not allow canceling while a submission is in progress?  Just make them ride-it-out, and once the submission is completed, then they can cancel it.

**Comment by awolfe76** [comment]
> Yeah, that's not what cancelled is supposed to mean. A filing goes into a cancelled state only from completed when they want/need to re-file. We also discussed calling this revoked if that clarifies it at all. See #411 (comment) and the comments that follow for more discussion on this.

Ok, that makes sense then. We would just need to update the description in the docs.

> I don't think so. A filing should just remain in-progress while in the process of getting a good submission into the system. Once you sign a given valid submission, then you transition the filing to complete.

It would be nice to be able to show this on the institutions listing page though. Although https://github.com/cfpb/hmda-platform-ui/issues/269 gets us that info for that screen. So ok there.

> I can see how this would be a problem. For our initial version, can we just not allow canceling while a submission is in progress? Just make them ride-it-out, and once the submission is completed, then they can cancel it.

Totally fine with the idea with allowing canceling while in-progress to be done later.

Thanks @hkeeler

**Comment by awolfe76** [comment]
Closing. Can re-open if more discussion needed.
