### ISSUE TITLE
Add data for edit/field metadata

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#724]
Add the data required to fill in the metadata setup in #717.

Attached is a `.csv` (uploaded as a `.txt` because that's what Github likes) with the required data. There are some extra fields in the file that may be used later. To complete this task the "Field Names", "Edit Number", and "User Friendly Edit Description" will be needed.

The "User Friendly Edit Description"  will be the `"desc": "A friendly description of this edit",` part of #717.

The "Field Names" (comma separated in the string) will be used to fill in the `"friendlyName":` in:
```json
"fields": [
        {
            "name": "fieldName",
            "friendlyName": "Field name"
        },
        {
            "name": "fieldName2",
            "friendlyName": "Field name 2"
        }
    ],
```

The `.csv` does **not** contain the `name` for the field. I'm not sure where that will be defined, maybe already has been on the backend, but can be added if needed.

[edit-metadata1.txt](https://github.com/cfpb/hmda-platform/files/646387/edit-metadata1.txt)

**Comment by schbetsy** [comment]
I noticed in the attached file that the `fieldNames` column only lists one field for each edit, though most edits have several relevant fields. For example, V275 depends on `applicationDate` AND `actionTakenDate`, but only "Action Taken Date" is listed in the file. 

So, (if my understanding of the desired UI is correct) I don't think we can rely on that file to get all of the fields we need for each edit. 

(I already added this comment [here](https://github.com/cfpb/hmda-platform/pull/732#discussion_r91789843), but this is a more relevant place to put it).

**Comment by schbetsy** [comment]
Bumping this. I'm currently working on adding an edit's relevant fields to the API, so it would be nice to know where the edit metadata will come from.

Will we be able to get a file that lists all of an edit's relevant fields? If so, how will it be formatted?

**Comment by schbetsy** [comment]
Resolution: @lesgou will add relevant fields to the edit-metadata file, separated by semicolons.

**Comment by lesgou** [comment]
Updated file:

[edit-metadata1.txt](https://github.com/cfpb/hmda-platform/files/693694/edit-metadata1.txt)

**Comment by awolfe76** [comment]
@schbetsy - can this one be closed?

**Comment by schbetsy** [comment]
Yep, good catch. This was necessary for #770 and is safe to close.
