### ISSUE TITLE
Create the POST for verification for macro edits

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#725]
Each macro edit requires verification. The UI will allow for multiple verifications for each edit. When each verification is selected the UI will `POST` to the `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits/macro` endpoint and send:
```json
{
  "edit": "M1",
  "justification": "The string for the selected justification."
}
```

The response should be:
```json
{
  "edit": "M2",
  "justifications": [
    "One string",
    "for every justification",
    "that has been selected",
    "including all previous selections"
  ]
}
```

The question I have for this is how does the UI know what the options are for the selections? Should we have them in the UI? Should they be part of the API?

In the docs for the `GET` for edits we have:
```json
"justifications": [
  {
    "value": "don't worry",
    "selected": false
  },
  {
    "value": "be happy",
    "selected": false
  }
]
```
Should that response have each possible selection in it? If so the json response to a `POST` would also need to have that same structure. (Maybe we change `"selected"` to `"verified"`.) 

@wpears - is that enough to allow us to update the state and be able render what we need?

_Related to See https://github.com/cfpb/hmda-platform-ui/issues/281_

**Comment by wpears** [comment]
I had it set out that the `GET` request would return the options so that the API is fully encapsulated (ie, if other clients than the UI wanted to verify macro edits, they could do so without referencing an external file).

I'd also prefer more structure in the justifications because of how rendering an "Other" freeform response would work (so the front-end isn't just rendering strings with no context and having to do string comparisons, but is working from a set of values, one of which can be freeform text (which causes the textarea to be rendered)).

So both the `POST` would use the following structure:
```
{
"edit": "M2",
"justifications": [
  {
    "value": "don't worry",
    "selected": true
  },
  {
    "value": "be happy",
    "selected": false
  },
  {
    "value": "Other",
    "selected": true,
    "text": "this is text written by a user"
  }
]
}
```

Which would then be returned in the same format upon `GET` requests. This is perhaps somewhat inefficient over the wire, but probably allows the code to be simpler since there aren't any mutations.

**Comment by awolfe76** [comment]
Just to finishing this off:

### `POST` request
```json
{
  "edit": "M1",
  "justification": "The string for the selected justification."
}
```

### `POST` and `GET` responses
- The `justifications: []` would be the set of all possible responses.
  - __Always__ returns the full set of justifications.
- Changes `selected` to `verified`.
```json
{
  "edits": [
    {
      "edit": "M2",
      "justifications": [
        {
          "value": "don't worry",
          "verified": true
        },
        {
          "value": "be happy",
          "verified": false
          },
        {
          "value": "Other",
          "verified": true,
          "text": "this is text written by a user"
        }
      ]
    }
  ]
}
```

**Comment by jmarin** [comment]
Isn't `verified` redundant? If they have posted a justification, doesn't that mean the edit is verified already?. How does the backend know what to return for this field?

**Comment by awolfe76** [comment]
>Isn't verified redundant? If they have posted a justification, doesn't that mean the edit is verified already?

`verified` does seem a little redundant but I'm not sure how to handle the case of the first time through after upload or when a filer logs out and comes back later. We would need to know all of the information. _(We still need to get the set of justifications for macro edits.)_

> How does the backend know what to return for this field?

Making assumptions here but if you are saving the list of `justifications` received by each `POST`, as long as its in the saved list `verified` is set to `true`.

> In addition to this (and related) the justification schema doesn't seem to be fully defined. The POST example above includes the edit name and a justification (text). But in the response example we see one where there is value, verified and text.

The last one is `Other`. In the available justifications should be an `Other` option. If a filer selects this option the UI shows them a text area to enter a new, free form, justification. That's why the different key `text` is there.

Hope that helps.

**Comment by awolfe76** [comment]
Sorry about this but thinking a little more we also need a way to "un-verify" a justification. I can see situations where a filer changes this. 

I think that can just be an update to the `POST` request:

```json
{
  "edit": "M1",
  "justification": "The string for the selected justification.",
  "verified": false
}
```

where the `verified` flag is still `true/false` telling whether the justification has been added or removed.

**Comment by jmarin** [comment]
>verified does seem a little redundant but I'm not sure how to handle the case of the first time through after upload or when a filer logs out and comes back later. We would need to know all of the information. (We still need to get the set of justifications for macro edits.)

Not sure if I'm missing something here. On first upload, the return for the `justifications` is an empty array. Then they provide some justifications, let's say for a few edits. We persist that. When they come back the macro edits endpoint will include the set of justifications provided for each edit by the user. 

>Sorry about this but thinking a little more we also need a way to "un-verify" a justification. I can see situations where a filer changes this.

>I think that can just be an update to the POST request:

>{
  "edit": "M1",
  "justification": "The string for the selected justification.",
  "verified": false
}
where the verified flag is still true/false telling whether the justification has been added or removed.

So does this mean we need to update justifications as well?. How do we uniquely identify them?. Maybe combination of `edit` and `justification`? (I don't like looking at strings for comparison though)

**Comment by awolfe76** [comment]
> Not sure if I'm missing something here. On first upload, the return for the justifications is an empty array. Then they provide some justifications, let's say for a few edits. We persist that. When they come back the macro edits endpoint will include the set of justifications provided for each edit by the user.

Rather than an empty array the UI was going to rely on the back-end to generate the list of options available to macro edits. Probably other ways to handle this, but that was the thought. In that case we would need `justifications: []` to be populated all the time.

> So does this mean we need to update justifications as well?. How do we uniquely identify them?. Maybe combination of edit and justification? (I don't like looking at strings for comparison though)

Yes, we'll have to let filers update their justifications (add/remove). To uniquely identify them maybe we `POST` something like:

```json
{
  "edit": "M1",
  "justification": {
    "text": "The string for the selected justification.",
    "value": 0
  },
  "verified": false
}
```

and the responses would be:

```json
"justifications": [
  {
    "text": "don't worry",
    "value": 0,
    "verified": true
  },
  {
    "text": "be happy",
    "value": 1,
    "verified": false
  },
  {
    "text": "other",
    "value": 2
    "verified": true,
    "justification": "this is text written by a user"
  }
]
```

This would make the HTML select render like:
```html
<select>
  <option value="0">don't worry</option>
  <option value="1">be happy</option>
  <option value="2">other</option>
</select>
```

The `other` option creates a text area which we would also send to the back-end as (like above):

```json
{
  "text": "other",
  "value": 2
  "verified": true,
  "justification": "this is text written by a user"
}
```

**Comment by jmarin** [comment]
>Rather than an empty array the UI was going to rely on the back-end to generate the list of options available to macro edits. Probably other ways to handle this, but that was the thought. In that case we would need justifications: [] to be populated all the time.

Where is this defined? We've been returning an empty array. Does this mean that we already have all the justifications populated, and we're just waiting to update them with "verified" and possibly a text? Couldn't the user pick from a list (maybe provided by another API endpoint) and then send only the stuff they are interested in saving?

**Comment by wpears** [comment]
@jmarin this hasn't been specifically defined in the spec, but it was how it was implemented in the mock-api (see https://github.com/cfpb/hmda-platform-ui/pull/170). We likely should have added this in detail to `api.md` or to an issue on hmda-platform.

In the scheme I described above, both `GET` and `POST` involve the full set of justifications:

Front-end issues `GET` to see value macro edits, the following is returned:

```
{
"edit": "M2",
"justifications": [
  {
    "value": "don't worry",
    "selected": false
  },
  {
    "value": "be happy",
    "selected": false
  },
  {
    "value": "Other",
    "selected": false,
    "text": ""
  }
]
}
```

The options are *predetermined by the backend* for each edit. Whether the default values (nothing selected) are persisted or just returned as a default case in the handling code is up to the backend.

Say the user then selects the first option, the `POST` that is issued has as its body the following:

```
{
"edit": "M2",
"justifications": [
  {
    "value": "don't worry",
    "selected": true
  },
  {
    "value": "be happy",
    "selected": false
  },
  {
    "value": "Other",
    "selected": false,
    "text": ""
  }
]
}
```

The backend accepts this `POST` and persists the values of the justifications. No comparisons need to be made, this completely replaces anything persisted before.


The user then selects the `Other` option and types in a justification, the following is issued:

```
```
{
"edit": "M2",
"justifications": [
  {
    "value": "don't worry",
    "selected": true
  },
  {
    "value": "be happy",
    "selected": false
  },
  {
    "value": "Other",
    "selected": true,
    "text": "My custom justification"
  }
]
}
```

Again, this is persisted in its entirety and the former justification values are invalidated.


As stated above, this is obviously inefficient over the wire, but prevents sloppy comparisons, etc. Whether we want to move forward with this scheme is of course open for debate.

**Comment by wpears** [comment]
The above scheme also captures the unverify use-case, as the `POST` again just has the selected option as `false` and the whole structure is persisted.

**Comment by hkeeler** [comment]
I think @wpears approach strikes a nice balance.  It handles unselecting justification, selecting multiple justifications, provides all the data needed to drive the UI, and keeps the same format on saving and retrieval.

Per @jmarin:
>So does this mean we need to update justifications as well?. How do we uniquely identify them? Maybe combination of `edit` and `justification`? (I don't like looking at strings for comparison though).  The justifications are stored in a database, so we need some way to filter that based on input from the user

I very much agree with this.  These justification descriptions may evolve over time.  I think it'd be better if the backend had some `id` for each to key off of.  As @jmarin says, these could be uniquely identified with a combined key of `edit` + `justification`.  Perhaps something like:

```json
{
"edit": "M2",
"justifications": [
  {
    "id": 1,
    "value": "don't worry",
    "selected": true
  },
  {
    "id": 2,
    "value": "be happy",
    "selected": false
  },
  {
    "id": 3,
    "value": "Other",
    "selected": true,
    "text": "My custom justification"
  }
]
}
```

**Comment by jmarin** [comment]
I think we might be getting somewhere. I get the convenience for the UI to get the full list all the time. You just issue a request and get everything you need to display the HTML. Unfortunately storing this as is makes for pretty sloppy data management: we're storing things that didn't happen ("empty" list of all edits). It's not just inefficient when going through the wire, it's a problem for long term maintenance, since this list will change (as a matter of fact, at this point we pretty much have no list, so we will be starting with a made up one). 
My preference would be to store __only__ the justifications that the user sent as part of their submission.  Any other data point is superfluous in the database. With an id I _think_ we can merge that with the full list and always return what the UI needs (the full list, updated with a "selected" flag for those that are also stored in the database). Need to think a bit about this, it might change a bit the semantics of what gets posted (it won't be the full list, but jus the justification that the user is interacting with at that time).

**Comment by hkeeler** [comment]
A few other thoughts on this:

1. I'm not sure `POST` is the best verb for submitting partial changes to the resource.  I think [`PATCH`](https://tools.ietf.org/html/rfc5789) is more appropriate.
1. How do we know that a given justification should accept the optional `text` field?
    1. It's `value` is "Other"?
    1. It has a `text` attribute returned?
    1. It is last in the list?

    I think any of these are going to be error prone and/or not-so-fun to validate on the backend.  I would prefer something more explicit.  Perhaps a `type` attribute?  Something like:

```json
{
"edit": "M2",
"justifications": [
  {
    "id": 1,
    "name": "Don't Worry",
    "type": "select",
    "value": true
  },
  {
    "id": 2,
    "name": "Be Happy",
    "type": "select",
    "value": false
  },
  {
    "id": 3,
    "name": "Other",
    "type": "text",
    "value": "My custom justification"
  }
]
}
```

...or a less elegant, but more explicit version where the text-base field gets it own section.  Something like:

```json
{
"edit": "M2",
"standardJustifications": [
  {
    "id": 1,
    "name": "Don't Worry",
    "value": true
  },
  {
    "id": 2,
    "name": "Be Happy",
    "value": false
  }
],
"otherJustification": "My custom justification"
}

```

**Comment by hkeeler** [comment]
Per @jmarin:
>My preference would be to store **only** the justifications that the user sent as part of their submission. Any other data point is superfluous in the database. With an id I think we can merge that with the full list and always return what the UI needs (the full list, updated with a "selected" flag for those that are also stored in the database).

I was thinking of it this way as well, but there could be some advantages to writing all justifications, not just the ones _selected_.
1. The backend logic is likely simpler.  If you only persist the _selected_ values, you have to check the current DB state, then figure out which justifications remain as-is, which get inserted, and which get deleted.  If you always persist all, it is always just an update.
    * I'm thinking in SQL terms here, so this _may_ not apply in the event stream world.
1. As we add new justifications over time, we'll be able to tell if the user didn't select a given justification, or if that justification just wasn't available at that time.  If we only persist _selected_ values, we'll lose the context of which possible justifications were there at the time of submission.

@jmarin, I'm not opposed to the way you're thinking about it.  I've used that same pattern in similar systems in the past, and it worked pretty well.  Just wanted to throw out some other considerations.

**Comment by wpears** [comment]
So let's assume we'll assign unique ids to each justification *per edit*. On `GET` from the front-end, the back-end looks up any previous justifications for this edit in the database and uses the result of this lookup to build the JSON for the response (if it's stored, `selected: true`). A `PATCH`/`PUT` (thanks for the correction @hkeeler) from the front-end will then only include the justification that triggered the request. This *may* be deselecting it, so on the `PATCH`/`PUT` the back-end will need to be able to remove entries from the DB.

Seems perfectly reasonable, though @hkeeler 's caveats should be kept in mind. The front-end can adjust pretty easily to either architecture.
