### ISSUE TITLE
IRS flow updates

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#729]
Due to https://github.com/cfpb/hmda-platform-ui/issues/286, we can clean up a few things around the status of a submission and in the API.

- [x] [submission status](https://github.com/cfpb/hmda-platform/blob/ac9f01670aa03aca7e03a1903e312b6db453fb65/Documents/submission-status.md) `11: IRS report verified - The IRS report has been verified by the financial institution and the submission can be signed.` is no longer required
- [x] the `POST` for the `/institutions/<institution>/filings/<period>/submissions/<submissionId>/irs` [endpoint](https://github.com/cfpb/hmda-platform/blob/ac9f01670aa03aca7e03a1903e312b6db453fb65/Documents/API.md) is no longer required
- [x] the `timestamp` and `receipt` on the `GET` for the `/institutions/<institution>/filings/<period>/submissions/<submissionId>/irs` [endpoint](https://github.com/cfpb/hmda-platform/blob/ac9f01670aa03aca7e03a1903e312b6db453fb65/Documents/API.md) are no longer required

_We should keep the status here (for now) but it will no longer need updated based on the IRS `POST`_

**Comment by awolfe76** [comment]
https://github.com/cfpb/hmda-platform-ui/pull/297 handles this for the front-end.

**Comment by schbetsy** [comment]
So, since we're removing IRSVerified (status 11), should the next status (Signed, status 12) get re-numbered to be 11?

**Comment by awolfe76** [comment]
Yes, I think so. If it's not a huge deal to do that right now.

**Comment by schbetsy** [comment]
Closed by #761.
