### ISSUE TITLE
Verify quality edits

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#747]

**Comment by awolfe76** [comment]
See https://github.com/cfpb/hmda-platform-ui/issues/288

**Comment by awolfe76** [comment]
There is one verification for all quality edits. This acts a lot like the `signature` endpoint.

It should be a `POST` to `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits/quality` with the request body being `{ verified: true } `.

The response should be:
```json
{
  "verified": true,
  "status": {
      "code": 8,
      "message": "validated with errors"
    }
}
```

The `status` could be either `8: validated with errors` or `9: validated`. The status of `9` would only happen if all macro edits were already verified (a filer could verify macro first even though that's not how we present them).

_We won't allow unchecking the quality checkbox. Instead we'll show a message on the front-end saying something like "If you think these edits are not correct, please fix and re-submit your file."_

---

_This part can be a separate issue._

We should also update the `GET` for the `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits` and `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits/quality` endpoints to include the `"verified": true,` or `"verified": false,`.

An example:

```json
{
  "syntactical": {},
  "validity": {},
  "quality": {
    "verified": false,
    "edits": []
  },
  "macro": []
}
```

**Comment by schbetsy** [comment]
When the user chooses `format=csv`, should the csv output show whether the Quality edits have been verified? If so, how should that look?

**Comment by schbetsy** [comment]
Question 2: From a back-end perspective, it would be easier to include the whole submission json in the response, rather than just the status. Like this:
```json
{
  "verified": true,
  "submission": {
    "id": {
      "institutionId": "1",
      "period": "2017",
      "sequenceNumber": 4
    },
    "status": {
      "code": 3,
      "message": "uploaded"
    },
    "start": 1486395364221,
    "end": 0
  }
}
```

Could that work?
