### ISSUE TITLE
IRS report

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#767]
Currently, the `/irs` endpoint is using mocked data. Now that it is a report of the only the data in the submission, and has no other dependencies, we can start to make this endpoint with real data.

The response format is the same as the mocked format in the [docs](https://github.com/cfpb/hmda-platform/blob/7f47895d0cecb5499736121da79c9b6d84d68e31/Documents/API.md), with the `status` removed.

Because there are no dependencies we'll have to update the [submission status](https://github.com/cfpb/hmda-platform/blob/7f47895d0cecb5499736121da79c9b6d84d68e31/Documents/submission-status.md) too. We shouldn't need the `10: IRS generated` status, we can remove it. The front-end will have to poll for the `/irs` endpoint to check if it's ready. We'll only start polling if the status is > `7: validating` (and if on the summary page). The endpoint should return an empty `msas: []` until the report is ready.

So the IRS report can start to be generated once status is > `7: validating`.

**Comment by lesgou** [comment]
The Institution Register Summary (IRS) report summarizes the submitted data by MSA/MD for a financial institution.

1. There are 7 main columns in the IRS report:

- [ ] Column 1:
**MSA/MD Number**

- [ ] Column 2:
**MSA/MD Name**

- [ ] Column 3:
**Total LARS**
a. This is a sum of the number of LARS reported in this MSA/MD (count the number of rows reported for this MSA/MD)

- [ ] Column 4:
**Total Amount ($000's)**
a. This is a sum of the **loan amount** reported in this MSA/MD
b. Rounded to the nearest thousand

- [ ] Column 5:
**Loan Type**
a. CONV (Loan Type = 1)
b. FHA (Loan Type = 2)
c. VA (Loan Type = 3)
d. FSA/RHS (Loan Type = 4)

- [ ] Column 6:
**Property Type**
a. 1-4 Family (Property Type = 1) 
b. Manuf Home (Property Type = 2) 
c. Multi Family (Property Type = 3)

- [ ] Column 7:
**Loan Purpose**
a. Home Purchase (Loan Purpose = 1)
b. Home Improve (Loan Purpose = 2)
c. Refinance (Loan Purpose = 3)


2. Each row in this report is an MSA/MD

3. The final row in this report summarizes the total for the financial institution for each of the following columns and sub-columns, where applicable: 
- [ ] Column 3
- [ ] Column 4
- [ ] Column 5:
a. CONV (Loan Type = 1)
b. FHA (Loan Type = 2)
c. VA (Loan Type = 3)
d. FSA/RHS (Loan Type = 4)
- [ ] Column 6:
a. 1-4 Family (Property Type = 1) 
b. Manuf Home (Property Type = 2) 
c. Multi Family (Property Type = 3)
- [ ] Column 7:
a. Home Purchase (Loan Purpose = 1)
b. Home Improve (Loan Purpose = 2)
c. Refinance (Loan Purpose = 3)

**Comment by nickgrippin** [comment]
@awolfe76: Leslie mentions a summary in her list (number 3)... Should that be part of the response?

**Comment by awolfe76** [comment]
Yeah, it will look like this:
![irs-footer](https://cloud.githubusercontent.com/assets/2932572/23517761/4b0d23c6-ff3f-11e6-8511-d99f21c9e9ed.png)

So maybe just add a `totals` object to the response:
```json
{
  "msas": [],
  "totals": {}
}
```
