### ISSUE TITLE
Store LAR data even if it has errors

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#768]
`HmdaFileValidator` should store LAR data even if it has validation errors, so a projection to the read side includes all the submitted data (in addition to this, `LARs` affected by quality errors will always be "validated with errors")

**Comment by schbetsy** [comment]
👍  This will be necessary for #718 and #717 (returning relevant field info about edit failures in the API) as well.

**Comment by schbetsy** [comment]
@jmarin Since this is a prerequisite for #717 & #718, would it be okay for me to work on it?

**Comment by jmarin** [comment]
@schbetsy This is also a dependency for #758 and I had already started work on it. I've extracted the relevant code and submitted a PR in #772. Thanks
