### ISSUE TITLE
Documentation for PanelCsvParser

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#805]
There were instructions in #797 for how to run and use the `PanelCsvParser`. Let's capture those in documentation so people will know how to use it.

Also note that the `HMDA_IS_DEMO` environment variable needs to be set. (via https://github.com/cfpb/hmda-platform/pull/801#issuecomment-278775104)

**Comment by jmarin** [comment]
Steps described [here](https://github.com/cfpb/hmda-platform/pull/868#issuecomment-285721131)
