### ISSUE TITLE
PSQL Exception in Panel Parser

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#807]
Running the Panel CSV Parser gets this error, unless I manually drop the `institutions` table in `psql`, which is tedious:
```
[error] (run-main-0) org.postgresql.util.PSQLException: ERROR: relation "institutions" already exists
org.postgresql.util.PSQLException: ERROR: relation "institutions" already exists
```

Update the Panel CSV Parser so it doesn't throw that error. We'll have to decide whether that means it should drop the `institutions` table first, or if it should allow adding additional institutions to the ones that are currently in the database.

**Comment by nickgrippin** [comment]
Does anyone have a comment on Betsy's question (whether to drop institutions table or add to existing table)?

**Comment by nickgrippin** [comment]
@jmarin, @schbetsy: Any thoughts on dropping the table or adding to existing table?  

I realize this probably opens up a much bigger can of worms about versioning panel data, but is there a short-term solution until we can implement to fix this bug?

**Comment by jmarin** [comment]
I vote for dropping it. My reasoning: this version of `HMDA Platform` is for 2017. There will be **one** panel for that year, and it won't be something that gets automatically updated. For version 2.0 I think this might not be the case, but I also see no point in worrying about that right now.
