### ISSUE TITLE
Signature endpoint with real data

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#814]
This endpoint is currently mocked. Will need to update it to use real data.

See the `/institutions/<institution>/filings/<period>/submissions/<submissionId>/sign` endpoint in the [API.md doc](https://github.com/cfpb/hmda-platform/blob/6ab278b3e1398a1b458049b04fd7b9273be6cd26/Documents/API.md).

**Comment by schbetsy** [comment]
For the `GET` action on this endpoint, what should be the response if the submission hasn't been signed?

Like this?
```json
{
  "timestamp": 0,
  "receipt": "",
  "status": {
      "code": 10,
      "message": "IRS report generated"
    }
}
```

For reference, I see in the docs that the response for a **signed** submission should look like this:
```json
{
  "timestamp": 1476809530772,
  "receipt": "asd0f987134asdlfasdflk",
  "status": {
      "code": 11,
      "message": "IRS report verified"
    }
}
```

**Comment by awolfe76** [comment]
@schbetsy - yep, that looks right to me. But it doesn't have to be `code: 10`, it should just be whatever the current status is.

**Comment by schbetsy** [comment]
What should happen if someone tries to un-sign the submission? (i.e. if we receive `{"signed": false}` as the payload to the `POST` action). Do we allow it? If so, what should the status become?

**Comment by awolfe76** [comment]
I don't think we should allow it. I think the only way to get out of the `signed` status is to trigger another upload, a re-file, which is handled differently than a `POST` to `/sign`.

**Comment by lesgou** [comment]
Agree with @awolfe76

**Comment by schbetsy** [comment]
What exactly should the receipt hash be? Can I store it in plain text on the `Submission` object? 
cc @jmarin

**Comment by jmarin** [comment]
@schbetsy might want to check with @awolfe76 or @wpears to see what it is that they expect the hash to be. As for storing it as plain text in `Submission` I don't see an issue with it

**Comment by awolfe76** [comment]
I don't have a strong opinion on what the hash is; it's just something that we are giving the filer so that they could use it to confirm that they have signed the submission. It would also have to be saved on the back-end as "part of" that submission.
