### ISSUE TITLE
CSV downloads with no content

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#820]
It's possible that we show a link to a CSV download (on the institutions listing page) that contain no edits.

Can the response, in this case, show that? Can it say something like `No edits for this submission`?

**Comment by nickgrippin** [comment]
Are you asking for a file that has that line of text in it?  That seems like an unnecessary API call, especially to have a user go through the process of saving the file, opening it, and only seeing that line of text.

Would it be possible to make that a message or pop-up in the UI?

**Comment by awolfe76** [comment]
Let me see what I can do. To know whether the edits exist we'd have to make an API call anyway. BUT, I may be able to do something based on the status of each submission, which we do know.

**Comment by awolfe76** [comment]
I think https://github.com/cfpb/hmda-platform-ui/pull/389 will handle this.
