### ISSUE TITLE
Pagination for edits

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#845]
_Pulls the `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits/<type>/<edit>` endpoint out of #719. Details coming._

**Comment by awolfe76** [comment]
To be able to add pagination to edits we need to paginate on the specific edits, eg S020, instead of the edit types. This will require a new endpoint for each edit, `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits/<type>/<edit>`, and will cause updates to the [`/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits`](https://github.com/cfpb/hmda-platform/blob/23a1dff0463e84db9c55972bb73ec2dfac9b67dc/Documents/API.md#edits) endpoint as well.

_**Note**: the UI is currently NOT using the [`/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits/<type>`](https://github.com/cfpb/hmda-platform/blob/23a1dff0463e84db9c55972bb73ec2dfac9b67dc/Documents/API.md#edits-by-type) endpoints, but changes would be required there as well._

#### Update the `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits`

Update this endpoint to return a list of edits. For example:

```json
{
  "syntactical": {
    "edits": [
      {
        "edit": "S020",
        "description": "Agency code must = 1, 2, 3, 5, 7, 9. The agency that submits the data must be the same as the reported agency code."
      },
      {
        "edit": "S010",
        "description": "The first record identifier in the file must = 1 (TS). The second and all subsequent record identifiers must = 2 (LAR)."
      }
    ]
  },
  "validity": {
    "edits": []
  },
  "quality": {
    "verified": false,
    "edits": []
  },
  "macro": {
    "edits": []
  }
}
```

This would allow someone to get the full list of edits and rows and then, in the case of sorting by edits, make API calls for the details of each specific edit.

#### Create the `/institutions/<institution>/filings/<period>/submissions/<submissionId>/edits/<type>/<edit>` endpoint

The would return the details for an edit and include the pagination information. For example:

```json
{
  "edit": "S020",
  "rows": [
    {
      "row": {
        "rowId": "Transmittal Sheet"
      },
      "fields": {
        "Agency Code": 10
      }
    },
    {
      "row": {
        "rowId": "8299422144"
      },
      "fields": {
        "Agency Code": 10
      }
    }
  ],
  "count": 20,
  "total": 130,
  "_links": {
    "first": "?page=1",
    "prev": "?page=1",
    "self": "?page=1",
    "next": "?page=2",
    "last": "?page=7",
    "href": "/institutions/1/filings/2017/submissions/1/edits/S020"
  }
}
```

**Comment by schbetsy** [comment]
Are the requirements for this ticket finished? Should it still be assigned to @awolfe76 ?

**Comment by awolfe76** [comment]
I think the requirements are ok and that this is safe to re-assign now.

**Comment by schbetsy** [comment]
This update makes it more complicated to provide a CSV summary of edits. 

**My reasoning**: We would need to decide and document which of the edits endpoints (`/edits`, `/edits/<edit>`, and `/edits/<type>`) would respond to the `?format=csv` param, and how. Also, the collection of data returned in the JSON endpoints is very different from what we're returning in CSV. So, it's looking more and more beneficial to separate the JSON generation code from the CSV generation code.

**My opinion**: I think it would be cleaner to have a separate endpoint for CSV response, like this: `/institutions/<institutionId>/filings/<period>/submissions/<seqNr>/edits/csv`, which would return this:

```csv
editType, editId, loanId
syntactical, S025, Transmittal Sheet
syntactical, S025, s1
syntactical, S025, s2
syntactical, S025, s3
syntactical, S010, s4
syntactical, S010, s5
macro, Q007
```

Then, the other edits endpoints wouldn't have to handle the CSV parameter or generate the CSV data.

Would that work? If so, it would make this ticket easier to implement.

**Comment by nickgrippin** [comment]
I like this approach, it will definitely clean up the back-end code a bit. 👍

**Comment by jmarin** [comment]
I'm ok with this approach
