### ISSUE TITLE
Modify the approval process for macro quality edits

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-platform#846]
Instead of having the user provide a justification for macro quality edits, the process will now be the same as with quality macro edits. The user will confirm through a check box that the data are correct.

**Comment by awolfe76** [comment]
This will be almost exactly like the `POST` for  [`/quality`](https://github.com/cfpb/hmda-platform/blob/master/Documents/API.md#edits-by-type). It should also return the `status`.

**Comment by schbetsy** [comment]
We'll need to update the Edits By Type endpoint too. With justifications gone, should the macro results look like this?

```json
  "macro": {
    "verified": false,
    "edits": [
      {
        "edit": "Q008",
        "edit": "Q070"
      }
    ]
  }
```

**Comment by awolfe76** [comment]
@schbetsy - that looks right to me and would follow what we've talked about for [pagination](https://github.com/cfpb/hmda-platform/issues/845) (to do later).
