### ISSUE TITLE
Persisting file name causes parsing stream to fail

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#852]

**Comment by nickgrippin** [comment]
Just an update as I continue to debug this ticket: the file upload and persistence seem to work, but when the parser tries to pull the list of events, it can't seem to find anything (around [here](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/scala/hmda/persistence/processing/HmdaFileParser.scala#L78)).
