### ISSUE TITLE
Remove sortBy option for /edits

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#853]
We no longer need the `?sortBy` option for the [`/edits` endpoint](https://github.com/cfpb/hmda-platform/blob/dd0f42549c4f59d0254ee8fa57e6c85304a05c4f/Documents/API.md#edits). The csv download will allow sorting by row if necessary.

**Comment by schbetsy** [comment]
It's also unnecessary for the edits by type endpoint, correct? i.e. `/institutions/<institutionId>/filings/<period>/submissions/<submissionId>/edits/<syntactical|validity|quality|macro>`

If it's unnecessary for both endpoints, I can remove all of the code that supports sorting edits by row.

**Comment by awolfe76** [comment]
@schbetsy - yep, I think that works.
