### ISSUE TITLE
Add pagination to IRS

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#864]
Using the same idea/format from #821, add pagination to the IRS endpoint.

**Comment by schbetsy** [comment]
Is the current implementation of IRS (and `FilingComponent`) Postgres-dependent? Since we're planning to replace Postgres with a different read storage technology, should I hold off on this ticket? @jmarin

**Comment by jmarin** [comment]
`IRS` is currently using `postgres`. I think it's ok to work on this ticket, since we already have this in place but the expected functionality is not complete. We can migrate it later

**Comment by schbetsy** [comment]
After this change, the IRS endpoint will respond with the JSON format below. In addition to the top-level fields it had before (`msas` and `totals`), it will now also have `count`, `total`, and `_links`, the pagination metadata.

```json
{
  "msas": [
    {
      "id": "123",
      "totalLARS": 4,
      "totalAmount": 123,
      "conv": 4,
      "FHA": 0,
      "VA": 0,
      "FSA": 0,
      "oneToFourFamily": 4,
      "MFD": 0,
      "multiFamily": 0,
      "homePurchase": 0,
      "homeImprovement": 0,
      "refinance": 4
    },
    {
      "id": "456",
      "totalLARS": 5,
      "totalAmount": 456,
      "conv": 5,
      "FHA": 0,
      "VA": 0,
      "FSA": 0,
      "oneToFourFamily": 5,
      "MFD": 0,
      "multiFamily": 0,
      "homePurchase": 0,
      "homeImprovement": 0,
      "refinance": 5
    }
  ],
  "totals": {
    "homeImprovement": 0,
    "multiFamily": 0,
    "lars": 9,
    "FSA": 0,
    "FHA": 0,
    "amount": 579,
    "oneToFourFamily": 9,
    "refinance": 9,
    "MFD": 0,
    "conv": 9,
    "homePurchase": 0,
    "VA": 0
  },
  "count": 20,
  "total": 130,
  "_links": {
    "first": "?page=1",
    "prev": "?page=1",
    "self": "?page=1",
    "next": "?page=2",
    "last": "?page=7",
    "href": "/institutions/1/filings/2017/submissions/1/irs{rel}"
  }
}
```

Question: This endpoint doesn't return the submission status. Should it?

**Comment by awolfe76** [comment]
I don't think we need the submission status here. The IRS doesn't require verification so it doesn't start/stop the process (though it used to).

But, if we wanted to have it for consistency it doesn't hurt anything.
