### ISSUE TITLE
Figure out Respondent ID/Institution ID

### ISSUE THREAD

**Issue by nickgrippin** [cfpb/hmda-platform#877]
Our current implementation of Institution ID uses the [`id_rssd` field](https://github.com/cfpb/hmda-platform/blob/master/parser/shared/src/main/scala/hmda/parser/fi/InstitutionParser.scala#L18) from the panel file.

However, when storing LARs in the PSQL database, we only store the exact LAR itself, absent any information about who submitted it.  This means that when retrieving the LAR for either [the modified LAR endpoint](https://github.com/cfpb/hmda-platform/blob/master/api/src/main/scala/hmda/api/http/public/PublicLarHttpApi.scala#L26) or [the IRS endpoin](https://github.com/cfpb/hmda-platform/blob/master/api/src/main/scala/hmda/api/http/institutions/submissions/SubmissionIrsPaths.scala#L38)t, we filter by respondent_id, since we have no other information about the Institution with which to look up/filter the database.

In reality, id_rssd and respondent_id will rarely match.  We need to address this by providing a way for us to look up LARs by `id_rssd`.

**Comment by schbetsy** [comment]
One idea that would resolve most of the mismatches between RespondentID and InstitutionID without having to restructure persistence:

1. Within the IRS endpoint, get the full `SubmissionId` (`institutionID`, `period`, and `seqNr`), from the path parameters.
2. Use the `SubmissionID` to access the `HmdaFileValidationState` for that submission. 
3. From there, get the Transmittal Sheet for that submission, which has the respondent ID for that file.
4. Use that respondent ID to query the `lars_total_msa` database.

**Comment by nickgrippin** [comment]
That's a great idea, and it could definitely work.  My only concern is if RSSD to Respondent ID is a 1:1 mapping (e.g. there are two institutions with the same Respondent ID).  @Kibrael, any thoughts?

**Comment by nickgrippin** [comment]
All right, I just talked with David, and this can definitely work!  The only change is that we'll need to get both respondent ID and agency code, then filter the database on those two fields.  

Respondent ID alone isn't a guaranteed unique field, but it is when combined with agency code.

**Comment by Kibrael** [comment]
RSSD to Respondent ID is 1:1.

Prepending Agency Code to Respondent ID is the convention for getting a unique Respondent ID (often abbreviated as ARID).

**Comment by hkeeler** [comment]
Why don't we want to add an `institution_id` onto the LAR table?  That seems like the cleanest solution.  You _always_ have an `institution_id` from the URL, and wouldn't require any extra logic to do the query.  Also, can't `respondent_id` change from year-to-year?  Will we have to come up with even more logical workarounds to look up past years LARs?

**Comment by Kibrael** [comment]
Yes respondent_id can change year over year. All of them are changing in 2018 to LEI.

**Comment by hkeeler** [comment]
>Yes respondent_id can change year over year. All of them are changing in 2018 to LEI.

Right, but can't `respondent_id` also be different for past years if the regulator for an institution changes?   I know this isn't common, but does happen, right?  I guess it will stop happening being an issue once LEI is there for all past LARs we need to lookup, but seems like a possibility in the meantime.

**Comment by Kibrael** [comment]
@hkeeler you are absolutely correct.

Research/Markets work with the Avery file as it has some linkage between years for identifiers in the HMDA data.

**Comment by nickgrippin** [comment]
So, it sounds like adding the institution ID (or RSSD) to the LAR table is the best solution here...  Will we run into any issues with that changing from year to year?

**Comment by Kibrael** [comment]
RSSD will be insufficient to populate institution ID when we start using NMLS and MCR data. That is likely to happen in 2018. With luck LEI will be the solution and can populate institution ID.

**Comment by hkeeler** [comment]
>Will we run into any issues with that changing from year to year?

We'll definitely have to do...something for 2018. :)  Assuming LEI is a reliable identifier available across all datasources, the cleanest approach would be to a full refactor, replacing RSSD ID with LEI for all references to `institution_id` everywhere.  However, I don't think we'll know for certain until we do a deeper dive into LEI.

**Comment by Kibrael** [comment]
Agree with @hkeeler. I think we've solved the 2017 portion and know we have 2018 work to do.
