### ISSUE TITLE
Add MSA Title to IRS response

### ISSUE THREAD

**Issue by nickgrippin** [cfpb/hmda-platform#892]
The MSA title will be the "CBSA Title" field in the [`jul_2015_cbsa.csv`](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/resources/jul_2015_cbsa.csv) file.  The field `name` should be added to the [MSA object](https://github.com/cfpb/hmda-platform/blob/master/query/src/main/scala/hmda/query/model/filing/Msa.scala), and can be looked up based on the `id` field.

**Comment by nickgrippin** [comment]
@awolfe76, @wpears: If the MSA doesn't have a name (i.e. the field has "NA"), should the name be populated with "NA", or should it be empty?

**Comment by awolfe76** [comment]
I think it would be best to use "NA" for now, since that is what the report shows.

**Comment by lesgou** [comment]
@feomike should we look into why NA's are populating for MSAs?
