### ISSUE TITLE
Institution search returning 404

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#897]
With the new data added I'm seeing a 404 returned from the institution search during the registration process.

From the [sample data file](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/resources/demoInstitutions.csv) it looks like 

- [bank0.com](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/resources/demoInstitutions.csv#L2)
- [bank1.com](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/resources/demoInstitutions.csv#L3)
- [cnbstl.com](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/resources/demoInstitutions.csv#L5)
- [consumercreditunion.com](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/resources/demoInstitutions.csv#L103)

should return an institution. Instead I'm seeing a 404 `{"httpStatus":404,"message":"email domain consumercreditunion.com not found","path":"/institutions"}`.

**Comment by nickgrippin** [comment]
In addition to this bug, I've also found that searching for an empty string seems to return all stored institutions.  Should an empty string search be allowed on this endpoint?

**Comment by nickgrippin** [comment]
Ah, so the problem is that the new panel data doesn't contain emails in the form of `test@bank0.com`, they're now just `bank0.com`, which resulted in our search not returning anything.  Putting in a fix now.
