### ISSUE TITLE
Update readme to show new changes to bank data

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#904]
We list the available institutions in the readme, within the ["to run the entire platform"](https://github.com/cfpb/hmda-platform#to-run-the-entire-platform) section. We should update that with the new institution data.

**Comment by nickgrippin** [comment]
Could this issue just be combined with [your other PR](https://github.com/cfpb/hmda-platform/pull/903)?

**Comment by awolfe76** [comment]
Good call, for some reason thought it was merged already.
