### ISSUE TITLE
Return descriptions for macro edits

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#905]
Other edit types return the description of the specific edit. We should do the same for macro edits.

See the [docs](https://github.com/cfpb/hmda-platform/blob/master/Documents/API.md#edits).

**Comment by awolfe76** [comment]
We should return the fields for macro too. Should that be another issue or can we add that here?

**Comment by schbetsy** [comment]
I'm actually adding descriptions to macro results as part of #845.

**Comment by schbetsy** [comment]
And re: adding the fields for macros: I think this should be a separate issue, since there are design/business questions involved.

**Comment by awolfe76** [comment]
Closing this. As @schbetsy mentioned the descriptions will be added in #845 and #908 is created to handle the fields.
