### ISSUE TITLE
Create filing when institution is created

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#915]
A filing for the current year should be created for every institution loaded from panel (add this to `PanelCsvParser`)

**Comment by nickgrippin** [comment]
In creating a Filing object, we have a flag called `filingRequired`.  How should this be set when reading in the Panel data?

**Comment by schbetsy** [comment]
(I don't have the Panel knowledge to answer your question, but) I believe that there isn't any logic in the app that hinges on that value. So, if it isn't set correctly, I suspect it won't matter for now.

**Comment by schbetsy** [comment]
What should happen when someone creates an institution record via the admin API? Will there be a separate mechanism for creating filings for those institutions?

**Comment by jmarin** [comment]
After this ticket goes in, the panel should be only loaded through the admin API. See #938

**Comment by schbetsy** [comment]
I don't understand. Why are we updating `PanelCsvParser` if we're never going to use it? If we're only going to use `InstitutionAdminHttpApi`, how will Filing objects get created for the Institutions?

**Comment by jmarin** [comment]
I didn't say we were not going to use it. What I mean is that `PanelCsvParser` should use the admin API to load data, instead of creating new (and separate) instances of the Hmda `ActorSystem` and child actors. This will require extending the `InstitutionAdminHttpApi` to create the filings when institution are inserted. The idea is that the `PanelCsvParser` ends up being a standalone jar file that can be executed from any machine and loads data through HTTP

**Comment by schbetsy** [comment]
Okay, I think I understand. 

Considering the architecture change you've described, is this ticket still useful? It sounds like any Filing-related code in `PanelCsvParser` will be obsolesced as soon as #938 happens, since we'll want to use the correct actor system to create the filings.
