### ISSUE TITLE
Validation (2017): S025 (Control Number)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#94]
**Edit #:** S025
**Type:** Syntactical
**Category:** Transmittal Sheet (TS) & Loan/Application Register (LAR)
**Column:** Control Number

Control number must = a valid respondent identifier/agency code combination for date processed.

Additional resources:
* [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
* [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
* [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by kgudel** [comment]
This seems like it requires panel.

**Comment by schbetsy** [comment]
What is the control number? I don't see a "Control Number" column in the filespec. (@lesgou ?)

**Comment by lesgou** [comment]
@schbetsy It looks like control number is the combination of respondent id + agency code.
so, respondent id and agency code in row 1 of the data = respondent id and agency code in panel (which is currently not a concatenated field)

**Comment by schbetsy** [comment]
Marking as "blocked". We will need panel to be implemented, so we can check against it that each Transmittal Sheet has an appropriate combination of Respondent ID and Agency Code.

Thanks @lesgou!
