### ISSUE TITLE
Add commas to displayed data

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-platform#949]
Recommend adding commas to the displayed data in edits and in the IRS.

For example, 68792 should be displayed as 68,792

![image](https://cloud.githubusercontent.com/assets/9752096/25619605/5802d8fa-2f00-11e7-8019-62839592e772.png)

**Comment by jmarin** [comment]
I think this belongs in `hmda-platform-ui`?

**Comment by lesgou** [comment]
@awolfe76 agrees.
