### ISSUE TITLE
HMDA pipe character in the pipe delimited format

### ISSUE THREAD

**Issue by EvelyneBenie** [cfpb/hmda-platform#956]
Is there a way to escape a pipe character if there is a pipe in the text? My team ran into an issue where the property address contained a pipe in the text

**Comment by feomike** [comment]
thanks for the comment @EvelyneBenie.  Following address standards outlined in USPS Publication 28, there shouldn't be a pipe character in address text.  We recommend removing it from the address prior to submission.  We are not planning on having an escape character, in the 2018 file specifications.
