### ISSUE TITLE
Validation (2017): S013 (Timestamp)

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#97]
**Edit #:** S013
**Type:** Syntactical
**Category:** Transmittal Sheet (only)
**Column:** Timestamp

Timestamp must be later than timestamp on database.

Additional resources:
- [FFIEC's 2016 HMDA File Spec](https://www.ffiec.gov/hmda/pdf/spec2016.pdf)
- [FFIEC's 2016 HMDA Edits](https://www.ffiec.gov/hmda/pdf/edit2016.pdf)
- [CFPB's 2017 HMDA File Spec](http://www.consumerfinance.gov/hmda/static/for-filers/2017/2017-HMDA-File-Specifications.pdf)

**Comment by kgudel** [comment]
This is already [partially implemented](https://github.com/cfpb/hmda-platform/blob/master/validation/src/main/scala/hmda/validation/rules/ts/syntactical/S013.scala), it checks that the time stamp is greater than some other time which is passed in as a variable. However, it is not clear what that database variable should reference, and it does not seem to align with the transactional model of our back end.

**Comment by schbetsy** [comment]
Marking as "blocked", since we haven't decided how to proceed. Need to decide what to use as the "database", or--if this edit is actually irrelevant with the new architecture--whether the edit can be removed.

**Comment by lesgou** [comment]
This edit is no longer relevant due to changes in the architecture.
