### ISSUE TITLE
Update "validated with errors" submission status description

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#990]
See the [doc](https://github.com/cfpb/hmda-platform/blob/master/Documents/submission-status.md)

See [this issue](https://github.com/cfpb/hmda-platform-ui/issues/564) too.

The message currently says `The data validation process is complete, but there are edits that need to be addressed. The filing process may not proceed until the file has been corrected and reuploaded.` But this isn't correct when there are quality/macro edits ... in that case the file doesn't have to be corrected and reuploaded.

@lesgou - can we just drop the last sentence or would you like to change it to something else?

**Comment by lesgou** [comment]
@awolfe76 How about:

The data validation process is complete, but there are edits that may need to be addressed. Please correct the file, if needed, and reupload. Or, if the data are correct, please verify the data below by selecting the checkbox.

**Comment by awolfe76** [comment]
What if we just drop the second sentence? Making the message:
`The data validation process is complete, but there are edits that need to be addressed.`

**Comment by lesgou** [comment]
@awolfe76 How about:

The data validation process is complete, but there are edits that may need to be addressed.
