### ISSUE TITLE
Request for details regarding boundaries file

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-platform#999]
I would like to confirm the effective dates pulled for the data in this [file](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/resources/jul_2015_cbsa.csv) are:

1. MSA/MD: 7/15/2015.    
1. County: 2010 Census for geography boundaries, but 2000 census for small population determination
1. Census Tract: 2010 Census

**Comment by kgudel** [comment]
So the data that we use is actually contained in 5 files: 2 contain information about population, one for states and one for Puerto Rico, 1 file simply for state abbreviations, 1 for census tracts, and 1 for MSAs.

The provenance for each of these files can actually be found in the first lines of the code that parsers the files, I'll include these lines below:

1. State Populations
   * Source: [2000-2010_pop_estimates.csv](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/resources/2000-2010_pop_estimates.csv)
   * Provenance: [StatesPopLookup](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/scala/hmda/census/model/StatesPopLookup.scala#L3-L5)

2. Puerto Rico Populations
   * Source: [PRM-EST00INT-AGESEX-5YR.csv](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/resources/PRM-EST00INT-AGESEX-5YR.csv)
   * Provenance: [PrPopLookup](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/scala/hmda/census/model/PrPopLookup.scala#L3-L5)

3. Census Tracts
   * Source: [us2010trf.txt](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/resources/us2010trf.txt)
   * Provenance: [TractLookup](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/scala/hmda/census/model/TractLookup.scala#L3-L5)

4. MSAs
   * Source: [jul_2015_cbsa.csv](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/resources/jul_2015_cbsa.csv)
   * Provenance: [CbsaLookup](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/scala/hmda/census/model/CbsaLookup.scala#L5-L8)

5. State Abbreviations
   * Source:[state.csv](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/resources/state.csv)
   * Provenance: [StateAbrvLookup](https://github.com/cfpb/hmda-platform/blob/master/census/src/main/scala/hmda/census/model/StateAbrvLookup.scala#L3-L5)

The Provenance includes 3 sections: a short description of what the file is being used for, the site that the file was taken from (this site usually has more specific information about the file and a link to the file itself), and a link to the file.

In looking at these links to put together this explanation I have also noticed that some of the included links have died. Is it worthwhile to find the new links to these files?

**Comment by lesgou** [comment]
Thanks for the info.

I would recommend updating the dead links.
